#config_version=6

mode:
  start_events: start_training_select
  stop_events: mode_base_stopping, stop_training_select
  priority: 600

event_player: 
  mode_training_select_started:
    - enable_scoop_hold
    - stop_training_qualify
    - show_training_completed_shots
  mode_training_select_started{current_player.training_heal_achieved==1}:
    - show_heal_completed
  mode_training_select_started{current_player.training_cluster_bomb_achieved==1}:
    - show_cluster_bomb_completed
  mode_training_select_started{current_player.training_proton_cannon_achieved==1}:
    - show_proton_cannon_completed
  mode_training_select_started{current_player.training_moon_missile_achieved==1}:
    - show_moon_missile_completed
  mode_training_select_started{current_player.training_ship_save_achieved==1}:
    - show_ship_save_completed
  mode_training_select_started{current_player.training_shields_achieved==1}:
    - show_shields_completed
  s_LeftFlipperButton_active:
    - training_select_left
  s_RightFlipperButton_active:
    - training_select_right
  s_LeftMagnaButton_active:
    - make_selection
  s_RightMagnaButton_active:
    - make_selection
  s_lockbar_key_active:
    - make_selection
  timer_training_select_complete:
    - make_selection
  make_selection:
    - release_scoop_hold
  release_scoop_hold:
    - disable_scoop_hold
  timer_training_select_tick{device.timers.training_select.ticks == 3}:
    - selection_hurry_up
  make_selection{device.state_machines.training_select.state=="heal"}:
    - start_training_heal
    - stopping_training_select
  make_selection{device.state_machines.training_select.state=="cluster_bomb"}:
    - start_training_cluster_bomb
    - stopping_training_select
  make_selection{device.state_machines.training_select.state=="proton_cannon"}:
    - start_training_proton_cannon
    - stopping_training_select
  make_selection{device.state_machines.training_select.state=="moon_missile"}:
    - start_training_moon_missile
    - stopping_training_select
  make_selection{device.state_machines.training_select.state=="ship_save"}:
    - start_training_ship_save
    - stopping_training_select
  make_selection{device.state_machines.training_select.state=="shields"}:
    - start_training_shields
    - stopping_training_select
  make_selection{device.state_machines.training_select.state=="skip"}:
    - stop_training_select
    - stop_training
  stopping_training_select:
    - training_music_start
    - meteor_wave_music_stop
    - stop_training_select
  balldevice_moon_lock_ball_enter{device.ball_devices.moon_lock.balls > current_player.moon_launch_locked_balls}:
    - delayed_release_moon_ball
  check_ts_heal{current_player.ts_last_move=="left" and current_player.training_heal_achieved==1}:
    - training_select_left
  check_ts_heal{current_player.ts_last_move=="right" and current_player.training_heal_achieved==1}:
    - training_select_right
  check_ts_cluster_bomb{current_player.ts_last_move=="left" and current_player.training_cluster_bomb_achieved==1}:
    - training_select_left
  check_ts_cluster_bomb{current_player.ts_last_move=="right" and current_player.training_cluster_bomb_achieved==1}:
    - training_select_right
  check_ts_proton_cannon{current_player.ts_last_move=="left" and current_player.training_proton_cannon_achieved==1}:
    - training_select_left
  check_ts_proton_cannon{current_player.ts_last_move=="right" and current_player.training_proton_cannon_achieved==1}:
    - training_select_right
  check_ts_moon_missile{current_player.ts_last_move=="left" and current_player.training_moon_missile_achieved==1}:
    - training_select_left
  check_ts_moon_missile{current_player.ts_last_move=="right" and current_player.training_moon_missile_achieved==1}:
    - training_select_right
  check_ts_ship_save{current_player.ts_last_move=="left" and current_player.training_ship_save_achieved==1}:
    - training_select_left
  check_ts_ship_save{current_player.ts_last_move=="right" and current_player.training_ship_save_achieved==1}:
    - training_select_right
  check_ts_shields{current_player.ts_last_move=="left" and current_player.training_shields_achieved==1}:
    - training_select_left
  check_ts_shields{current_player.ts_last_move=="right" and current_player.training_shields_achieved==1}:
    - training_select_right
  show_training_completed_shots{current_player.shot_training_health1==1}:
    - heal_1_completed
  show_training_completed_shots{current_player.shot_training_health2==1}:
    - heal_2_completed
  show_training_completed_shots{current_player.shot_training_health3==1}:
    - heal_3_completed
  show_training_completed_shots{current_player.shot_training_health4==1}:
    - heal_4_completed
  show_training_completed_shots{current_player.shot_training_health5==1}:
    - heal_5_completed
  show_training_completed_shots{current_player.shot_training_health6==1}:
    - heal_6_completed
  show_training_completed_shots{current_player.shot_training_health7==1}:
    - heal_7_completed
  show_training_completed_shots{current_player.shot_training_health8==1}:
    - heal_8_completed
  show_training_completed_shots{current_player.shot_training_health9==1}:
    - heal_9_completed
  show_training_completed_shots{current_player.shot_training_cluster_charge1==1}:
    - cluster_bomb_1_completed
  show_training_completed_shots{current_player.shot_training_cluster_charge2==1}:
    - cluster_bomb_2_completed
  show_training_completed_shots{current_player.shot_training_cluster_charge3==1}:
    - cluster_bomb_3_completed
  show_training_completed_shots{current_player.shot_training_proton_charge1==1}:
    - proton_cannon_1_completed
  show_training_completed_shots{current_player.shot_training_proton_charge2==1}:
    - proton_cannon_2_completed
  show_training_completed_shots{current_player.shot_training_proton_charge3==1}:
    - proton_cannon_3_completed
  show_training_completed_shots{current_player.shot_training_moon_lane1==1}:
    - moon_missile_1_completed
  show_training_completed_shots{current_player.shot_training_moon_lane2==1}:
    - moon_missile_2_completed
  show_training_completed_shots{current_player.shot_training_moon_lane3==1}:
    - moon_missile_3_completed
  show_training_completed_shots{current_player.shot_training_moon_lane4==1}:
    - moon_missile_4_completed
  show_training_completed_shots{current_player.shot_training_ship_charge1==1}:
    - ship_save_1_completed
  show_training_completed_shots{current_player.shot_training_ship_charge2==1}:
    - ship_save_2_completed
  show_training_completed_shots{current_player.shot_training_ship_charge3==1}:
    - ship_save_3_completed
  show_training_completed_shots{current_player.shot_training_shield_charge1==1}:
    - shields_1_completed
  show_training_completed_shots{current_player.shot_training_shield_charge2==1}:
    - shields_2_completed
  show_training_completed_shots{current_player.shot_training_shield_charge3==1}:
    - shields_3_completed


light_player: 
  heal_1_completed: 
    LH1: 
      color: 00dd00
      priority: 100

  heal_2_completed: 
    LH2: 
      color: 00dd00
      priority: 100

  heal_3_completed: 
    LH3: 
      color: 00dd00
      priority: 100

  heal_4_completed: 
    LH4: 
      color: 00dd00
      priority: 100

  heal_5_completed: 
    LH5: 
      color: 00dd00
      priority: 100

  heal_6_completed: 
    LH6: 
      color: 00dd00
      priority: 100

  heal_7_completed: 
    LH7: 
      color: 00dd00
      priority: 100

  heal_8_completed: 
    LH8: 
      color: 00dd00
      priority: 100

  heal_9_completed: 
    LH9: 
      color: 00dd00
      priority: 100

  cluster_bomb_1_completed: 
    LCC1: 
      color: dd00dd
      priority: 100

  cluster_bomb_2_completed: 
    LCC2: 
      color: dd00dd
      priority: 100

  cluster_bomb_3_completed: 
    LCC3: 
      color: dd00dd
      priority: 100

  proton_cannon_1_completed: 
    LPC1: 
      color: 00dddd
      priority: 100

  proton_cannon_2_completed: 
    LPC2: 
      color: 00dddd
      priority: 100

  proton_cannon_3_completed: 
    LPC3: 
      color: 00dddd
      priority: 100

  moon_missile_1_completed: 
    LML1: 
      color: ccbb00
      priority: 100

  moon_missile_2_completed: 
    LML2: 
      color: ccbb00
      priority: 100

  moon_missile_3_completed: 
    LML3: 
      color: ccbb00
      priority: 100

  moon_missile_4_completed: 
    LML4: 
      color: ccbb00
      priority: 100

  ship_save_1_completed: 
    LF1: 
      color: 0500ee
      priority: 100

  ship_save_2_completed: 
    LF2: 
      color: 0500ee
      priority: 100

  ship_save_3_completed: 
    LF3: 
      color: 0500ee
      priority: 100

  shields_1_completed: 
    LSC1: 
      color: 0010cc
      priority: 100

  shields_2_completed: 
    LSC2: 
      color: 0010cc
      priority: 100

  shields_3_completed: 
    LSC3: 
      color: 0010cc
      priority: 100


random_event_player: 
  training_music_start: 
    events:
      training_music_1_start: 1
      training_music_2_start: 1
      training_music_3_start: 1
      training_music_4_start: 1
      training_music_5_start: 1
    scope: player


segment_display_player: 
  mode_training_select_started: 
    player1: 
      text: " "
      flashing: off
    player2: 
      text: "SELECT"
      flashing: off
    player4: 
      text: " "
      flashing: off

  heal_selected{current_player.training_heal_achieved==0}: 
    player3: 
      text: "HEAL "
      flashing: off

  cluster_bomb_selected{current_player.training_cluster_bomb_achieved==0}: 
    player3: 
      text: "CLUSTER"
      flashing: off

  proton_cannon_selected{current_player.training_proton_cannon_achieved==0}: 
    player3: 
      text: "PROTON"
      flashing: off

  moon_missile_selected{current_player.training_moon_missile_achieved==0}: 
    player3: 
      text: "MOON "
      flashing: off

  ship_save_selected{current_player.training_ship_save_achieved==0}: 
    player3: 
      text: "SAVER "
      flashing: off

  shields_selected{current_player.training_shields_achieved==0}: 
    player3: 
      text: "SHIELDS"
      flashing: off

  skip_selected: 
    player3: 
      text: "SKIP "
      flashing: off


shots: 
  select_heal:
    profile: training_select
    restart_events: heal_unselected, make_selection
    show_tokens: 
      lights: "tHeal"
      color: "00dd00"
    control_events: 
      - events: heal_selected{current_player.ts_hurry_up==0}
        state: 1
      - events: heal_selected{current_player.ts_hurry_up==1}, selection_hurry_up{device.state_machines.training_select.state=="heal"}
        state: 2
  select_cluster_bomb:
    profile: training_select
    restart_events: cluster_bomb_unselected, make_selection
    show_tokens: 
      lights: "tClusterAll"
      color: "dd00dd"
    control_events: 
      - events: cluster_bomb_selected{current_player.ts_hurry_up==0}
        state: 1
      - events: cluster_bomb_selected{current_player.ts_hurry_up==1}, selection_hurry_up{device.state_machines.training_select.state=="cluster_bomb"}
        state: 2
  select_proton_cannon:
    profile: training_select
    restart_events: proton_cannon_unselected, make_selection
    show_tokens: 
      lights: "tProtonAll"
      color: "00dddd"
    control_events: 
      - events: proton_cannon_selected{current_player.ts_hurry_up==0}
        state: 1
      - events: proton_cannon_selected{current_player.ts_hurry_up==1}, selection_hurry_up{device.state_machines.training_select.state=="proton_cannon"}
        state: 2
  select_moon_missile:
    profile: training_select
    restart_events: moon_missile_unselected, make_selection
    show_tokens: 
      lights: "tMoonAll"
      color: "ccbb00"
    control_events: 
      - events: moon_missile_selected{current_player.ts_hurry_up==0}
        state: 1
      - events: moon_missile_selected{current_player.ts_hurry_up==1}, selection_hurry_up{device.state_machines.training_select.state=="moon_missile"}
        state: 2
  select_ship_save:
    profile: training_select
    restart_events: ship_save_unselected, make_selection
    show_tokens: 
      lights: "tSaver"
      color: "0500ee"
    control_events: 
      - events: ship_save_selected{current_player.ts_hurry_up==0}
        state: 1
      - events: ship_save_selected{current_player.ts_hurry_up==1}, selection_hurry_up{device.state_machines.training_select.state=="ship_save"}
        state: 2
  select_shields:
    profile: training_select
    restart_events: shields_unselected, make_selection
    show_tokens: 
      lights: "tShields"
      color: "0010cc"
    control_events: 
      - events: shields_selected{current_player.ts_hurry_up==0}
        state: 1
      - events: shields_selected{current_player.ts_hurry_up==1}, selection_hurry_up{device.state_machines.training_select.state=="shields"}
        state: 2

show_player: 
  mode_training_select_started: 
    flash_color_with_fade: 
      key: key_ts_gi
      speed: 2
      show_tokens: 
        lights: "GI"
        fade: "900"
        color: "ffedd2"
  skip_selected: 
    flash_color: 
      key: key_skip_gi
      priority: 100
      speed: 11
      show_tokens: 
        lights: "gi22"
        color: "ffffff"
  skip_unselected: 
    flash_color: 
      action: stop
      key: key_skip_gi
      speed: 13
      show_tokens: 
        lights: "gi22"
        color: "ffffff"


slide_player: 
  mode_training_select_started.1: 
    training_select:
      action: play
      expire: 0s


sound_player: 
  mode_training_select_started: 
    voc_select_option: 
      key: key_voc_select_option
      action: play


state_machines: 
  training_select:
    starting_state: init
    states: 
      init: 
        label: Init State
        events_when_started: training_select_init
      heal: 
        label: Select Heal State
        events_when_started: heal_selected, show_training_completed_shots, check_ts_heal
      cluster_bomb: 
        label: Select Cluster Bomb State
        events_when_started: cluster_bomb_selected, show_training_completed_shots, check_ts_cluster_bomb
      proton_cannon: 
        label: Select Proton Cannon State
        events_when_started: proton_cannon_selected, show_training_completed_shots, check_ts_proton_cannon
      moon_missile: 
        label: Select Moon Missile State
        events_when_started: moon_missile_selected, show_training_completed_shots, check_ts_moon_missile
      ship_save: 
        label: Select Ship Save State
        events_when_started: ship_save_selected, show_training_completed_shots, check_ts_ship_save
      shields: 
        label: Select Shields State
        events_when_started: shields_selected, show_training_completed_shots, check_ts_shields
      skip: 
        label: Skip State
        events_when_started: skip_selected, show_training_completed_shots
    transitions: 
      - source: init
        target: heal
        events: 
          - training_select_init
      - source: heal
        target: cluster_bomb
        events: 
          - training_select_right
        events_when_transitioning: heal_unselected
      - source: cluster_bomb
        target: proton_cannon
        events: 
          - training_select_right
        events_when_transitioning: cluster_bomb_unselected
      - source: proton_cannon
        target: ship_save
        events: 
          - training_select_right
        events_when_transitioning: proton_cannon_unselected
      - source: ship_save
        target: shields
        events: 
          - training_select_right
        events_when_transitioning: ship_save_unselected
      - source: shields
        target: moon_missile
        events: 
          - training_select_right
        events_when_transitioning: shields_unselected
      - source: moon_missile
        target: skip
        events: 
          - training_select_right
        events_when_transitioning: moon_missile_unselected
      - source: skip
        target: heal
        events: 
          - training_select_right
        events_when_transitioning: skip_unselected
      - source: heal
        target: skip
        events: 
          - training_select_left
        events_when_transitioning: heal_unselected
      - source: cluster_bomb
        target: heal
        events: 
          - training_select_left
        events_when_transitioning: cluster_bomb_unselected
      - source: proton_cannon
        target: cluster_bomb
        events: 
          - training_select_left
        events_when_transitioning: proton_cannon_unselected
      - source: ship_save
        target: proton_cannon
        events: 
          - training_select_left
        events_when_transitioning: ship_save_unselected
      - source: shields
        target: ship_save
        events: 
          - training_select_left
        events_when_transitioning: shields_unselected
      - source: moon_missile
        target: shields
        events: 
          - training_select_left
        events_when_transitioning: moon_missile_unselected
      - source: skip
        target: moon_missile
        events: 
          - training_select_left
        events_when_transitioning: skip_unselected

timers: 
  training_select:
    start_value: 10
    end_value: 0
    direction: down
    control_events: 
      - event: mode_training_select_started
        action: restart
    restart_on_complete: False
    start_running: False
    tick_interval: 1000ms

variable_player: 
  timer_training_select_tick: 
    selection_countdown_value: 
      action: set
      int: {device.timers.training_select.ticks}

  mode_training_select_started: 
    selection_countdown_value: 
      action: set
      int: 10
    ts_hurry_up: 
      action: set
      int: 0
    ts_last_move: 
      action: set
      string: "right"

  selection_hurry_up: 
    ts_hurry_up: 
      action: set
      int: 1

  training_select_left: 
    ts_last_move: 
      action: set
      string: "left"

  training_select_right: 
    ts_last_move: 
      action: set
      string: "right"




