Option Explicit

Include("scripts\dest\vpx\tablescript.vbs")

GlfSwitchNameMap.Add "s_spinner", "s_Spinner"
GlfSwitchNameMap.Add "s_scoop", "s_Scoop"
GlfSwitchNameMap.Add "s_bumper1", "s_Bumper1"
GlfSwitchNameMap.Add "s_bumper2", "s_Bumper2"
GlfSwitchNameMap.Add "s_bumper3", "s_Bumper3"
GlfSwitchNameMap.Add "s_trough1", "s_Trough1"
GlfSwitchNameMap.Add "s_trough2", "s_Trough2"
GlfSwitchNameMap.Add "s_trough3", "s_Trough3"
GlfSwitchNameMap.Add "s_trough5", "s_Trough5"
GlfSwitchNameMap.Add "s_trough_jam", "s_TroughJam"
GlfSwitchNameMap.Add "s_left_flipper", "s_LeftFlipperButton"
GlfSwitchNameMap.Add "s_right_flipper", "s_RightFlipperButton"
GlfSwitchNameMap.Add "s_left_magna_key", "s_LeftMagnaButton"
GlfSwitchNameMap.Add "s_right_magna_key", "s_RightMagnaButton"
GlfSwitchNameMap.Add "_Started", "_started"
GlfSwitchNameMap.Add "s_right_staged_flipper_key", "s_RightFlipper1Button"


Function BuildAudioUidMap()
    Dim dict
    Set dict = CreateObject("Scripting.Dictionary")

    dict.Add "mus_ambient_bg", "uid://cq10388r1s2s8"
    dict.Add "mus_post_game", "uid://d1ex72geowij7"
    dict.Add "mus_post_game_heavier", "uid://dkyapdtaf88ab"
	dict.Add "mus_training_1", "uid://cvs6lib2f2x23"
    dict.Add "mus_training_2", "uid://beg55e5newf0q"
    dict.Add "mus_training_3", "uid://c31d1tirwe51k"
    dict.Add "mus_training_4", "uid://crn0poomcd6t5"
    dict.Add "mus_training_5", "uid://cs1wdhww3p7pb"
    dict.Add "mus_victory", "uid://bx4wrp3563um6"
    dict.Add "mus_wave0", "uid://g76kbus5vljm"
    dict.Add "mus_wave1", "uid://bc3txwg08gm6a"
    dict.Add "mus_wave2", "uid://ds0x23fkofxoy"
    dict.Add "mus_wave3", "uid://bko7y5b2g85nw"
    dict.Add "mus_wave4", "uid://dgvmsoqdbw5cl"
    dict.Add "mus_wave5", "uid://6rfjyy18u0cl"
    dict.Add "mus_wave6", "uid://bup7l8yewcxcm"
    dict.Add "mus_wave7", "uid://b6kqwl66q6mll"
    dict.Add "mus_wave8", "uid://c6d6m88im6h7p"
    dict.Add "mus_wave9", "uid://d82stlss4kpn"
    dict.Add "mus_wizard", "uid://dfm05sng4x03v"
    dict.Add "mus_wizard2", "uid://cb5cpa4uxvq7d"
    dict.Add "sfx_alien_ship_crash", "uid://b4nlkwqhwfwm3"
    dict.Add "sfx_ball_drain", "uid://cgdw7v4p7hid4"
    dict.Add "sfx_ball_launch", "uid://ctnjuamqxln3v"
    dict.Add "sfx_boom1", "uid://ndel4n14uwf8"
    dict.Add "sfx_boom2", "uid://cb84wukjbte3v"
    dict.Add "sfx_boom3", "uid://ccs247e0ilj4n"
    dict.Add "sfx_boom4", "uid://by8c7dh1u23gf"
    dict.Add "sfx_boom5", "uid://rom131mg65v6"
    dict.Add "sfx_boom6", "uid://gp8wdvnfbq8r"
    dict.Add "sfx_bumper1", "uid://bg71ach8fdosk"
    dict.Add "sfx_bumper2", "uid://76fvfmu40ot7"
    dict.Add "sfx_bumper3", "uid://bcr5qry6p1e4q"
    dict.Add "sfx_bumper4", "uid://cyalm3i2h4u1u"
    dict.Add "sfx_button", "uid://yejhgpb2sx1a"
    dict.Add "sfx_cluster_fired", "uid://2fvem4qhngw2"
    dict.Add "sfx_combo", "uid://dpaftbq5564wr"
    dict.Add "sfx_EarthHit1", "uid://uoiemw8hyijm"
    dict.Add "sfx_EarthHit2", "uid://nwwq86jkqqkh"
    dict.Add "sfx_EarthHit3", "uid://ca3vmk2qymsjy"
    dict.Add "sfx_entry", "uid://bm6hu3xwv0ice"
    dict.Add "sfx_error_buzz", "uid://cydnbh46l4b0g"
    dict.Add "sfx_final_explosion", "uid://chr1ctypdltip"
    dict.Add "sfx_final_wave_scoop", "uid://7dw8ikmacv0d"
    dict.Add "sfx_hs_initial", "uid://c1fa6lbvcyey0"
    dict.Add "sfx_jackpot", "uid://ca7nqyfs81and"
    dict.Add "sfx_launch", "uid://dx0v4wbbwe5qf"
    dict.Add "sfx_LCC1", "uid://dcctv3dyechee"
    dict.Add "sfx_LCC2", "uid://blmwispbmtp7k"
    dict.Add "sfx_LCC3", "uid://bjtth7lxnt4yv"
    dict.Add "sfx_LDS", "uid://bwtx3ahu6qm4l"
    dict.Add "sfx_left_ramp_time_warp", "uid://yfxi6o7k4tes"
    dict.Add "sfx_left_sling", "uid://d0qrljpjm7we"
    dict.Add "sfx_LF1", "uid://d4j63uly4b38l"
    dict.Add "sfx_LF2", "uid://d0nnwwj1rgwd6"
    dict.Add "sfx_LF3", "uid://cwktawjjm6jbv"
    dict.Add "sfx_LH", "uid://cn81mp3472o2i"
    dict.Add "sfx_LLI", "uid://b6ui8e63d21ia"
    dict.Add "sfx_LLO", "uid://h3ty0bkopgky"
    dict.Add "sfx_LM1", "uid://ccvvdky2l1ybx"
    dict.Add "sfx_LM2", "uid://fgxh7wnucyr1"
    dict.Add "sfx_LM3", "uid://blcwrkjfx73iy"
    dict.Add "sfx_LM4", "uid://dm7vamqcxioxw"
    dict.Add "sfx_LM5", "uid://blon3bs2p0bi0"
    dict.Add "sfx_LMet1", "uid://cnuw2khnu4ky5"
    dict.Add "sfx_LMet2", "uid://esmqc3u1xl3j"
    dict.Add "sfx_LMet3", "uid://d1ba8la1wv7g5"
    dict.Add "sfx_LMet4", "uid://dwbmtfhtlrjeb"
    dict.Add "sfx_LMet5", "uid://v07m07jyer5s"
    dict.Add "sfx_LMet6", "uid://bvtvn4hkubbrs"
    dict.Add "sfx_LMet7", "uid://b1fnpeto4pd71"
    dict.Add "sfx_LMet8", "uid://bxln4pqpp0m3c"
    dict.Add "sfx_LPC1", "uid://dxfp32fwhgkws"
    dict.Add "sfx_LPC2", "uid://bm66yfelq2slm"
    dict.Add "sfx_LPC3", "uid://dk7xgem8v8ul1"
    dict.Add "sfx_LPC4", "uid://b1m7r68gson0g"
    dict.Add "sfx_LPC5", "uid://ckfwh8y3407ay"
    dict.Add "sfx_LPF1", "uid://vga4e4vcq504"
    dict.Add "sfx_LPF2", "uid://bfm6jkujah8a0"
    dict.Add "sfx_LPF3", "uid://tfujvy8vjxy1"
    dict.Add "sfx_LPF4", "uid://baj7dt48wnuab"
    dict.Add "sfx_LPF5", "uid://3nnatditilrp"
    dict.Add "sfx_LRI", "uid://cdu4ngkx1iqoh"
    dict.Add "sfx_LRO", "uid://dwyii5tgtfvxy"
    dict.Add "sfx_LS1", "uid://sspeac0082s1"
    dict.Add "sfx_LS2", "uid://b1bxx3opvhlda"
    dict.Add "sfx_LS3", "uid://b5u4ovfnqvy7c"
    dict.Add "sfx_LS4", "uid://dflls5ufwt67m"
    dict.Add "sfx_LS5", "uid://c4futjj2141qb"
    dict.Add "sfx_LS6", "uid://c6q74vswx44fg"
    dict.Add "sfx_LS_between_waves_updated", "uid://0y3yohp4vxfu"
    dict.Add "sfx_LS_during_training", "uid://b0g7dyfnfyp1c"
    dict.Add "sfx_LSC1", "uid://ff1fkkhcpwn7"
    dict.Add "sfx_LSC2", "uid://cke0ilkoo2w3"
    dict.Add "sfx_LSC3", "uid://bel7pqow5a0e4"
    dict.Add "sfx_LSC4", "uid://cmwbcaw0bueh6"
    dict.Add "sfx_LSL", "uid://baenqevu430go"
    dict.Add "sfx_LSR", "uid://bmwqesgwiiucy"
    dict.Add "sfx_LSUp", "uid://dno3gilqjwjyo"
    dict.Add "sfx_LTW", "uid://cbmthkadyeg54"
    dict.Add "sfx_mag_cap", "uid://cm8u0g80sclu0"
    dict.Add "sfx_nuke", "uid://pi7hwl6dt74"
    dict.Add "sfx_Orb1", "uid://bmqqkptr7ajaa"
    dict.Add "sfx_Orb2", "uid://b12mw8mxml7dx"
    dict.Add "sfx_Orb3", "uid://c57lbeg3nb4so"
    dict.Add "sfx_powerdown", "uid://dhjg7rwhsgsas"
    dict.Add "sfx_right_ramp_moon_launch", "uid://c6fvm314mnaih"
    dict.Add "sfx_right_sling", "uid://bhgnabxp8d4ex"
    dict.Add "sfx_scoop", "uid://der2u7qdcdc24"
    dict.Add "sfx_Spinner", "uid://bmf0eeq5fpclf"
    dict.Add "sfx_super_jackpot", "uid://bxcgo6ep7bbm2"
    dict.Add "sfx_tally_alt", "uid://dec65c450lhyl"
    dict.Add "sfx_tilt", "uid://cc7i16ui0j7hj"
    dict.Add "sfx_tilt_warning", "uid://cm7okcuu87jtw"
    dict.Add "voc_AlienAlert", "uid://ch5hrie74o27l"
    dict.Add "voc_AlienHit", "uid://shbw3c1ykgrp"
    dict.Add "voc_attract1", "uid://vlrquxdxcdej"
    dict.Add "voc_attract2", "uid://c6cgl2uuowexo"
    dict.Add "voc_attract3", "uid://4531w3unlkld"
    dict.Add "voc_attract4", "uid://b16edvhevpi7b"
    dict.Add "voc_attract5", "uid://da7f62yd7ev46"
    dict.Add "voc_ball_locked", "uid://b0haw8ska0jgg"
    dict.Add "voc_critically_low_health", "uid://dxngs1quslhge"
    dict.Add "voc_double_bonus", "uid://beuojtp4q0y1o"
    dict.Add "voc_double_scoring", "uid://17wcr0xyopvv"
    dict.Add "voc_extra_ball_acheived", "uid://pge85amw7trq"
    dict.Add "voc_extra_ball_ready", "uid://b5a0jhjkfb1jx"
    dict.Add "voc_final_wave_ready", "uid://n33dt5u5oov2"
    dict.Add "voc_full_health", "uid://qvv2w1m66x0q"
    dict.Add "voc_full_protons", "uid://tjooa8p5o1qa"
    dict.Add "voc_imminent_shutdown", "uid://cn4ua3vcgvuag"
    dict.Add "voc_LCR1", "uid://c33txedcngjph"
    dict.Add "voc_LCR2", "uid://dtvfl36gvmxt1"
    dict.Add "voc_LCWiz", "uid://dlwhxr4rd4nmb"
    dict.Add "voc_LLWiz", "uid://dxnqqpxulxagq"
    dict.Add "voc_LMLR", "uid://3u1neq8xdek1"
    dict.Add "voc_LMR", "uid://btml4x152gqes"
    dict.Add "voc_LMR1", "uid://bo8v6dfp7l46h"
    dict.Add "voc_LMR2", "uid://036d81vk27nc"
    dict.Add "voc_LPR1", "uid://cg1kxw0mre88l"
    dict.Add "voc_nuke", "uid://c6uame2qmwcnn"
    dict.Add "voc_p1", "uid://0he2j5j7wof2"
    dict.Add "voc_p2", "uid://b7rkxgatfoxmu"
    dict.Add "voc_p3", "uid://d3o12wpcmeauc"
    dict.Add "voc_p4", "uid://blqnjbi6qx5u"
    dict.Add "voc_relaxed_combos", "uid://c7o4nffqrfjqe"
    dict.Add "voc_sdsss", "uid://bc4kng01dun02"
    dict.Add "voc_select_option", "uid://dbdra81elogft"
    dict.Add "voc_shields_acquired", "uid://uy4edgysgq06"
    dict.Add "voc_ShipSaver", "uid://cn5shkreepmyi"
    dict.Add "voc_ss", "uid://cwuoyn7yqdo8a"
    dict.Add "voc_sss", "uid://c0e63i4sybhf7"
    dict.Add "voc_ssss", "uid://dd84cti23b1kw"
    dict.Add "voc_super_pop_bumpers", "uid://npceabsgag6o"
    dict.Add "voc_super_spinner", "uid://cgapxqwpjadjf"
    dict.Add "voc_training", "uid://i4bt8y7sqd0r"
    dict.Add "voc_training_canceled", "uid://duji1rtikebko"
    dict.Add "voc_training_incomplete", "uid://g5qd3e7mr7em"
    dict.Add "voc_wave_completed", "uid://uckpu6xdah1x"
    dict.Add "voc_wave_incoming", "uid://cs0ixllo3sl8j"
    dict.Add "voc_winners_poem1", "uid://blbghdnocuieg"
    dict.Add "voc_winners_poem2", "uid://b5goyyypaffc"
    dict.Add "voc_winners_poem3", "uid://bjht5j0sh6qjc"
    dict.Add "voc_winners_poem4", "uid://bextapv1s1qvq"
    dict.Add "voc_winners_poem5", "uid://2v411h8jfnej"
    dict.Add "voc_winners_poem6", "uid://fgtfpwbagevy"
    dict.Add "voc_wiz", "uid://cjq5pqm2rnqdk"
    dict.Add "voc_wizard_game", "uid://cmny0mdne6po"

    Set BuildAudioUidMap = dict
End Function

Dim soundUidMap
Set soundUidMap = BuildAudioUidMap()



Dim objFSO,objTextFile
Sub Include (strFile)
	'Create objects for opening text file
	Set objFSO = CreateObject("Scripting.FileSystemObject")
	Set objTextFile = objFSO.OpenTextFile(strFile, 1)

	'Execute content of file.
	ExecuteGlobal objTextFile.ReadAll
 
	'CLose file
	objTextFile.Close
 
	'Clean up
	Set objFSO = Nothing
	Set objTextFile = Nothing
End Sub

