'*****************************************************************************************************************************************
'  ZVLM : VLM  Arrays
'*****************************************************************************************************************************************


' VLM  Arrays - Start
' Arrays per baked part
Dim BP_Asteroid1: BP_Asteroid1=Array(BM_Asteroid1, LM_F_FL1_Asteroid1, LM_F_FL2_Asteroid1, LM_F_FL3_Asteroid1, LM_F_FL4_Asteroid1, LM_F_FL7_Asteroid1, LM_L_LB2_Asteroid1, LM_L_LB3_Asteroid1, LM_L_LB4_Asteroid1, LM_L_LM3_Asteroid1, LM_L_LPC1_Asteroid1, LM_L_LPC4_Asteroid1, LM_L_LPC5_Asteroid1, LM_L_LPF_Asteroid1, LM_L_LSwC1_Asteroid1, LM_L_LSwC2_Asteroid1, LM_L_LSwC3_Asteroid1, LM_L_Lspot1_Asteroid1, LM_GI_gi16_Asteroid1, LM_GI_gi20_Asteroid1, LM_GI_gi21_Asteroid1)
Dim BP_Asteroid2: BP_Asteroid2=Array(LM_F_FL1_Asteroid2, LM_F_FL2_Asteroid2, LM_F_FL3_Asteroid2, LM_F_FL4_Asteroid2, LM_F_FL7_Asteroid2, LM_L_LB2_Asteroid2, LM_L_LB3_Asteroid2, LM_L_LB4_Asteroid2, LM_L_LM3_Asteroid2, LM_L_LPC4_Asteroid2, LM_L_LPC5_Asteroid2, LM_L_LPF_Asteroid2, LM_L_LSwC1_Asteroid2, LM_L_LSwC2_Asteroid2, LM_L_LSwC3_Asteroid2, LM_L_Lspot1_Asteroid2, LM_GI_gi16_Asteroid2, LM_GI_gi20_Asteroid2, LM_GI_gi21_Asteroid2)
Dim BP_Asteroid3: BP_Asteroid3=Array(LM_F_FL1_Asteroid3, LM_F_FL2_Asteroid3, LM_F_FL3_Asteroid3, LM_F_FL4_Asteroid3, LM_F_FL7_Asteroid3, LM_L_LB2_Asteroid3, LM_L_LB3_Asteroid3, LM_L_LB4_Asteroid3, LM_L_LM3_Asteroid3, LM_L_LPC4_Asteroid3, LM_L_LPC5_Asteroid3, LM_L_LPF_Asteroid3, LM_L_LSwC1_Asteroid3, LM_L_LSwC2_Asteroid3, LM_L_LSwC3_Asteroid3, LM_L_Lspot1_Asteroid3, LM_GI_gi16_Asteroid3, LM_GI_gi20_Asteroid3, LM_GI_gi21_Asteroid3)
Dim BP_Asteroid4: BP_Asteroid4=Array(LM_F_FL1_Asteroid4, LM_F_FL2_Asteroid4, LM_F_FL3_Asteroid4, LM_F_FL4_Asteroid4, LM_F_FL7_Asteroid4, LM_L_LB2_Asteroid4, LM_L_LB3_Asteroid4, LM_L_LB4_Asteroid4, LM_L_LM3_Asteroid4, LM_L_LPC1_Asteroid4, LM_L_LPC4_Asteroid4, LM_L_LPC5_Asteroid4, LM_L_LPF_Asteroid4, LM_L_LSwC1_Asteroid4, LM_L_LSwC2_Asteroid4, LM_L_LSwC3_Asteroid4, LM_L_Lspot1_Asteroid4, LM_GI_gi16_Asteroid4, LM_GI_gi20_Asteroid4, LM_GI_gi21_Asteroid4)
Dim BP_BR1: BP_BR1=Array(BM_BR1, LM_F_FL5_BR1, LM_F_FL6_BR1, LM_L_LB1_BR1, LM_L_LMet1_BR1, LM_L_LSwL1_BR1)
Dim BP_BR2: BP_BR2=Array(BM_BR2, LM_F_FL1_BR2, LM_F_FL2_BR2, LM_F_FL3_BR2, LM_F_FL7_BR2, LM_L_LB2_BR2, LM_L_LB3_BR2, LM_L_LB4_BR2, LM_GI_gi16_BR2, LM_GI_gi17_BR2)
Dim BP_BR3: BP_BR3=Array(BM_BR3, LM_F_FL1_BR3, LM_F_FL2_BR3, LM_F_FL3_BR3, LM_F_FL7_BR3, LM_L_LB2_BR3, LM_L_LB3_BR3, LM_L_LB4_BR3, LM_GI_gi16_BR3)
Dim BP_BR4: BP_BR4=Array(BM_BR4, LM_F_FL1_BR4, LM_F_FL2_BR4, LM_F_FL3_BR4, LM_F_FL5_BR4, LM_F_FL7_BR4, LM_L_LB2_BR4, LM_L_LB3_BR4, LM_L_LB4_BR4, LM_L_Lspot1_BR4, LM_GI_gi13_BR4, LM_GI_gi16_BR4)
Dim BP_BS1: BP_BS1=Array(BM_BS1, LM_F_FL6_BS1, LM_L_LB1_BS1, LM_L_LMet1_BS1, LM_L_LSwL1_BS1, LM_L_LSwL2_BS1)
Dim BP_BS2: BP_BS2=Array(BM_BS2, LM_F_FL1_BS2, LM_F_FL2_BS2, LM_F_FL3_BS2, LM_F_FL7_BS2, LM_L_LB2_BS2, LM_L_LB3_BS2, LM_L_LB4_BS2, LM_GI_gi13_BS2, LM_GI_gi16_BS2)
Dim BP_BS3: BP_BS3=Array(BM_BS3, LM_F_FL1_BS3, LM_F_FL2_BS3, LM_F_FL3_BS3, LM_F_FL7_BS3, LM_L_LB2_BS3, LM_L_LB3_BS3, LM_L_LB4_BS3, LM_GI_gi16_BS3)
Dim BP_BS4: BP_BS4=Array(BM_BS4, LM_F_FL1_BS4, LM_F_FL2_BS4, LM_F_FL3_BS4, LM_F_FL7_BS4, LM_L_LB2_BS4, LM_L_LB3_BS4, LM_L_LB4_BS4, LM_L_Lspot1_BS4, LM_GI_gi13_BS4, LM_GI_gi16_BS4)
Dim BP_BmpBot: BP_BmpBot=Array(BM_BmpBot, LM_F_FL1_BmpBot, LM_F_FL2_BmpBot, LM_F_FL3_BmpBot, LM_F_FL7_BmpBot, LM_L_LB1_BmpBot, LM_L_LB2_BmpBot, LM_L_LB3_BmpBot, LM_L_LB4_BmpBot, LM_L_LSwL2_BmpBot, LM_GI_gi13_BmpBot, LM_GI_gi16_BmpBot)
Dim BP_BmpTopB: BP_BmpTopB=Array(BM_BmpTopB, LM_F_FL1_BmpTopB, LM_F_FL2_BmpTopB, LM_F_FL3_BmpTopB, LM_F_FL4_BmpTopB, LM_F_FL7_BmpTopB, LM_L_LB2_BmpTopB, LM_L_LB3_BmpTopB, LM_L_LB4_BmpTopB, LM_L_LSwC2_BmpTopB, LM_L_Lspot1_BmpTopB, LM_GI_gi13_BmpTopB, LM_GI_gi16_BmpTopB)
Dim BP_BmpTopR: BP_BmpTopR=Array(BM_BmpTopR, LM_L_LB1_BmpTopR, LM_L_LMet1_BmpTopR, LM_L_LMet2_BmpTopR, LM_L_LS1_BmpTopR, LM_L_LS2_BmpTopR, LM_L_LSwL1_BmpTopR, LM_L_LSwL2_BmpTopR, LM_L_LW6_BmpTopR, LM_L_LW7_BmpTopR, LM_L_LW8_BmpTopR, LM_GI_gi04_BmpTopR)
Dim BP_DiverterPin: BP_DiverterPin=Array(BM_DiverterPin, LM_F_FL1_DiverterPin, LM_F_FL2_DiverterPin, LM_F_FL3_DiverterPin, LM_F_FL7_DiverterPin, LM_L_LB2_DiverterPin, LM_L_LB3_DiverterPin)
Dim BP_Gate2: BP_Gate2=Array(BM_Gate2, LM_F_FL1_Gate2, LM_GI_gi10_Gate2, LM_GI_gi14_Gate2)
Dim BP_GateL: BP_GateL=Array(BM_GateL, LM_F_FL2_GateL, LM_F_FL3_GateL, LM_F_FL7_GateL, LM_L_LPC1_GateL, LM_L_Lspot2_GateL, LM_GI_gi20_GateL, LM_GI_gi21_GateL)
Dim BP_GateR: BP_GateR=Array(BM_GateR, LM_F_FL1_GateR, LM_F_FL2_GateR, LM_F_FL3_GateR, LM_F_FL4_GateR, LM_F_FL7_GateR, LM_L_LB4_GateR, LM_L_LMR_GateR, LM_GI_gi13_GateR, LM_GI_gi16_GateR)
Dim BP_LArm: BP_LArm=Array(BM_LArm, LM_F_FL1_LArm, LM_F_FL5_LArm, LM_F_FL6_LArm, LM_L_Lspot2_LArm, LM_GI_gi01_LArm, LM_GI_gi02_LArm, LM_GI_gi03_LArm, LM_GI_gi04_LArm)
Dim BP_LFlip: BP_LFlip=Array(BM_LFlip, LM_F_FL5_LFlip, LM_F_FL6_LFlip, LM_L_LC1_LFlip, LM_L_LC2_LFlip, LM_L_LH1_LFlip, LM_L_LH2_LFlip, LM_L_LH3_LFlip, LM_L_LH4_LFlip, LM_L_LPR4_LFlip, LM_L_LSA_LFlip, LM_L_Lspot2_LFlip, LM_D_a15_LFlip, LM_GI_gi01_LFlip, LM_GI_gi02_LFlip, LM_GI_gi03_LFlip, LM_GI_gi04_LFlip, LM_GI_gi07_LFlip, LM_GI_giapron_LFlip)
Dim BP_LFlipU: BP_LFlipU=Array(BM_LFlipU, LM_F_FL5_LFlipU, LM_F_FL6_LFlipU, LM_L_LC1_LFlipU, LM_L_LC2_LFlipU, LM_L_LC3_LFlipU, LM_L_LC4_LFlipU, LM_L_LH1_LFlipU, LM_L_LH2_LFlipU, LM_L_LH3_LFlipU, LM_L_LH4_LFlipU, LM_L_LH5_LFlipU, LM_L_LPR4_LFlipU, LM_L_LPR5_LFlipU, LM_L_LSA_LFlipU, LM_L_Lspot2_LFlipU, LM_D_a15_LFlipU, LM_GI_gi01_LFlipU, LM_GI_gi02_LFlipU, LM_GI_gi03_LFlipU, LM_GI_gi04_LFlipU, LM_GI_gi07_LFlipU, LM_GI_giapron_LFlipU)
Dim BP_LockPin: BP_LockPin=Array(BM_LockPin, LM_F_FL1_LockPin, LM_F_FL2_LockPin, LM_F_FL3_LockPin, LM_F_FL7_LockPin, LM_L_LB1_LockPin, LM_L_Lspot2_LockPin, LM_GI_gi14_LockPin, LM_GI_gi15_LockPin, LM_GI_gi19_LockPin)
Dim BP_Lsling1: BP_Lsling1=Array(BM_Lsling1, LM_F_FL1_Lsling1, LM_F_FL5_Lsling1, LM_F_FL6_Lsling1, LM_L_LCR1_Lsling1, LM_L_LCR2_Lsling1, LM_L_Lspot2_Lsling1, LM_GI_gi01_Lsling1, LM_GI_gi03_Lsling1, LM_GI_gi04_Lsling1, LM_GI_giapron_Lsling1)
Dim BP_Lsling2: BP_Lsling2=Array(BM_Lsling2, LM_F_FL5_Lsling2, LM_F_FL6_Lsling2, LM_L_LCR1_Lsling2, LM_L_LCR2_Lsling2, LM_L_Lspot2_Lsling2, LM_GI_gi01_Lsling2, LM_GI_gi03_Lsling2, LM_GI_gi04_Lsling2, LM_GI_gi07_Lsling2, LM_GI_giapron_Lsling2)
Dim BP_Parts: BP_Parts=Array(BM_Parts, LM_L_LShip_Parts, LM_F_FL1_Parts, LM_F_FL2_Parts, LM_F_FL3_Parts, LM_F_FL4_Parts, LM_F_FL5_Parts, LM_F_FL6_Parts, LM_F_FL7_Parts, LM_L_LB1_Parts, LM_L_LB2_Parts, LM_L_LB3_Parts, LM_L_LB4_Parts, LM_L_LC1_Parts, LM_L_LC2_Parts, LM_L_LC8_Parts, LM_L_LCC1_Parts, LM_L_LCC2_Parts, LM_L_LCC3_Parts, LM_L_LCR1_Parts, LM_L_LCR2_Parts, LM_L_LCWiz_Parts, LM_L_LEBR_Parts, LM_L_LF1_Parts, LM_L_LF2_Parts, LM_L_LF3_Parts, LM_L_LH1_Parts, LM_L_LH9_Parts, LM_L_LLI_Parts, LM_L_LLO_Parts, LM_L_LLWiz_Parts, LM_L_LM1_Parts, LM_L_LM2_Parts, LM_L_LM4_Parts, LM_L_LM5_Parts, LM_L_LMLR_Parts, LM_L_LMR1_Parts, LM_L_LMR2_Parts, LM_L_LMR_Parts, LM_L_LMet1_Parts, LM_L_LMet2_Parts, LM_L_LMet3_Parts, LM_L_LMet4_Parts, LM_L_LPC1_Parts, LM_L_LPC2_Parts, LM_L_LPC3_Parts, LM_L_LPC4_Parts, LM_L_LPC5_Parts, LM_L_LPR1_Parts, LM_L_LPR2_Parts, LM_L_LPR3_Parts, LM_L_LPR4_Parts, LM_L_LPR5_Parts, LM_L_LPR6_Parts, LM_L_LRI_Parts, LM_L_LRO_Parts, LM_L_LS1_Parts, LM_L_LS2_Parts, LM_L_LS3_Parts, LM_L_LS4_Parts, _
	LM_L_LS5_Parts, LM_L_LS6_Parts, LM_L_LSC1_Parts, LM_L_LSC2_Parts, LM_L_LSC3_Parts, LM_L_LSC4_Parts, LM_L_LSL_Parts, LM_L_LSR_Parts, LM_Stars_Parts, LM_L_LSwC1_Parts, LM_L_LSwC2_Parts, LM_L_LSwC3_Parts, LM_L_LSwL1_Parts, LM_L_LSwL2_Parts, LM_L_LTW1_Parts, LM_L_LTW2_Parts, LM_L_LTW3_Parts, LM_L_LTW4_Parts, LM_L_LW1_Parts, LM_L_LW2_Parts, LM_L_LW3_Parts, LM_L_LW4_Parts, LM_L_LW5_Parts, LM_L_LW6_Parts, LM_L_LW7_Parts, LM_L_LW8_Parts, LM_L_LW9_Parts, LM_L_LWiz_Parts, LM_L_LX_Parts, LM_L_Lspot1_Parts, LM_L_Lspot2_Parts, LM_D_a00_Parts, LM_D_a01_Parts, LM_D_a02_Parts, LM_D_a03_Parts, LM_D_a04_Parts, LM_D_a05_Parts, LM_D_a06_Parts, LM_D_a10_Parts, LM_D_a11_Parts, LM_D_a12_Parts, LM_D_a13_Parts, LM_D_a14_Parts, LM_D_a15_Parts, LM_D_a16_Parts, LM_GI_gi01_Parts, LM_GI_gi02_Parts, LM_GI_gi03_Parts, LM_GI_gi04_Parts, LM_GI_gi05_Parts, LM_GI_gi06_Parts, LM_GI_gi07_Parts, LM_GI_gi08_Parts, LM_GI_gi09_Parts, LM_GI_gi10_Parts, LM_GI_gi11_Parts, LM_GI_gi12_Parts, LM_GI_gi13_Parts, LM_GI_gi14_Parts, LM_GI_gi15_Parts, _
	LM_GI_gi16_Parts, LM_GI_gi17_Parts, LM_GI_gi18_Parts, LM_GI_gi19_Parts, LM_GI_gi20_Parts, LM_GI_gi21_Parts, LM_GI_giapron_Parts)
Dim BP_Playfield: BP_Playfield=Array(BM_Playfield, LM_F_FL1_Playfield, LM_F_FL2_Playfield, LM_F_FL3_Playfield, LM_F_FL4_Playfield, LM_F_FL5_Playfield, LM_F_FL6_Playfield, LM_F_FL7_Playfield, LM_L_LB1_Playfield, LM_L_LB2_Playfield, LM_L_LB3_Playfield, LM_L_LB4_Playfield, LM_L_LC1_Playfield, LM_L_LC2_Playfield, LM_L_LC3_Playfield, LM_L_LC4_Playfield, LM_L_LC5_Playfield, LM_L_LC6_Playfield, LM_L_LC7_Playfield, LM_L_LC8_Playfield, LM_L_LCC1_Playfield, LM_L_LCC2_Playfield, LM_L_LCC3_Playfield, LM_L_LCR1_Playfield, LM_L_LCR2_Playfield, LM_L_LCWiz_Playfield, LM_L_LEBR_Playfield, LM_L_LF1_Playfield, LM_L_LF2_Playfield, LM_L_LF3_Playfield, LM_L_LH1_Playfield, LM_L_LH2_Playfield, LM_L_LH3_Playfield, LM_L_LH4_Playfield, LM_L_LH5_Playfield, LM_L_LH6_Playfield, LM_L_LH7_Playfield, LM_L_LH8_Playfield, LM_L_LH9_Playfield, LM_L_LLI_Playfield, LM_L_LLO_Playfield, LM_L_LLWiz_Playfield, LM_L_LM1_Playfield, LM_L_LM2_Playfield, LM_L_LM3_Playfield, LM_L_LM4_Playfield, LM_L_LM5_Playfield, LM_L_LMLR_Playfield, LM_L_LMR1_Playfield, _
	LM_L_LMR2_Playfield, LM_L_LMR_Playfield, LM_L_LMet1_Playfield, LM_L_LMet2_Playfield, LM_L_LMet3_Playfield, LM_L_LMet4_Playfield, LM_L_LPC1_Playfield, LM_L_LPC2_Playfield, LM_L_LPC3_Playfield, LM_L_LPC4_Playfield, LM_L_LPC5_Playfield, LM_L_LPF_Playfield, LM_L_LPR1_Playfield, LM_L_LPR2_Playfield, LM_L_LPR3_Playfield, LM_L_LPR4_Playfield, LM_L_LPR5_Playfield, LM_L_LPR6_Playfield, LM_L_LRI_Playfield, LM_L_LRO_Playfield, LM_L_LS1_Playfield, LM_L_LS2_Playfield, LM_L_LS3_Playfield, LM_L_LS4_Playfield, LM_L_LS5_Playfield, LM_L_LS6_Playfield, LM_L_LSA_Playfield, LM_L_LSC1_Playfield, LM_L_LSC2_Playfield, LM_L_LSC3_Playfield, LM_L_LSC4_Playfield, LM_L_LSL_Playfield, LM_L_LSR_Playfield, LM_L_LSwC1_Playfield, LM_L_LSwC2_Playfield, LM_L_LSwC3_Playfield, LM_L_LSwL1_Playfield, LM_L_LSwL2_Playfield, LM_L_LTW1_Playfield, LM_L_LTW2_Playfield, LM_L_LTW3_Playfield, LM_L_LTW4_Playfield, LM_L_LW1_Playfield, LM_L_LW2_Playfield, LM_L_LW3_Playfield, LM_L_LW4_Playfield, LM_L_LW5_Playfield, LM_L_LW6_Playfield, LM_L_LW7_Playfield, _
	LM_L_LW8_Playfield, LM_L_LW9_Playfield, LM_L_LWiz_Playfield, LM_L_LX_Playfield, LM_L_Lspot1_Playfield, LM_L_Lspot2_Playfield, LM_D_a00_Playfield, LM_D_a01_Playfield, LM_D_a02_Playfield, LM_D_a03_Playfield, LM_D_a04_Playfield, LM_D_a05_Playfield, LM_D_a06_Playfield, LM_D_a10_Playfield, LM_D_a11_Playfield, LM_D_a12_Playfield, LM_D_a13_Playfield, LM_D_a14_Playfield, LM_D_a15_Playfield, LM_D_a16_Playfield, LM_GI_gi01_Playfield, LM_GI_gi02_Playfield, LM_GI_gi03_Playfield, LM_GI_gi04_Playfield, LM_GI_gi05_Playfield, LM_GI_gi06_Playfield, LM_GI_gi07_Playfield, LM_GI_gi08_Playfield, LM_GI_gi09_Playfield, LM_GI_gi10_Playfield, LM_GI_gi11_Playfield, LM_GI_gi12_Playfield, LM_GI_gi13_Playfield, LM_GI_gi14_Playfield, LM_GI_gi15_Playfield, LM_GI_gi16_Playfield, LM_GI_gi17_Playfield, LM_GI_gi18_Playfield, LM_GI_gi19_Playfield, LM_GI_gi20_Playfield, LM_GI_gi21_Playfield, LM_GI_giapron_Playfield)
Dim BP_RArm: BP_RArm=Array(BM_RArm, LM_F_FL5_RArm, LM_F_FL6_RArm, LM_L_Lspot2_RArm, LM_GI_gi05_RArm, LM_GI_gi06_RArm, LM_GI_gi07_RArm, LM_GI_gi08_RArm)
Dim BP_RFlip: BP_RFlip=Array(BM_RFlip, LM_F_FL5_RFlip, LM_F_FL6_RFlip, LM_L_LC8_RFlip, LM_L_LH7_RFlip, LM_L_LH8_RFlip, LM_L_LH9_RFlip, LM_L_LSA_RFlip, LM_L_Lspot2_RFlip, LM_GI_gi01_RFlip, LM_GI_gi02_RFlip, LM_GI_gi03_RFlip, LM_GI_gi05_RFlip, LM_GI_gi06_RFlip, LM_GI_gi07_RFlip, LM_GI_gi08_RFlip, LM_GI_giapron_RFlip)
Dim BP_RFlip1: BP_RFlip1=Array(BM_RFlip1, LM_F_FL1_RFlip1, LM_F_FL4_RFlip1, LM_L_LB1_RFlip1, LM_L_LS6_RFlip1, LM_GI_gi14_RFlip1, LM_GI_gi15_RFlip1, LM_GI_gi19_RFlip1)
Dim BP_RFlip1U: BP_RFlip1U=Array(BM_RFlip1U, LM_F_FL1_RFlip1U, LM_F_FL4_RFlip1U, LM_L_LB1_RFlip1U, LM_L_LF3_RFlip1U, LM_L_LS5_RFlip1U, LM_L_LS6_RFlip1U, LM_GI_gi10_RFlip1U, LM_GI_gi13_RFlip1U, LM_GI_gi14_RFlip1U, LM_GI_gi15_RFlip1U, LM_GI_gi19_RFlip1U)
Dim BP_RFlipU: BP_RFlipU=Array(BM_RFlipU, LM_F_FL5_RFlipU, LM_F_FL6_RFlipU, LM_L_LC5_RFlipU, LM_L_LC6_RFlipU, LM_L_LC7_RFlipU, LM_L_LC8_RFlipU, LM_L_LH5_RFlipU, LM_L_LH6_RFlipU, LM_L_LH7_RFlipU, LM_L_LH8_RFlipU, LM_L_LH9_RFlipU, LM_L_LPR5_RFlipU, LM_L_LPR6_RFlipU, LM_L_LSA_RFlipU, LM_L_Lspot2_RFlipU, LM_D_a00_RFlipU, LM_D_a01_RFlipU, LM_D_a06_RFlipU, LM_GI_gi01_RFlipU, LM_GI_gi02_RFlipU, LM_GI_gi03_RFlipU, LM_GI_gi05_RFlipU, LM_GI_gi06_RFlipU, LM_GI_gi07_RFlipU, LM_GI_gi08_RFlipU, LM_GI_giapron_RFlipU)
Dim BP_Rails: BP_Rails=Array(BM_Rails, LM_F_FL1_Rails)
Dim BP_Ramp: BP_Ramp=Array(BM_Ramp, LM_F_FL1_Ramp, LM_F_FL2_Ramp, LM_F_FL3_Ramp, LM_F_FL4_Ramp, LM_F_FL6_Ramp, LM_F_FL7_Ramp, LM_L_LB1_Ramp, LM_L_LCC1_Ramp, LM_L_LPC1_Ramp, LM_L_LPC4_Ramp, LM_Stars_Ramp, LM_L_LTW1_Ramp, LM_L_LTW2_Ramp, LM_L_Lspot1_Ramp, LM_L_Lspot2_Ramp, LM_GI_gi16_Ramp, LM_GI_gi20_Ramp, LM_GI_gi21_Ramp)
Dim BP_Rsling1: BP_Rsling1=Array(BM_Rsling1, LM_F_FL5_Rsling1, LM_F_FL6_Rsling1, LM_L_LB1_Rsling1, LM_L_LMR1_Rsling1, LM_L_LMR2_Rsling1, LM_L_Lspot2_Rsling1, LM_GI_gi05_Rsling1, LM_GI_gi06_Rsling1, LM_GI_gi07_Rsling1, LM_GI_gi08_Rsling1, LM_GI_giapron_Rsling1)
Dim BP_Rsling2: BP_Rsling2=Array(BM_Rsling2, LM_F_FL1_Rsling2, LM_F_FL5_Rsling2, LM_F_FL6_Rsling2, LM_L_LB1_Rsling2, LM_L_LMR1_Rsling2, LM_L_LMR2_Rsling2, LM_L_Lspot2_Rsling2, LM_GI_gi05_Rsling2, LM_GI_gi07_Rsling2, LM_GI_gi08_Rsling2, LM_GI_giapron_Rsling2)
Dim BP_Ship: BP_Ship=Array(BM_Ship, LM_L_LShip_Ship, LM_F_FL1_Ship, LM_F_FL2_Ship, LM_F_FL3_Ship, LM_F_FL7_Ship, LM_L_LB1_Ship, LM_L_LS3_Ship)
Dim BP_Spin: BP_Spin=Array(BM_Spin, LM_F_FL1_Spin, LM_F_FL2_Spin, LM_F_FL3_Spin, LM_F_FL4_Spin, LM_F_FL7_Spin, LM_L_LB3_Spin, LM_L_Lspot1_Spin, LM_GI_gi20_Spin, LM_GI_gi21_Spin)
Dim BP_SpinU: BP_SpinU=Array(BM_SpinU, LM_F_FL1_SpinU, LM_F_FL2_SpinU, LM_F_FL3_SpinU, LM_F_FL4_SpinU, LM_F_FL7_SpinU, LM_L_LPC1_SpinU, LM_L_Lspot1_SpinU, LM_GI_gi20_SpinU, LM_GI_gi21_SpinU)
Dim BP_SpinWire: BP_SpinWire=Array(BM_SpinWire, LM_F_FL2_SpinWire, LM_F_FL3_SpinWire, LM_F_FL7_SpinWire, LM_L_Lspot1_SpinWire, LM_GI_gi20_SpinWire, LM_GI_gi21_SpinWire)
Dim BP_TM1: BP_TM1=Array(BM_TM1, LM_F_FL5_TM1, LM_L_LB1_TM1, LM_L_LM1_TM1, LM_L_LS1_TM1, LM_L_LSwL1_TM1)
Dim BP_TM2: BP_TM2=Array(BM_TM2, LM_F_FL1_TM2, LM_F_FL2_TM2, LM_F_FL4_TM2, LM_F_FL7_TM2, LM_L_LB1_TM2, LM_L_LM2_TM2, LM_L_LPC1_TM2, LM_L_LPC2_TM2, LM_GI_gi20_TM2, LM_GI_gi21_TM2)
Dim BP_TM3: BP_TM3=Array(BM_TM3, LM_F_FL1_TM3, LM_F_FL2_TM3, LM_F_FL3_TM3, LM_F_FL4_TM3, LM_F_FL7_TM3, LM_L_LB3_TM3, LM_L_LM3_TM3, LM_L_LPC4_TM3, LM_L_LPC5_TM3, LM_L_LPF_TM3, LM_L_LSwC2_TM3, LM_L_Lspot1_TM3)
Dim BP_TM4: BP_TM4=Array(BM_TM4, LM_F_FL1_TM4, LM_F_FL2_TM4, LM_F_FL3_TM4, LM_F_FL4_TM4, LM_F_FL7_TM4, LM_L_LB3_TM4, LM_L_LB4_TM4, LM_L_LEBR_TM4, LM_L_LM4_TM4, LM_L_LMR_TM4, LM_L_LPC5_TM4, LM_L_Lspot1_TM4, LM_GI_gi13_TM4, LM_GI_gi16_TM4)
Dim BP_TM5: BP_TM5=Array(BM_TM5, LM_F_FL1_TM5, LM_F_FL7_TM5, LM_L_LF2_TM5, LM_L_LF3_TM5, LM_L_LM5_TM5, LM_L_LMLR_TM5, LM_GI_gi13_TM5, LM_GI_gi14_TM5, LM_GI_gi19_TM5)
Dim BP_TMet1: BP_TMet1=Array(BM_TMet1, LM_L_LB1_TMet1, LM_L_LMet1_TMet1)
Dim BP_TMet2: BP_TMet2=Array(BM_TMet2, LM_L_LMet2_TMet2, LM_L_LS3_TMet2)
Dim BP_TMet3: BP_TMet3=Array(BM_TMet3, LM_L_LMet3_TMet3)
Dim BP_TMet4: BP_TMet4=Array(BM_TMet4, LM_L_LMet4_TMet4)
Dim BP_TS1: BP_TS1=Array(BM_TS1, LM_L_LSC1_TS1, LM_L_LSC2_TS1, LM_GI_gi10_TS1)
Dim BP_TS2: BP_TS2=Array(BM_TS2, LM_F_FL6_TS2, LM_L_LB1_TS2, LM_L_LSC1_TS2, LM_L_LSC2_TS2, LM_L_LSC3_TS2, LM_GI_gi10_TS2)
Dim BP_TS3: BP_TS3=Array(BM_TS3, LM_F_FL6_TS3, LM_L_LSC2_TS3, LM_L_LSC3_TS3, LM_GI_gi10_TS3)
Dim BP_TS4: BP_TS4=Array(BM_TS4, LM_F_FL6_TS4, LM_L_LSC3_TS4, LM_L_LSC4_TS4, LM_GI_gi10_TS4)
Dim BP_TrustPost: BP_TrustPost=Array(BM_TrustPost, LM_F_FL5_TrustPost, LM_F_FL6_TrustPost, LM_L_LSA_TrustPost, LM_GI_giapron_TrustPost)
Dim BP_UnderPF: BP_UnderPF=Array(BM_UnderPF, LM_F_FL1_UnderPF, LM_F_FL2_UnderPF, LM_F_FL3_UnderPF, LM_F_FL4_UnderPF, LM_F_FL5_UnderPF, LM_F_FL6_UnderPF, LM_F_FL7_UnderPF, LM_L_LB1_UnderPF, LM_L_LB3_UnderPF, LM_L_LB4_UnderPF, LM_L_LC1_UnderPF, LM_L_LC2_UnderPF, LM_L_LC3_UnderPF, LM_L_LC4_UnderPF, LM_L_LC5_UnderPF, LM_L_LC6_UnderPF, LM_L_LC7_UnderPF, LM_L_LC8_UnderPF, LM_L_LCC1_UnderPF, LM_L_LCC2_UnderPF, LM_L_LCC3_UnderPF, LM_L_LCR1_UnderPF, LM_L_LCR2_UnderPF, LM_L_LCWiz_UnderPF, LM_L_LEBR_UnderPF, LM_L_LF1_UnderPF, LM_L_LF2_UnderPF, LM_L_LF3_UnderPF, LM_L_LH1_UnderPF, LM_L_LH2_UnderPF, LM_L_LH3_UnderPF, LM_L_LH4_UnderPF, LM_L_LH5_UnderPF, LM_L_LH6_UnderPF, LM_L_LH7_UnderPF, LM_L_LH8_UnderPF, LM_L_LH9_UnderPF, LM_L_LLI_UnderPF, LM_L_LLO_UnderPF, LM_L_LLWiz_UnderPF, LM_L_LM1_UnderPF, LM_L_LM2_UnderPF, LM_L_LM3_UnderPF, LM_L_LM4_UnderPF, LM_L_LM5_UnderPF, LM_L_LMLR_UnderPF, LM_L_LMR1_UnderPF, LM_L_LMR2_UnderPF, LM_L_LMR_UnderPF, LM_L_LMet1_UnderPF, LM_L_LMet2_UnderPF, LM_L_LMet3_UnderPF, LM_L_LMet4_UnderPF, _
	LM_L_LPC1_UnderPF, LM_L_LPC2_UnderPF, LM_L_LPC3_UnderPF, LM_L_LPC4_UnderPF, LM_L_LPC5_UnderPF, LM_L_LPF_UnderPF, LM_L_LPR1_UnderPF, LM_L_LPR2_UnderPF, LM_L_LPR3_UnderPF, LM_L_LPR4_UnderPF, LM_L_LPR5_UnderPF, LM_L_LPR6_UnderPF, LM_L_LRI_UnderPF, LM_L_LRO_UnderPF, LM_L_LS1_UnderPF, LM_L_LS2_UnderPF, LM_L_LS3_UnderPF, LM_L_LS4_UnderPF, LM_L_LS5_UnderPF, LM_L_LS6_UnderPF, LM_L_LSA_UnderPF, LM_L_LSC1_UnderPF, LM_L_LSC2_UnderPF, LM_L_LSC3_UnderPF, LM_L_LSC4_UnderPF, LM_L_LSL_UnderPF, LM_L_LSR_UnderPF, LM_L_LSwC1_UnderPF, LM_L_LSwC2_UnderPF, LM_L_LSwC3_UnderPF, LM_L_LSwL1_UnderPF, LM_L_LSwL2_UnderPF, LM_L_LTW1_UnderPF, LM_L_LTW2_UnderPF, LM_L_LTW3_UnderPF, LM_L_LTW4_UnderPF, LM_L_LW1_UnderPF, LM_L_LW2_UnderPF, LM_L_LW3_UnderPF, LM_L_LW4_UnderPF, LM_L_LW5_UnderPF, LM_L_LW6_UnderPF, LM_L_LW7_UnderPF, LM_L_LW8_UnderPF, LM_L_LW9_UnderPF, LM_L_LWiz_UnderPF, LM_L_LX_UnderPF, LM_L_Lspot1_UnderPF, LM_L_Lspot2_UnderPF, LM_D_a00_UnderPF, LM_D_a01_UnderPF, LM_D_a05_UnderPF, LM_D_a10_UnderPF, LM_D_a11_UnderPF, LM_D_a15_UnderPF, _
	LM_GI_gi01_UnderPF, LM_GI_gi02_UnderPF, LM_GI_gi03_UnderPF, LM_GI_gi04_UnderPF, LM_GI_gi05_UnderPF, LM_GI_gi06_UnderPF, LM_GI_gi07_UnderPF, LM_GI_gi08_UnderPF, LM_GI_gi10_UnderPF, LM_GI_gi13_UnderPF, LM_GI_gi15_UnderPF, LM_GI_gi16_UnderPF, LM_GI_gi19_UnderPF, LM_GI_gi20_UnderPF)
Dim BP_swC1: BP_swC1=Array(BM_swC1, LM_F_FL2_swC1, LM_F_FL3_swC1, LM_F_FL4_swC1, LM_F_FL6_swC1, LM_F_FL7_swC1, LM_L_LPC4_swC1, LM_L_LSwC1_swC1, LM_L_Lspot1_swC1, LM_GI_gi20_swC1)
Dim BP_swC2: BP_swC2=Array(BM_swC2, LM_F_FL2_swC2, LM_F_FL3_swC2, LM_F_FL4_swC2, LM_F_FL7_swC2, LM_L_LSwC1_swC2, LM_L_LSwC2_swC2, LM_L_LSwC3_swC2, LM_L_Lspot1_swC2)
Dim BP_swC3: BP_swC3=Array(BM_swC3, LM_F_FL1_swC3, LM_F_FL2_swC3, LM_F_FL3_swC3, LM_F_FL4_swC3, LM_F_FL7_swC3, LM_L_LB3_swC3, LM_L_LB4_swC3, LM_L_LPC5_swC3, LM_L_LSwC3_swC3, LM_L_Lspot1_swC3, LM_GI_gi16_swC3)
Dim BP_swI1: BP_swI1=Array(BM_swI1, LM_F_FL2_swI1, LM_F_FL3_swI1, LM_F_FL7_swI1, LM_GI_gi20_swI1)
Dim BP_swI2: BP_swI2=Array(BM_swI2, LM_F_FL1_swI2, LM_F_FL2_swI2, LM_F_FL3_swI2, LM_F_FL7_swI2, LM_L_LB3_swI2, LM_L_Lspot1_swI2)
Dim BP_swL1: BP_swL1=Array(BM_swL1, LM_F_FL2_swL1, LM_F_FL3_swL1, LM_F_FL7_swL1, LM_GI_gi20_swL1, LM_GI_gi21_swL1)
Dim BP_swL2: BP_swL2=Array(BM_swL2, LM_F_FL2_swL2, LM_F_FL3_swL2, LM_F_FL7_swL2, LM_GI_gi20_swL2, LM_GI_gi21_swL2)
Dim BP_swLB1: BP_swLB1=Array(BM_swLB1, LM_F_FL5_swLB1, LM_L_LB1_swLB1, LM_L_LS1_swLB1, LM_L_LSwL1_swLB1, LM_L_Lspot2_swLB1)
Dim BP_swLB2: BP_swLB2=Array(BM_swLB2, LM_L_LB1_swLB2, LM_L_LSwL2_swLB2)
Dim BP_swLI: BP_swLI=Array(BM_swLI, LM_F_FL5_swLI, LM_L_LLI_swLI, LM_GI_gi01_swLI, LM_GI_gi02_swLI, LM_GI_gi03_swLI, LM_GI_gi04_swLI, LM_GI_gi09_swLI)
Dim BP_swLO: BP_swLO=Array(BM_swLO, LM_F_FL5_swLO, LM_L_LLO_swLO, LM_L_LSL_swLO, LM_L_Lspot2_swLO, LM_GI_gi01_swLO, LM_GI_gi02_swLO, LM_GI_gi03_swLO, LM_GI_gi04_swLO)
Dim BP_swP1: BP_swP1=Array(BM_swP1)
Dim BP_swP2: BP_swP2=Array(BM_swP2)
Dim BP_swR1: BP_swR1=Array(BM_swR1, LM_F_FL1_swR1, LM_F_FL3_swR1, LM_F_FL7_swR1, LM_L_LB4_swR1, LM_L_LF1_swR1, LM_L_LF2_swR1)
Dim BP_swR2: BP_swR2=Array(BM_swR2, LM_F_FL1_swR2, LM_F_FL2_swR2, LM_F_FL3_swR2, LM_F_FL7_swR2, LM_L_LB2_swR2)
Dim BP_swRI: BP_swRI=Array(BM_swRI, LM_F_FL5_swRI, LM_F_FL6_swRI, LM_L_LRI_swRI, LM_GI_gi05_swRI, LM_GI_gi06_swRI, LM_GI_gi07_swRI, LM_GI_gi08_swRI)
Dim BP_swRO: BP_swRO=Array(BM_swRO, LM_F_FL6_swRO, LM_L_LRO_swRO, LM_L_LSR_swRO, LM_GI_gi07_swRO)
' Arrays per lighting scenario
Dim BL_D_a00: BL_D_a00=Array(LM_D_a00_Parts, LM_D_a00_Playfield, LM_D_a00_RFlipU, LM_D_a00_UnderPF)
Dim BL_D_a01: BL_D_a01=Array(LM_D_a01_Parts, LM_D_a01_Playfield, LM_D_a01_RFlipU, LM_D_a01_UnderPF)
Dim BL_D_a02: BL_D_a02=Array(LM_D_a02_Parts, LM_D_a02_Playfield)
Dim BL_D_a03: BL_D_a03=Array(LM_D_a03_Parts, LM_D_a03_Playfield)
Dim BL_D_a04: BL_D_a04=Array(LM_D_a04_Parts, LM_D_a04_Playfield)
Dim BL_D_a05: BL_D_a05=Array(LM_D_a05_Parts, LM_D_a05_Playfield, LM_D_a05_UnderPF)
Dim BL_D_a06: BL_D_a06=Array(LM_D_a06_Parts, LM_D_a06_Playfield, LM_D_a06_RFlipU)
Dim BL_D_a10: BL_D_a10=Array(LM_D_a10_Parts, LM_D_a10_Playfield, LM_D_a10_UnderPF)
Dim BL_D_a11: BL_D_a11=Array(LM_D_a11_Parts, LM_D_a11_Playfield, LM_D_a11_UnderPF)
Dim BL_D_a12: BL_D_a12=Array(LM_D_a12_Parts, LM_D_a12_Playfield)
Dim BL_D_a13: BL_D_a13=Array(LM_D_a13_Parts, LM_D_a13_Playfield)
Dim BL_D_a14: BL_D_a14=Array(LM_D_a14_Parts, LM_D_a14_Playfield)
Dim BL_D_a15: BL_D_a15=Array(LM_D_a15_LFlip, LM_D_a15_LFlipU, LM_D_a15_Parts, LM_D_a15_Playfield, LM_D_a15_UnderPF)
Dim BL_D_a16: BL_D_a16=Array(LM_D_a16_Parts, LM_D_a16_Playfield)
Dim BL_F_FL1: BL_F_FL1=Array(LM_F_FL1_Asteroid1, LM_F_FL1_Asteroid2, LM_F_FL1_Asteroid3, LM_F_FL1_Asteroid4, LM_F_FL1_BR2, LM_F_FL1_BR3, LM_F_FL1_BR4, LM_F_FL1_BS2, LM_F_FL1_BS3, LM_F_FL1_BS4, LM_F_FL1_BmpBot, LM_F_FL1_BmpTopB, LM_F_FL1_DiverterPin, LM_F_FL1_Gate2, LM_F_FL1_GateR, LM_F_FL1_LArm, LM_F_FL1_LockPin, LM_F_FL1_Lsling1, LM_F_FL1_Parts, LM_F_FL1_Playfield, LM_F_FL1_RFlip1, LM_F_FL1_RFlip1U, LM_F_FL1_Rails, LM_F_FL1_Ramp, LM_F_FL1_Rsling2, LM_F_FL1_Ship, LM_F_FL1_Spin, LM_F_FL1_SpinU, LM_F_FL1_TM2, LM_F_FL1_TM3, LM_F_FL1_TM4, LM_F_FL1_TM5, LM_F_FL1_UnderPF, LM_F_FL1_swC3, LM_F_FL1_swI2, LM_F_FL1_swR1, LM_F_FL1_swR2)
Dim BL_F_FL2: BL_F_FL2=Array(LM_F_FL2_Asteroid1, LM_F_FL2_Asteroid2, LM_F_FL2_Asteroid3, LM_F_FL2_Asteroid4, LM_F_FL2_BR2, LM_F_FL2_BR3, LM_F_FL2_BR4, LM_F_FL2_BS2, LM_F_FL2_BS3, LM_F_FL2_BS4, LM_F_FL2_BmpBot, LM_F_FL2_BmpTopB, LM_F_FL2_DiverterPin, LM_F_FL2_GateL, LM_F_FL2_GateR, LM_F_FL2_LockPin, LM_F_FL2_Parts, LM_F_FL2_Playfield, LM_F_FL2_Ramp, LM_F_FL2_Ship, LM_F_FL2_Spin, LM_F_FL2_SpinU, LM_F_FL2_SpinWire, LM_F_FL2_TM2, LM_F_FL2_TM3, LM_F_FL2_TM4, LM_F_FL2_UnderPF, LM_F_FL2_swC1, LM_F_FL2_swC2, LM_F_FL2_swC3, LM_F_FL2_swI1, LM_F_FL2_swI2, LM_F_FL2_swL1, LM_F_FL2_swL2, LM_F_FL2_swR2)
Dim BL_F_FL3: BL_F_FL3=Array(LM_F_FL3_Asteroid1, LM_F_FL3_Asteroid2, LM_F_FL3_Asteroid3, LM_F_FL3_Asteroid4, LM_F_FL3_BR2, LM_F_FL3_BR3, LM_F_FL3_BR4, LM_F_FL3_BS2, LM_F_FL3_BS3, LM_F_FL3_BS4, LM_F_FL3_BmpBot, LM_F_FL3_BmpTopB, LM_F_FL3_DiverterPin, LM_F_FL3_GateL, LM_F_FL3_GateR, LM_F_FL3_LockPin, LM_F_FL3_Parts, LM_F_FL3_Playfield, LM_F_FL3_Ramp, LM_F_FL3_Ship, LM_F_FL3_Spin, LM_F_FL3_SpinU, LM_F_FL3_SpinWire, LM_F_FL3_TM3, LM_F_FL3_TM4, LM_F_FL3_UnderPF, LM_F_FL3_swC1, LM_F_FL3_swC2, LM_F_FL3_swC3, LM_F_FL3_swI1, LM_F_FL3_swI2, LM_F_FL3_swL1, LM_F_FL3_swL2, LM_F_FL3_swR1, LM_F_FL3_swR2)
Dim BL_F_FL4: BL_F_FL4=Array(LM_F_FL4_Asteroid1, LM_F_FL4_Asteroid2, LM_F_FL4_Asteroid3, LM_F_FL4_Asteroid4, LM_F_FL4_BmpTopB, LM_F_FL4_GateR, LM_F_FL4_Parts, LM_F_FL4_Playfield, LM_F_FL4_RFlip1, LM_F_FL4_RFlip1U, LM_F_FL4_Ramp, LM_F_FL4_Spin, LM_F_FL4_SpinU, LM_F_FL4_TM2, LM_F_FL4_TM3, LM_F_FL4_TM4, LM_F_FL4_UnderPF, LM_F_FL4_swC1, LM_F_FL4_swC2, LM_F_FL4_swC3)
Dim BL_F_FL5: BL_F_FL5=Array(LM_F_FL5_BR1, LM_F_FL5_BR4, LM_F_FL5_LArm, LM_F_FL5_LFlip, LM_F_FL5_LFlipU, LM_F_FL5_Lsling1, LM_F_FL5_Lsling2, LM_F_FL5_Parts, LM_F_FL5_Playfield, LM_F_FL5_RArm, LM_F_FL5_RFlip, LM_F_FL5_RFlipU, LM_F_FL5_Rsling1, LM_F_FL5_Rsling2, LM_F_FL5_TM1, LM_F_FL5_TrustPost, LM_F_FL5_UnderPF, LM_F_FL5_swLB1, LM_F_FL5_swLI, LM_F_FL5_swLO, LM_F_FL5_swRI)
Dim BL_F_FL6: BL_F_FL6=Array(LM_F_FL6_BR1, LM_F_FL6_BS1, LM_F_FL6_LArm, LM_F_FL6_LFlip, LM_F_FL6_LFlipU, LM_F_FL6_Lsling1, LM_F_FL6_Lsling2, LM_F_FL6_Parts, LM_F_FL6_Playfield, LM_F_FL6_RArm, LM_F_FL6_RFlip, LM_F_FL6_RFlipU, LM_F_FL6_Ramp, LM_F_FL6_Rsling1, LM_F_FL6_Rsling2, LM_F_FL6_TS2, LM_F_FL6_TS3, LM_F_FL6_TS4, LM_F_FL6_TrustPost, LM_F_FL6_UnderPF, LM_F_FL6_swC1, LM_F_FL6_swRI, LM_F_FL6_swRO)
Dim BL_F_FL7: BL_F_FL7=Array(LM_F_FL7_Asteroid1, LM_F_FL7_Asteroid2, LM_F_FL7_Asteroid3, LM_F_FL7_Asteroid4, LM_F_FL7_BR2, LM_F_FL7_BR3, LM_F_FL7_BR4, LM_F_FL7_BS2, LM_F_FL7_BS3, LM_F_FL7_BS4, LM_F_FL7_BmpBot, LM_F_FL7_BmpTopB, LM_F_FL7_DiverterPin, LM_F_FL7_GateL, LM_F_FL7_GateR, LM_F_FL7_LockPin, LM_F_FL7_Parts, LM_F_FL7_Playfield, LM_F_FL7_Ramp, LM_F_FL7_Ship, LM_F_FL7_Spin, LM_F_FL7_SpinU, LM_F_FL7_SpinWire, LM_F_FL7_TM2, LM_F_FL7_TM3, LM_F_FL7_TM4, LM_F_FL7_TM5, LM_F_FL7_UnderPF, LM_F_FL7_swC1, LM_F_FL7_swC2, LM_F_FL7_swC3, LM_F_FL7_swI1, LM_F_FL7_swI2, LM_F_FL7_swL1, LM_F_FL7_swL2, LM_F_FL7_swR1, LM_F_FL7_swR2)
Dim BL_GI_gi01: BL_GI_gi01=Array(LM_GI_gi01_LArm, LM_GI_gi01_LFlip, LM_GI_gi01_LFlipU, LM_GI_gi01_Lsling1, LM_GI_gi01_Lsling2, LM_GI_gi01_Parts, LM_GI_gi01_Playfield, LM_GI_gi01_RFlip, LM_GI_gi01_RFlipU, LM_GI_gi01_UnderPF, LM_GI_gi01_swLI, LM_GI_gi01_swLO)
Dim BL_GI_gi02: BL_GI_gi02=Array(LM_GI_gi02_LArm, LM_GI_gi02_LFlip, LM_GI_gi02_LFlipU, LM_GI_gi02_Parts, LM_GI_gi02_Playfield, LM_GI_gi02_RFlip, LM_GI_gi02_RFlipU, LM_GI_gi02_UnderPF, LM_GI_gi02_swLI, LM_GI_gi02_swLO)
Dim BL_GI_gi03: BL_GI_gi03=Array(LM_GI_gi03_LArm, LM_GI_gi03_LFlip, LM_GI_gi03_LFlipU, LM_GI_gi03_Lsling1, LM_GI_gi03_Lsling2, LM_GI_gi03_Parts, LM_GI_gi03_Playfield, LM_GI_gi03_RFlip, LM_GI_gi03_RFlipU, LM_GI_gi03_UnderPF, LM_GI_gi03_swLI, LM_GI_gi03_swLO)
Dim BL_GI_gi04: BL_GI_gi04=Array(LM_GI_gi04_BmpTopR, LM_GI_gi04_LArm, LM_GI_gi04_LFlip, LM_GI_gi04_LFlipU, LM_GI_gi04_Lsling1, LM_GI_gi04_Lsling2, LM_GI_gi04_Parts, LM_GI_gi04_Playfield, LM_GI_gi04_UnderPF, LM_GI_gi04_swLI, LM_GI_gi04_swLO)
Dim BL_GI_gi05: BL_GI_gi05=Array(LM_GI_gi05_Parts, LM_GI_gi05_Playfield, LM_GI_gi05_RArm, LM_GI_gi05_RFlip, LM_GI_gi05_RFlipU, LM_GI_gi05_Rsling1, LM_GI_gi05_Rsling2, LM_GI_gi05_UnderPF, LM_GI_gi05_swRI)
Dim BL_GI_gi06: BL_GI_gi06=Array(LM_GI_gi06_Parts, LM_GI_gi06_Playfield, LM_GI_gi06_RArm, LM_GI_gi06_RFlip, LM_GI_gi06_RFlipU, LM_GI_gi06_Rsling1, LM_GI_gi06_UnderPF, LM_GI_gi06_swRI)
Dim BL_GI_gi07: BL_GI_gi07=Array(LM_GI_gi07_LFlip, LM_GI_gi07_LFlipU, LM_GI_gi07_Lsling2, LM_GI_gi07_Parts, LM_GI_gi07_Playfield, LM_GI_gi07_RArm, LM_GI_gi07_RFlip, LM_GI_gi07_RFlipU, LM_GI_gi07_Rsling1, LM_GI_gi07_Rsling2, LM_GI_gi07_UnderPF, LM_GI_gi07_swRI, LM_GI_gi07_swRO)
Dim BL_GI_gi08: BL_GI_gi08=Array(LM_GI_gi08_Parts, LM_GI_gi08_Playfield, LM_GI_gi08_RArm, LM_GI_gi08_RFlip, LM_GI_gi08_RFlipU, LM_GI_gi08_Rsling1, LM_GI_gi08_Rsling2, LM_GI_gi08_UnderPF, LM_GI_gi08_swRI)
Dim BL_GI_gi09: BL_GI_gi09=Array(LM_GI_gi09_Parts, LM_GI_gi09_Playfield, LM_GI_gi09_swLI)
Dim BL_GI_gi10: BL_GI_gi10=Array(LM_GI_gi10_Gate2, LM_GI_gi10_Parts, LM_GI_gi10_Playfield, LM_GI_gi10_RFlip1U, LM_GI_gi10_TS1, LM_GI_gi10_TS2, LM_GI_gi10_TS3, LM_GI_gi10_TS4, LM_GI_gi10_UnderPF)
Dim BL_GI_gi11: BL_GI_gi11=Array(LM_GI_gi11_Parts, LM_GI_gi11_Playfield)
Dim BL_GI_gi12: BL_GI_gi12=Array(LM_GI_gi12_Parts, LM_GI_gi12_Playfield)
Dim BL_GI_gi13: BL_GI_gi13=Array(LM_GI_gi13_BR4, LM_GI_gi13_BS2, LM_GI_gi13_BS4, LM_GI_gi13_BmpBot, LM_GI_gi13_BmpTopB, LM_GI_gi13_GateR, LM_GI_gi13_Parts, LM_GI_gi13_Playfield, LM_GI_gi13_RFlip1U, LM_GI_gi13_TM4, LM_GI_gi13_TM5, LM_GI_gi13_UnderPF)
Dim BL_GI_gi14: BL_GI_gi14=Array(LM_GI_gi14_Gate2, LM_GI_gi14_LockPin, LM_GI_gi14_Parts, LM_GI_gi14_Playfield, LM_GI_gi14_RFlip1, LM_GI_gi14_RFlip1U, LM_GI_gi14_TM5)
Dim BL_GI_gi15: BL_GI_gi15=Array(LM_GI_gi15_LockPin, LM_GI_gi15_Parts, LM_GI_gi15_Playfield, LM_GI_gi15_RFlip1, LM_GI_gi15_RFlip1U, LM_GI_gi15_UnderPF)
Dim BL_GI_gi16: BL_GI_gi16=Array(LM_GI_gi16_Asteroid1, LM_GI_gi16_Asteroid2, LM_GI_gi16_Asteroid3, LM_GI_gi16_Asteroid4, LM_GI_gi16_BR2, LM_GI_gi16_BR3, LM_GI_gi16_BR4, LM_GI_gi16_BS2, LM_GI_gi16_BS3, LM_GI_gi16_BS4, LM_GI_gi16_BmpBot, LM_GI_gi16_BmpTopB, LM_GI_gi16_GateR, LM_GI_gi16_Parts, LM_GI_gi16_Playfield, LM_GI_gi16_Ramp, LM_GI_gi16_TM4, LM_GI_gi16_UnderPF, LM_GI_gi16_swC3)
Dim BL_GI_gi17: BL_GI_gi17=Array(LM_GI_gi17_BR2, LM_GI_gi17_Parts, LM_GI_gi17_Playfield)
Dim BL_GI_gi18: BL_GI_gi18=Array(LM_GI_gi18_Parts, LM_GI_gi18_Playfield)
Dim BL_GI_gi19: BL_GI_gi19=Array(LM_GI_gi19_LockPin, LM_GI_gi19_Parts, LM_GI_gi19_Playfield, LM_GI_gi19_RFlip1, LM_GI_gi19_RFlip1U, LM_GI_gi19_TM5, LM_GI_gi19_UnderPF)
Dim BL_GI_gi20: BL_GI_gi20=Array(LM_GI_gi20_Asteroid1, LM_GI_gi20_Asteroid2, LM_GI_gi20_Asteroid3, LM_GI_gi20_Asteroid4, LM_GI_gi20_GateL, LM_GI_gi20_Parts, LM_GI_gi20_Playfield, LM_GI_gi20_Ramp, LM_GI_gi20_Spin, LM_GI_gi20_SpinU, LM_GI_gi20_SpinWire, LM_GI_gi20_TM2, LM_GI_gi20_UnderPF, LM_GI_gi20_swC1, LM_GI_gi20_swI1, LM_GI_gi20_swL1, LM_GI_gi20_swL2)
Dim BL_GI_gi21: BL_GI_gi21=Array(LM_GI_gi21_Asteroid1, LM_GI_gi21_Asteroid2, LM_GI_gi21_Asteroid3, LM_GI_gi21_Asteroid4, LM_GI_gi21_GateL, LM_GI_gi21_Parts, LM_GI_gi21_Playfield, LM_GI_gi21_Ramp, LM_GI_gi21_Spin, LM_GI_gi21_SpinU, LM_GI_gi21_SpinWire, LM_GI_gi21_TM2, LM_GI_gi21_swL1, LM_GI_gi21_swL2)
Dim BL_GI_giapron: BL_GI_giapron=Array(LM_GI_giapron_LFlip, LM_GI_giapron_LFlipU, LM_GI_giapron_Lsling1, LM_GI_giapron_Lsling2, LM_GI_giapron_Parts, LM_GI_giapron_Playfield, LM_GI_giapron_RFlip, LM_GI_giapron_RFlipU, LM_GI_giapron_Rsling1, LM_GI_giapron_Rsling2, LM_GI_giapron_TrustPost)
Dim BL_L_LB1: BL_L_LB1=Array(LM_L_LB1_BR1, LM_L_LB1_BS1, LM_L_LB1_BmpBot, LM_L_LB1_BmpTopR, LM_L_LB1_LockPin, LM_L_LB1_Parts, LM_L_LB1_Playfield, LM_L_LB1_RFlip1, LM_L_LB1_RFlip1U, LM_L_LB1_Ramp, LM_L_LB1_Rsling1, LM_L_LB1_Rsling2, LM_L_LB1_Ship, LM_L_LB1_TM1, LM_L_LB1_TM2, LM_L_LB1_TMet1, LM_L_LB1_TS2, LM_L_LB1_UnderPF, LM_L_LB1_swLB1, LM_L_LB1_swLB2)
Dim BL_L_LB2: BL_L_LB2=Array(LM_L_LB2_Asteroid1, LM_L_LB2_Asteroid2, LM_L_LB2_Asteroid3, LM_L_LB2_Asteroid4, LM_L_LB2_BR2, LM_L_LB2_BR3, LM_L_LB2_BR4, LM_L_LB2_BS2, LM_L_LB2_BS3, LM_L_LB2_BS4, LM_L_LB2_BmpBot, LM_L_LB2_BmpTopB, LM_L_LB2_DiverterPin, LM_L_LB2_Parts, LM_L_LB2_Playfield, LM_L_LB2_swR2)
Dim BL_L_LB3: BL_L_LB3=Array(LM_L_LB3_Asteroid1, LM_L_LB3_Asteroid2, LM_L_LB3_Asteroid3, LM_L_LB3_Asteroid4, LM_L_LB3_BR2, LM_L_LB3_BR3, LM_L_LB3_BR4, LM_L_LB3_BS2, LM_L_LB3_BS3, LM_L_LB3_BS4, LM_L_LB3_BmpBot, LM_L_LB3_BmpTopB, LM_L_LB3_DiverterPin, LM_L_LB3_Parts, LM_L_LB3_Playfield, LM_L_LB3_Spin, LM_L_LB3_TM3, LM_L_LB3_TM4, LM_L_LB3_UnderPF, LM_L_LB3_swC3, LM_L_LB3_swI2)
Dim BL_L_LB4: BL_L_LB4=Array(LM_L_LB4_Asteroid1, LM_L_LB4_Asteroid2, LM_L_LB4_Asteroid3, LM_L_LB4_Asteroid4, LM_L_LB4_BR2, LM_L_LB4_BR3, LM_L_LB4_BR4, LM_L_LB4_BS2, LM_L_LB4_BS3, LM_L_LB4_BS4, LM_L_LB4_BmpBot, LM_L_LB4_BmpTopB, LM_L_LB4_GateR, LM_L_LB4_Parts, LM_L_LB4_Playfield, LM_L_LB4_TM4, LM_L_LB4_UnderPF, LM_L_LB4_swC3, LM_L_LB4_swR1)
Dim BL_L_LC1: BL_L_LC1=Array(LM_L_LC1_LFlip, LM_L_LC1_LFlipU, LM_L_LC1_Parts, LM_L_LC1_Playfield, LM_L_LC1_UnderPF)
Dim BL_L_LC2: BL_L_LC2=Array(LM_L_LC2_LFlip, LM_L_LC2_LFlipU, LM_L_LC2_Parts, LM_L_LC2_Playfield, LM_L_LC2_UnderPF)
Dim BL_L_LC3: BL_L_LC3=Array(LM_L_LC3_LFlipU, LM_L_LC3_Playfield, LM_L_LC3_UnderPF)
Dim BL_L_LC4: BL_L_LC4=Array(LM_L_LC4_LFlipU, LM_L_LC4_Playfield, LM_L_LC4_UnderPF)
Dim BL_L_LC5: BL_L_LC5=Array(LM_L_LC5_Playfield, LM_L_LC5_RFlipU, LM_L_LC5_UnderPF)
Dim BL_L_LC6: BL_L_LC6=Array(LM_L_LC6_Playfield, LM_L_LC6_RFlipU, LM_L_LC6_UnderPF)
Dim BL_L_LC7: BL_L_LC7=Array(LM_L_LC7_Playfield, LM_L_LC7_RFlipU, LM_L_LC7_UnderPF)
Dim BL_L_LC8: BL_L_LC8=Array(LM_L_LC8_Parts, LM_L_LC8_Playfield, LM_L_LC8_RFlip, LM_L_LC8_RFlipU, LM_L_LC8_UnderPF)
Dim BL_L_LCC1: BL_L_LCC1=Array(LM_L_LCC1_Parts, LM_L_LCC1_Playfield, LM_L_LCC1_Ramp, LM_L_LCC1_UnderPF)
Dim BL_L_LCC2: BL_L_LCC2=Array(LM_L_LCC2_Parts, LM_L_LCC2_Playfield, LM_L_LCC2_UnderPF)
Dim BL_L_LCC3: BL_L_LCC3=Array(LM_L_LCC3_Parts, LM_L_LCC3_Playfield, LM_L_LCC3_UnderPF)
Dim BL_L_LCR1: BL_L_LCR1=Array(LM_L_LCR1_Lsling1, LM_L_LCR1_Lsling2, LM_L_LCR1_Parts, LM_L_LCR1_Playfield, LM_L_LCR1_UnderPF)
Dim BL_L_LCR2: BL_L_LCR2=Array(LM_L_LCR2_Lsling1, LM_L_LCR2_Lsling2, LM_L_LCR2_Parts, LM_L_LCR2_Playfield, LM_L_LCR2_UnderPF)
Dim BL_L_LCWiz: BL_L_LCWiz=Array(LM_L_LCWiz_Parts, LM_L_LCWiz_Playfield, LM_L_LCWiz_UnderPF)
Dim BL_L_LEBR: BL_L_LEBR=Array(LM_L_LEBR_Parts, LM_L_LEBR_Playfield, LM_L_LEBR_TM4, LM_L_LEBR_UnderPF)
Dim BL_L_LF1: BL_L_LF1=Array(LM_L_LF1_Parts, LM_L_LF1_Playfield, LM_L_LF1_UnderPF, LM_L_LF1_swR1)
Dim BL_L_LF2: BL_L_LF2=Array(LM_L_LF2_Parts, LM_L_LF2_Playfield, LM_L_LF2_TM5, LM_L_LF2_UnderPF, LM_L_LF2_swR1)
Dim BL_L_LF3: BL_L_LF3=Array(LM_L_LF3_Parts, LM_L_LF3_Playfield, LM_L_LF3_RFlip1U, LM_L_LF3_TM5, LM_L_LF3_UnderPF)
Dim BL_L_LH1: BL_L_LH1=Array(LM_L_LH1_LFlip, LM_L_LH1_LFlipU, LM_L_LH1_Parts, LM_L_LH1_Playfield, LM_L_LH1_UnderPF)
Dim BL_L_LH2: BL_L_LH2=Array(LM_L_LH2_LFlip, LM_L_LH2_LFlipU, LM_L_LH2_Playfield, LM_L_LH2_UnderPF)
Dim BL_L_LH3: BL_L_LH3=Array(LM_L_LH3_LFlip, LM_L_LH3_LFlipU, LM_L_LH3_Playfield, LM_L_LH3_UnderPF)
Dim BL_L_LH4: BL_L_LH4=Array(LM_L_LH4_LFlip, LM_L_LH4_LFlipU, LM_L_LH4_Playfield, LM_L_LH4_UnderPF)
Dim BL_L_LH5: BL_L_LH5=Array(LM_L_LH5_LFlipU, LM_L_LH5_Playfield, LM_L_LH5_RFlipU, LM_L_LH5_UnderPF)
Dim BL_L_LH6: BL_L_LH6=Array(LM_L_LH6_Playfield, LM_L_LH6_RFlipU, LM_L_LH6_UnderPF)
Dim BL_L_LH7: BL_L_LH7=Array(LM_L_LH7_Playfield, LM_L_LH7_RFlip, LM_L_LH7_RFlipU, LM_L_LH7_UnderPF)
Dim BL_L_LH8: BL_L_LH8=Array(LM_L_LH8_Playfield, LM_L_LH8_RFlip, LM_L_LH8_RFlipU, LM_L_LH8_UnderPF)
Dim BL_L_LH9: BL_L_LH9=Array(LM_L_LH9_Parts, LM_L_LH9_Playfield, LM_L_LH9_RFlip, LM_L_LH9_RFlipU, LM_L_LH9_UnderPF)
Dim BL_L_LLI: BL_L_LLI=Array(LM_L_LLI_Parts, LM_L_LLI_Playfield, LM_L_LLI_UnderPF, LM_L_LLI_swLI)
Dim BL_L_LLO: BL_L_LLO=Array(LM_L_LLO_Parts, LM_L_LLO_Playfield, LM_L_LLO_UnderPF, LM_L_LLO_swLO)
Dim BL_L_LLWiz: BL_L_LLWiz=Array(LM_L_LLWiz_Parts, LM_L_LLWiz_Playfield, LM_L_LLWiz_UnderPF)
Dim BL_L_LM1: BL_L_LM1=Array(LM_L_LM1_Parts, LM_L_LM1_Playfield, LM_L_LM1_TM1, LM_L_LM1_UnderPF)
Dim BL_L_LM2: BL_L_LM2=Array(LM_L_LM2_Parts, LM_L_LM2_Playfield, LM_L_LM2_TM2, LM_L_LM2_UnderPF)
Dim BL_L_LM3: BL_L_LM3=Array(LM_L_LM3_Asteroid1, LM_L_LM3_Asteroid2, LM_L_LM3_Asteroid3, LM_L_LM3_Asteroid4, LM_L_LM3_Playfield, LM_L_LM3_TM3, LM_L_LM3_UnderPF)
Dim BL_L_LM4: BL_L_LM4=Array(LM_L_LM4_Parts, LM_L_LM4_Playfield, LM_L_LM4_TM4, LM_L_LM4_UnderPF)
Dim BL_L_LM5: BL_L_LM5=Array(LM_L_LM5_Parts, LM_L_LM5_Playfield, LM_L_LM5_TM5, LM_L_LM5_UnderPF)
Dim BL_L_LMLR: BL_L_LMLR=Array(LM_L_LMLR_Parts, LM_L_LMLR_Playfield, LM_L_LMLR_TM5, LM_L_LMLR_UnderPF)
Dim BL_L_LMR: BL_L_LMR=Array(LM_L_LMR_GateR, LM_L_LMR_Parts, LM_L_LMR_Playfield, LM_L_LMR_TM4, LM_L_LMR_UnderPF)
Dim BL_L_LMR1: BL_L_LMR1=Array(LM_L_LMR1_Parts, LM_L_LMR1_Playfield, LM_L_LMR1_Rsling1, LM_L_LMR1_Rsling2, LM_L_LMR1_UnderPF)
Dim BL_L_LMR2: BL_L_LMR2=Array(LM_L_LMR2_Parts, LM_L_LMR2_Playfield, LM_L_LMR2_Rsling1, LM_L_LMR2_Rsling2, LM_L_LMR2_UnderPF)
Dim BL_L_LMet1: BL_L_LMet1=Array(LM_L_LMet1_BR1, LM_L_LMet1_BS1, LM_L_LMet1_BmpTopR, LM_L_LMet1_Parts, LM_L_LMet1_Playfield, LM_L_LMet1_TMet1, LM_L_LMet1_UnderPF)
Dim BL_L_LMet2: BL_L_LMet2=Array(LM_L_LMet2_BmpTopR, LM_L_LMet2_Parts, LM_L_LMet2_Playfield, LM_L_LMet2_TMet2, LM_L_LMet2_UnderPF)
Dim BL_L_LMet3: BL_L_LMet3=Array(LM_L_LMet3_Parts, LM_L_LMet3_Playfield, LM_L_LMet3_TMet3, LM_L_LMet3_UnderPF)
Dim BL_L_LMet4: BL_L_LMet4=Array(LM_L_LMet4_Parts, LM_L_LMet4_Playfield, LM_L_LMet4_TMet4, LM_L_LMet4_UnderPF)
Dim BL_L_LPC1: BL_L_LPC1=Array(LM_L_LPC1_Asteroid1, LM_L_LPC1_Asteroid4, LM_L_LPC1_GateL, LM_L_LPC1_Parts, LM_L_LPC1_Playfield, LM_L_LPC1_Ramp, LM_L_LPC1_SpinU, LM_L_LPC1_TM2, LM_L_LPC1_UnderPF)
Dim BL_L_LPC2: BL_L_LPC2=Array(LM_L_LPC2_Parts, LM_L_LPC2_Playfield, LM_L_LPC2_TM2, LM_L_LPC2_UnderPF)
Dim BL_L_LPC3: BL_L_LPC3=Array(LM_L_LPC3_Parts, LM_L_LPC3_Playfield, LM_L_LPC3_UnderPF)
Dim BL_L_LPC4: BL_L_LPC4=Array(LM_L_LPC4_Asteroid1, LM_L_LPC4_Asteroid2, LM_L_LPC4_Asteroid3, LM_L_LPC4_Asteroid4, LM_L_LPC4_Parts, LM_L_LPC4_Playfield, LM_L_LPC4_Ramp, LM_L_LPC4_TM3, LM_L_LPC4_UnderPF, LM_L_LPC4_swC1)
Dim BL_L_LPC5: BL_L_LPC5=Array(LM_L_LPC5_Asteroid1, LM_L_LPC5_Asteroid2, LM_L_LPC5_Asteroid3, LM_L_LPC5_Asteroid4, LM_L_LPC5_Parts, LM_L_LPC5_Playfield, LM_L_LPC5_TM3, LM_L_LPC5_TM4, LM_L_LPC5_UnderPF, LM_L_LPC5_swC3)
Dim BL_L_LPF: BL_L_LPF=Array(LM_L_LPF_Asteroid1, LM_L_LPF_Asteroid2, LM_L_LPF_Asteroid3, LM_L_LPF_Asteroid4, LM_L_LPF_Playfield, LM_L_LPF_TM3, LM_L_LPF_UnderPF)
Dim BL_L_LPR1: BL_L_LPR1=Array(LM_L_LPR1_Parts, LM_L_LPR1_Playfield, LM_L_LPR1_UnderPF)
Dim BL_L_LPR2: BL_L_LPR2=Array(LM_L_LPR2_Parts, LM_L_LPR2_Playfield, LM_L_LPR2_UnderPF)
Dim BL_L_LPR3: BL_L_LPR3=Array(LM_L_LPR3_Parts, LM_L_LPR3_Playfield, LM_L_LPR3_UnderPF)
Dim BL_L_LPR4: BL_L_LPR4=Array(LM_L_LPR4_LFlip, LM_L_LPR4_LFlipU, LM_L_LPR4_Parts, LM_L_LPR4_Playfield, LM_L_LPR4_UnderPF)
Dim BL_L_LPR5: BL_L_LPR5=Array(LM_L_LPR5_LFlipU, LM_L_LPR5_Parts, LM_L_LPR5_Playfield, LM_L_LPR5_RFlipU, LM_L_LPR5_UnderPF)
Dim BL_L_LPR6: BL_L_LPR6=Array(LM_L_LPR6_Parts, LM_L_LPR6_Playfield, LM_L_LPR6_RFlipU, LM_L_LPR6_UnderPF)
Dim BL_L_LRI: BL_L_LRI=Array(LM_L_LRI_Parts, LM_L_LRI_Playfield, LM_L_LRI_UnderPF, LM_L_LRI_swRI)
Dim BL_L_LRO: BL_L_LRO=Array(LM_L_LRO_Parts, LM_L_LRO_Playfield, LM_L_LRO_UnderPF, LM_L_LRO_swRO)
Dim BL_L_LS1: BL_L_LS1=Array(LM_L_LS1_BmpTopR, LM_L_LS1_Parts, LM_L_LS1_Playfield, LM_L_LS1_TM1, LM_L_LS1_UnderPF, LM_L_LS1_swLB1)
Dim BL_L_LS2: BL_L_LS2=Array(LM_L_LS2_BmpTopR, LM_L_LS2_Parts, LM_L_LS2_Playfield, LM_L_LS2_UnderPF)
Dim BL_L_LS3: BL_L_LS3=Array(LM_L_LS3_Parts, LM_L_LS3_Playfield, LM_L_LS3_Ship, LM_L_LS3_TMet2, LM_L_LS3_UnderPF)
Dim BL_L_LS4: BL_L_LS4=Array(LM_L_LS4_Parts, LM_L_LS4_Playfield, LM_L_LS4_UnderPF)
Dim BL_L_LS5: BL_L_LS5=Array(LM_L_LS5_Parts, LM_L_LS5_Playfield, LM_L_LS5_RFlip1U, LM_L_LS5_UnderPF)
Dim BL_L_LS6: BL_L_LS6=Array(LM_L_LS6_Parts, LM_L_LS6_Playfield, LM_L_LS6_RFlip1, LM_L_LS6_RFlip1U, LM_L_LS6_UnderPF)
Dim BL_L_LSA: BL_L_LSA=Array(LM_L_LSA_LFlip, LM_L_LSA_LFlipU, LM_L_LSA_Playfield, LM_L_LSA_RFlip, LM_L_LSA_RFlipU, LM_L_LSA_TrustPost, LM_L_LSA_UnderPF)
Dim BL_L_LSC1: BL_L_LSC1=Array(LM_L_LSC1_Parts, LM_L_LSC1_Playfield, LM_L_LSC1_TS1, LM_L_LSC1_TS2, LM_L_LSC1_UnderPF)
Dim BL_L_LSC2: BL_L_LSC2=Array(LM_L_LSC2_Parts, LM_L_LSC2_Playfield, LM_L_LSC2_TS1, LM_L_LSC2_TS2, LM_L_LSC2_TS3, LM_L_LSC2_UnderPF)
Dim BL_L_LSC3: BL_L_LSC3=Array(LM_L_LSC3_Parts, LM_L_LSC3_Playfield, LM_L_LSC3_TS2, LM_L_LSC3_TS3, LM_L_LSC3_TS4, LM_L_LSC3_UnderPF)
Dim BL_L_LSC4: BL_L_LSC4=Array(LM_L_LSC4_Parts, LM_L_LSC4_Playfield, LM_L_LSC4_TS4, LM_L_LSC4_UnderPF)
Dim BL_L_LSL: BL_L_LSL=Array(LM_L_LSL_Parts, LM_L_LSL_Playfield, LM_L_LSL_UnderPF, LM_L_LSL_swLO)
Dim BL_L_LSR: BL_L_LSR=Array(LM_L_LSR_Parts, LM_L_LSR_Playfield, LM_L_LSR_UnderPF, LM_L_LSR_swRO)
Dim BL_L_LShip: BL_L_LShip=Array(LM_L_LShip_Parts, LM_L_LShip_Ship)
Dim BL_L_LSwC1: BL_L_LSwC1=Array(LM_L_LSwC1_Asteroid1, LM_L_LSwC1_Asteroid2, LM_L_LSwC1_Asteroid3, LM_L_LSwC1_Asteroid4, LM_L_LSwC1_Parts, LM_L_LSwC1_Playfield, LM_L_LSwC1_UnderPF, LM_L_LSwC1_swC1, LM_L_LSwC1_swC2)
Dim BL_L_LSwC2: BL_L_LSwC2=Array(LM_L_LSwC2_Asteroid1, LM_L_LSwC2_Asteroid2, LM_L_LSwC2_Asteroid3, LM_L_LSwC2_Asteroid4, LM_L_LSwC2_BmpTopB, LM_L_LSwC2_Parts, LM_L_LSwC2_Playfield, LM_L_LSwC2_TM3, LM_L_LSwC2_UnderPF, LM_L_LSwC2_swC2)
Dim BL_L_LSwC3: BL_L_LSwC3=Array(LM_L_LSwC3_Asteroid1, LM_L_LSwC3_Asteroid2, LM_L_LSwC3_Asteroid3, LM_L_LSwC3_Asteroid4, LM_L_LSwC3_Parts, LM_L_LSwC3_Playfield, LM_L_LSwC3_UnderPF, LM_L_LSwC3_swC2, LM_L_LSwC3_swC3)
Dim BL_L_LSwL1: BL_L_LSwL1=Array(LM_L_LSwL1_BR1, LM_L_LSwL1_BS1, LM_L_LSwL1_BmpTopR, LM_L_LSwL1_Parts, LM_L_LSwL1_Playfield, LM_L_LSwL1_TM1, LM_L_LSwL1_UnderPF, LM_L_LSwL1_swLB1)
Dim BL_L_LSwL2: BL_L_LSwL2=Array(LM_L_LSwL2_BS1, LM_L_LSwL2_BmpBot, LM_L_LSwL2_BmpTopR, LM_L_LSwL2_Parts, LM_L_LSwL2_Playfield, LM_L_LSwL2_UnderPF, LM_L_LSwL2_swLB2)
Dim BL_L_LTW1: BL_L_LTW1=Array(LM_L_LTW1_Parts, LM_L_LTW1_Playfield, LM_L_LTW1_Ramp, LM_L_LTW1_UnderPF)
Dim BL_L_LTW2: BL_L_LTW2=Array(LM_L_LTW2_Parts, LM_L_LTW2_Playfield, LM_L_LTW2_Ramp, LM_L_LTW2_UnderPF)
Dim BL_L_LTW3: BL_L_LTW3=Array(LM_L_LTW3_Parts, LM_L_LTW3_Playfield, LM_L_LTW3_UnderPF)
Dim BL_L_LTW4: BL_L_LTW4=Array(LM_L_LTW4_Parts, LM_L_LTW4_Playfield, LM_L_LTW4_UnderPF)
Dim BL_L_LW1: BL_L_LW1=Array(LM_L_LW1_Parts, LM_L_LW1_Playfield, LM_L_LW1_UnderPF)
Dim BL_L_LW2: BL_L_LW2=Array(LM_L_LW2_Parts, LM_L_LW2_Playfield, LM_L_LW2_UnderPF)
Dim BL_L_LW3: BL_L_LW3=Array(LM_L_LW3_Parts, LM_L_LW3_Playfield, LM_L_LW3_UnderPF)
Dim BL_L_LW4: BL_L_LW4=Array(LM_L_LW4_Parts, LM_L_LW4_Playfield, LM_L_LW4_UnderPF)
Dim BL_L_LW5: BL_L_LW5=Array(LM_L_LW5_Parts, LM_L_LW5_Playfield, LM_L_LW5_UnderPF)
Dim BL_L_LW6: BL_L_LW6=Array(LM_L_LW6_BmpTopR, LM_L_LW6_Parts, LM_L_LW6_Playfield, LM_L_LW6_UnderPF)
Dim BL_L_LW7: BL_L_LW7=Array(LM_L_LW7_BmpTopR, LM_L_LW7_Parts, LM_L_LW7_Playfield, LM_L_LW7_UnderPF)
Dim BL_L_LW8: BL_L_LW8=Array(LM_L_LW8_BmpTopR, LM_L_LW8_Parts, LM_L_LW8_Playfield, LM_L_LW8_UnderPF)
Dim BL_L_LW9: BL_L_LW9=Array(LM_L_LW9_Parts, LM_L_LW9_Playfield, LM_L_LW9_UnderPF)
Dim BL_L_LWiz: BL_L_LWiz=Array(LM_L_LWiz_Parts, LM_L_LWiz_Playfield, LM_L_LWiz_UnderPF)
Dim BL_L_LX: BL_L_LX=Array(LM_L_LX_Parts, LM_L_LX_Playfield, LM_L_LX_UnderPF)
Dim BL_L_Lspot1: BL_L_Lspot1=Array(LM_L_Lspot1_Asteroid1, LM_L_Lspot1_Asteroid2, LM_L_Lspot1_Asteroid3, LM_L_Lspot1_Asteroid4, LM_L_Lspot1_BR4, LM_L_Lspot1_BS4, LM_L_Lspot1_BmpTopB, LM_L_Lspot1_Parts, LM_L_Lspot1_Playfield, LM_L_Lspot1_Ramp, LM_L_Lspot1_Spin, LM_L_Lspot1_SpinU, LM_L_Lspot1_SpinWire, LM_L_Lspot1_TM3, LM_L_Lspot1_TM4, LM_L_Lspot1_UnderPF, LM_L_Lspot1_swC1, LM_L_Lspot1_swC2, LM_L_Lspot1_swC3, LM_L_Lspot1_swI2)
Dim BL_L_Lspot2: BL_L_Lspot2=Array(LM_L_Lspot2_GateL, LM_L_Lspot2_LArm, LM_L_Lspot2_LFlip, LM_L_Lspot2_LFlipU, LM_L_Lspot2_LockPin, LM_L_Lspot2_Lsling1, LM_L_Lspot2_Lsling2, LM_L_Lspot2_Parts, LM_L_Lspot2_Playfield, LM_L_Lspot2_RArm, LM_L_Lspot2_RFlip, LM_L_Lspot2_RFlipU, LM_L_Lspot2_Ramp, LM_L_Lspot2_Rsling1, LM_L_Lspot2_Rsling2, LM_L_Lspot2_UnderPF, LM_L_Lspot2_swLB1, LM_L_Lspot2_swLO)
Dim BL_Stars: BL_Stars=Array(LM_Stars_Parts, LM_Stars_Ramp)
Dim BL_World: BL_World=Array(BM_Asteroid1, BM_BR1, BM_BR2, BM_BR3, BM_BR4, BM_BS1, BM_BS2, BM_BS3, BM_BS4, BM_BmpBot, BM_BmpTopB, BM_BmpTopR, BM_DiverterPin, BM_Gate2, BM_GateL, BM_GateR, BM_LArm, BM_LFlip, BM_LFlipU, BM_LockPin, BM_Lsling1, BM_Lsling2, BM_Parts, BM_Playfield, BM_RArm, BM_RFlip, BM_RFlip1, BM_RFlip1U, BM_RFlipU, BM_Rails, BM_Ramp, BM_Rsling1, BM_Rsling2, BM_Ship, BM_Spin, BM_SpinU, BM_SpinWire, BM_TM1, BM_TM2, BM_TM3, BM_TM4, BM_TM5, BM_TMet1, BM_TMet2, BM_TMet3, BM_TMet4, BM_TS1, BM_TS2, BM_TS3, BM_TS4, BM_TrustPost, BM_UnderPF, BM_swC1, BM_swC2, BM_swC3, BM_swI1, BM_swI2, BM_swL1, BM_swL2, BM_swLB1, BM_swLB2, BM_swLI, BM_swLO, BM_swP1, BM_swP2, BM_swR1, BM_swR2, BM_swRI, BM_swRO)
' Global arrays
Dim BG_Bakemap: BG_Bakemap=Array(BM_Asteroid1, BM_BR1, BM_BR2, BM_BR3, BM_BR4, BM_BS1, BM_BS2, BM_BS3, BM_BS4, BM_BmpBot, BM_BmpTopB, BM_BmpTopR, BM_DiverterPin, BM_Gate2, BM_GateL, BM_GateR, BM_LArm, BM_LFlip, BM_LFlipU, BM_LockPin, BM_Lsling1, BM_Lsling2, BM_Parts, BM_Playfield, BM_RArm, BM_RFlip, BM_RFlip1, BM_RFlip1U, BM_RFlipU, BM_Rails, BM_Ramp, BM_Rsling1, BM_Rsling2, BM_Ship, BM_Spin, BM_SpinU, BM_SpinWire, BM_TM1, BM_TM2, BM_TM3, BM_TM4, BM_TM5, BM_TMet1, BM_TMet2, BM_TMet3, BM_TMet4, BM_TS1, BM_TS2, BM_TS3, BM_TS4, BM_TrustPost, BM_UnderPF, BM_swC1, BM_swC2, BM_swC3, BM_swI1, BM_swI2, BM_swL1, BM_swL2, BM_swLB1, BM_swLB2, BM_swLI, BM_swLO, BM_swP1, BM_swP2, BM_swR1, BM_swR2, BM_swRI, BM_swRO)
Dim BG_Lightmap: BG_Lightmap=Array(LM_D_a00_Parts, LM_D_a00_Playfield, LM_D_a00_RFlipU, LM_D_a00_UnderPF, LM_D_a01_Parts, LM_D_a01_Playfield, LM_D_a01_RFlipU, LM_D_a01_UnderPF, LM_D_a02_Parts, LM_D_a02_Playfield, LM_D_a03_Parts, LM_D_a03_Playfield, LM_D_a04_Parts, LM_D_a04_Playfield, LM_D_a05_Parts, LM_D_a05_Playfield, LM_D_a05_UnderPF, LM_D_a06_Parts, LM_D_a06_Playfield, LM_D_a06_RFlipU, LM_D_a10_Parts, LM_D_a10_Playfield, LM_D_a10_UnderPF, LM_D_a11_Parts, LM_D_a11_Playfield, LM_D_a11_UnderPF, LM_D_a12_Parts, LM_D_a12_Playfield, LM_D_a13_Parts, LM_D_a13_Playfield, LM_D_a14_Parts, LM_D_a14_Playfield, LM_D_a15_LFlip, LM_D_a15_LFlipU, LM_D_a15_Parts, LM_D_a15_Playfield, LM_D_a15_UnderPF, LM_D_a16_Parts, LM_D_a16_Playfield, LM_F_FL1_Asteroid1, LM_F_FL1_Asteroid2, LM_F_FL1_Asteroid3, LM_F_FL1_Asteroid4, LM_F_FL1_BR2, LM_F_FL1_BR3, LM_F_FL1_BR4, LM_F_FL1_BS2, LM_F_FL1_BS3, LM_F_FL1_BS4, LM_F_FL1_BmpBot, LM_F_FL1_BmpTopB, LM_F_FL1_DiverterPin, LM_F_FL1_Gate2, LM_F_FL1_GateR, LM_F_FL1_LArm, LM_F_FL1_LockPin, _
	LM_F_FL1_Lsling1, LM_F_FL1_Parts, LM_F_FL1_Playfield, LM_F_FL1_RFlip1, LM_F_FL1_RFlip1U, LM_F_FL1_Rails, LM_F_FL1_Ramp, LM_F_FL1_Rsling2, LM_F_FL1_Ship, LM_F_FL1_Spin, LM_F_FL1_SpinU, LM_F_FL1_TM2, LM_F_FL1_TM3, LM_F_FL1_TM4, LM_F_FL1_TM5, LM_F_FL1_UnderPF, LM_F_FL1_swC3, LM_F_FL1_swI2, LM_F_FL1_swR1, LM_F_FL1_swR2, LM_F_FL2_Asteroid1, LM_F_FL2_Asteroid2, LM_F_FL2_Asteroid3, LM_F_FL2_Asteroid4, LM_F_FL2_BR2, LM_F_FL2_BR3, LM_F_FL2_BR4, LM_F_FL2_BS2, LM_F_FL2_BS3, LM_F_FL2_BS4, LM_F_FL2_BmpBot, LM_F_FL2_BmpTopB, LM_F_FL2_DiverterPin, LM_F_FL2_GateL, LM_F_FL2_GateR, LM_F_FL2_LockPin, LM_F_FL2_Parts, LM_F_FL2_Playfield, LM_F_FL2_Ramp, LM_F_FL2_Ship, LM_F_FL2_Spin, LM_F_FL2_SpinU, LM_F_FL2_SpinWire, LM_F_FL2_TM2, LM_F_FL2_TM3, LM_F_FL2_TM4, LM_F_FL2_UnderPF, LM_F_FL2_swC1, LM_F_FL2_swC2, LM_F_FL2_swC3, LM_F_FL2_swI1, LM_F_FL2_swI2, LM_F_FL2_swL1, LM_F_FL2_swL2, LM_F_FL2_swR2, LM_F_FL3_Asteroid1, LM_F_FL3_Asteroid2, LM_F_FL3_Asteroid3, LM_F_FL3_Asteroid4, LM_F_FL3_BR2, LM_F_FL3_BR3, LM_F_FL3_BR4, LM_F_FL3_BS2, _
	LM_F_FL3_BS3, LM_F_FL3_BS4, LM_F_FL3_BmpBot, LM_F_FL3_BmpTopB, LM_F_FL3_DiverterPin, LM_F_FL3_GateL, LM_F_FL3_GateR, LM_F_FL3_LockPin, LM_F_FL3_Parts, LM_F_FL3_Playfield, LM_F_FL3_Ramp, LM_F_FL3_Ship, LM_F_FL3_Spin, LM_F_FL3_SpinU, LM_F_FL3_SpinWire, LM_F_FL3_TM3, LM_F_FL3_TM4, LM_F_FL3_UnderPF, LM_F_FL3_swC1, LM_F_FL3_swC2, LM_F_FL3_swC3, LM_F_FL3_swI1, LM_F_FL3_swI2, LM_F_FL3_swL1, LM_F_FL3_swL2, LM_F_FL3_swR1, LM_F_FL3_swR2, LM_F_FL4_Asteroid1, LM_F_FL4_Asteroid2, LM_F_FL4_Asteroid3, LM_F_FL4_Asteroid4, LM_F_FL4_BmpTopB, LM_F_FL4_GateR, LM_F_FL4_Parts, LM_F_FL4_Playfield, LM_F_FL4_RFlip1, LM_F_FL4_RFlip1U, LM_F_FL4_Ramp, LM_F_FL4_Spin, LM_F_FL4_SpinU, LM_F_FL4_TM2, LM_F_FL4_TM3, LM_F_FL4_TM4, LM_F_FL4_UnderPF, LM_F_FL4_swC1, LM_F_FL4_swC2, LM_F_FL4_swC3, LM_F_FL5_BR1, LM_F_FL5_BR4, LM_F_FL5_LArm, LM_F_FL5_LFlip, LM_F_FL5_LFlipU, LM_F_FL5_Lsling1, LM_F_FL5_Lsling2, LM_F_FL5_Parts, LM_F_FL5_Playfield, LM_F_FL5_RArm, LM_F_FL5_RFlip, LM_F_FL5_RFlipU, LM_F_FL5_Rsling1, LM_F_FL5_Rsling2, LM_F_FL5_TM1, _
	LM_F_FL5_TrustPost, LM_F_FL5_UnderPF, LM_F_FL5_swLB1, LM_F_FL5_swLI, LM_F_FL5_swLO, LM_F_FL5_swRI, LM_F_FL6_BR1, LM_F_FL6_BS1, LM_F_FL6_LArm, LM_F_FL6_LFlip, LM_F_FL6_LFlipU, LM_F_FL6_Lsling1, LM_F_FL6_Lsling2, LM_F_FL6_Parts, LM_F_FL6_Playfield, LM_F_FL6_RArm, LM_F_FL6_RFlip, LM_F_FL6_RFlipU, LM_F_FL6_Ramp, LM_F_FL6_Rsling1, LM_F_FL6_Rsling2, LM_F_FL6_TS2, LM_F_FL6_TS3, LM_F_FL6_TS4, LM_F_FL6_TrustPost, LM_F_FL6_UnderPF, LM_F_FL6_swC1, LM_F_FL6_swRI, LM_F_FL6_swRO, LM_F_FL7_Asteroid1, LM_F_FL7_Asteroid2, LM_F_FL7_Asteroid3, LM_F_FL7_Asteroid4, LM_F_FL7_BR2, LM_F_FL7_BR3, LM_F_FL7_BR4, LM_F_FL7_BS2, LM_F_FL7_BS3, LM_F_FL7_BS4, LM_F_FL7_BmpBot, LM_F_FL7_BmpTopB, LM_F_FL7_DiverterPin, LM_F_FL7_GateL, LM_F_FL7_GateR, LM_F_FL7_LockPin, LM_F_FL7_Parts, LM_F_FL7_Playfield, LM_F_FL7_Ramp, LM_F_FL7_Ship, LM_F_FL7_Spin, LM_F_FL7_SpinU, LM_F_FL7_SpinWire, LM_F_FL7_TM2, LM_F_FL7_TM3, LM_F_FL7_TM4, LM_F_FL7_TM5, LM_F_FL7_UnderPF, LM_F_FL7_swC1, LM_F_FL7_swC2, LM_F_FL7_swC3, LM_F_FL7_swI1, LM_F_FL7_swI2, LM_F_FL7_swL1, _
	LM_F_FL7_swL2, LM_F_FL7_swR1, LM_F_FL7_swR2, LM_GI_gi01_LArm, LM_GI_gi01_LFlip, LM_GI_gi01_LFlipU, LM_GI_gi01_Lsling1, LM_GI_gi01_Lsling2, LM_GI_gi01_Parts, LM_GI_gi01_Playfield, LM_GI_gi01_RFlip, LM_GI_gi01_RFlipU, LM_GI_gi01_UnderPF, LM_GI_gi01_swLI, LM_GI_gi01_swLO, LM_GI_gi02_LArm, LM_GI_gi02_LFlip, LM_GI_gi02_LFlipU, LM_GI_gi02_Parts, LM_GI_gi02_Playfield, LM_GI_gi02_RFlip, LM_GI_gi02_RFlipU, LM_GI_gi02_UnderPF, LM_GI_gi02_swLI, LM_GI_gi02_swLO, LM_GI_gi03_LArm, LM_GI_gi03_LFlip, LM_GI_gi03_LFlipU, LM_GI_gi03_Lsling1, LM_GI_gi03_Lsling2, LM_GI_gi03_Parts, LM_GI_gi03_Playfield, LM_GI_gi03_RFlip, LM_GI_gi03_RFlipU, LM_GI_gi03_UnderPF, LM_GI_gi03_swLI, LM_GI_gi03_swLO, LM_GI_gi04_BmpTopR, LM_GI_gi04_LArm, LM_GI_gi04_LFlip, LM_GI_gi04_LFlipU, LM_GI_gi04_Lsling1, LM_GI_gi04_Lsling2, LM_GI_gi04_Parts, LM_GI_gi04_Playfield, LM_GI_gi04_UnderPF, LM_GI_gi04_swLI, LM_GI_gi04_swLO, LM_GI_gi05_Parts, LM_GI_gi05_Playfield, LM_GI_gi05_RArm, LM_GI_gi05_RFlip, LM_GI_gi05_RFlipU, LM_GI_gi05_Rsling1, LM_GI_gi05_Rsling2, _
	LM_GI_gi05_UnderPF, LM_GI_gi05_swRI, LM_GI_gi06_Parts, LM_GI_gi06_Playfield, LM_GI_gi06_RArm, LM_GI_gi06_RFlip, LM_GI_gi06_RFlipU, LM_GI_gi06_Rsling1, LM_GI_gi06_UnderPF, LM_GI_gi06_swRI, LM_GI_gi07_LFlip, LM_GI_gi07_LFlipU, LM_GI_gi07_Lsling2, LM_GI_gi07_Parts, LM_GI_gi07_Playfield, LM_GI_gi07_RArm, LM_GI_gi07_RFlip, LM_GI_gi07_RFlipU, LM_GI_gi07_Rsling1, LM_GI_gi07_Rsling2, LM_GI_gi07_UnderPF, LM_GI_gi07_swRI, LM_GI_gi07_swRO, LM_GI_gi08_Parts, LM_GI_gi08_Playfield, LM_GI_gi08_RArm, LM_GI_gi08_RFlip, LM_GI_gi08_RFlipU, LM_GI_gi08_Rsling1, LM_GI_gi08_Rsling2, LM_GI_gi08_UnderPF, LM_GI_gi08_swRI, LM_GI_gi09_Parts, LM_GI_gi09_Playfield, LM_GI_gi09_swLI, LM_GI_gi10_Gate2, LM_GI_gi10_Parts, LM_GI_gi10_Playfield, LM_GI_gi10_RFlip1U, LM_GI_gi10_TS1, LM_GI_gi10_TS2, LM_GI_gi10_TS3, LM_GI_gi10_TS4, LM_GI_gi10_UnderPF, LM_GI_gi11_Parts, LM_GI_gi11_Playfield, LM_GI_gi12_Parts, LM_GI_gi12_Playfield, LM_GI_gi13_BR4, LM_GI_gi13_BS2, LM_GI_gi13_BS4, LM_GI_gi13_BmpBot, LM_GI_gi13_BmpTopB, LM_GI_gi13_GateR, _
	LM_GI_gi13_Parts, LM_GI_gi13_Playfield, LM_GI_gi13_RFlip1U, LM_GI_gi13_TM4, LM_GI_gi13_TM5, LM_GI_gi13_UnderPF, LM_GI_gi14_Gate2, LM_GI_gi14_LockPin, LM_GI_gi14_Parts, LM_GI_gi14_Playfield, LM_GI_gi14_RFlip1, LM_GI_gi14_RFlip1U, LM_GI_gi14_TM5, LM_GI_gi15_LockPin, LM_GI_gi15_Parts, LM_GI_gi15_Playfield, LM_GI_gi15_RFlip1, LM_GI_gi15_RFlip1U, LM_GI_gi15_UnderPF, LM_GI_gi16_Asteroid1, LM_GI_gi16_Asteroid2, LM_GI_gi16_Asteroid3, LM_GI_gi16_Asteroid4, LM_GI_gi16_BR2, LM_GI_gi16_BR3, LM_GI_gi16_BR4, LM_GI_gi16_BS2, LM_GI_gi16_BS3, LM_GI_gi16_BS4, LM_GI_gi16_BmpBot, LM_GI_gi16_BmpTopB, LM_GI_gi16_GateR, LM_GI_gi16_Parts, LM_GI_gi16_Playfield, LM_GI_gi16_Ramp, LM_GI_gi16_TM4, LM_GI_gi16_UnderPF, LM_GI_gi16_swC3, LM_GI_gi17_BR2, LM_GI_gi17_Parts, LM_GI_gi17_Playfield, LM_GI_gi18_Parts, LM_GI_gi18_Playfield, LM_GI_gi19_LockPin, LM_GI_gi19_Parts, LM_GI_gi19_Playfield, LM_GI_gi19_RFlip1, LM_GI_gi19_RFlip1U, LM_GI_gi19_TM5, LM_GI_gi19_UnderPF, LM_GI_gi20_Asteroid1, LM_GI_gi20_Asteroid2, LM_GI_gi20_Asteroid3, _
	LM_GI_gi20_Asteroid4, LM_GI_gi20_GateL, LM_GI_gi20_Parts, LM_GI_gi20_Playfield, LM_GI_gi20_Ramp, LM_GI_gi20_Spin, LM_GI_gi20_SpinU, LM_GI_gi20_SpinWire, LM_GI_gi20_TM2, LM_GI_gi20_UnderPF, LM_GI_gi20_swC1, LM_GI_gi20_swI1, LM_GI_gi20_swL1, LM_GI_gi20_swL2, LM_GI_gi21_Asteroid1, LM_GI_gi21_Asteroid2, LM_GI_gi21_Asteroid3, LM_GI_gi21_Asteroid4, LM_GI_gi21_GateL, LM_GI_gi21_Parts, LM_GI_gi21_Playfield, LM_GI_gi21_Ramp, LM_GI_gi21_Spin, LM_GI_gi21_SpinU, LM_GI_gi21_SpinWire, LM_GI_gi21_TM2, LM_GI_gi21_swL1, LM_GI_gi21_swL2, LM_GI_giapron_LFlip, LM_GI_giapron_LFlipU, LM_GI_giapron_Lsling1, LM_GI_giapron_Lsling2, LM_GI_giapron_Parts, LM_GI_giapron_Playfield, LM_GI_giapron_RFlip, LM_GI_giapron_RFlipU, LM_GI_giapron_Rsling1, LM_GI_giapron_Rsling2, LM_GI_giapron_TrustPost, LM_L_LB1_BR1, LM_L_LB1_BS1, LM_L_LB1_BmpBot, LM_L_LB1_BmpTopR, LM_L_LB1_LockPin, LM_L_LB1_Parts, LM_L_LB1_Playfield, LM_L_LB1_RFlip1, LM_L_LB1_RFlip1U, LM_L_LB1_Ramp, LM_L_LB1_Rsling1, LM_L_LB1_Rsling2, LM_L_LB1_Ship, LM_L_LB1_TM1, LM_L_LB1_TM2, _
	LM_L_LB1_TMet1, LM_L_LB1_TS2, LM_L_LB1_UnderPF, LM_L_LB1_swLB1, LM_L_LB1_swLB2, LM_L_LB2_Asteroid1, LM_L_LB2_Asteroid2, LM_L_LB2_Asteroid3, LM_L_LB2_Asteroid4, LM_L_LB2_BR2, LM_L_LB2_BR3, LM_L_LB2_BR4, LM_L_LB2_BS2, LM_L_LB2_BS3, LM_L_LB2_BS4, LM_L_LB2_BmpBot, LM_L_LB2_BmpTopB, LM_L_LB2_DiverterPin, LM_L_LB2_Parts, LM_L_LB2_Playfield, LM_L_LB2_swR2, LM_L_LB3_Asteroid1, LM_L_LB3_Asteroid2, LM_L_LB3_Asteroid3, LM_L_LB3_Asteroid4, LM_L_LB3_BR2, LM_L_LB3_BR3, LM_L_LB3_BR4, LM_L_LB3_BS2, LM_L_LB3_BS3, LM_L_LB3_BS4, LM_L_LB3_BmpBot, LM_L_LB3_BmpTopB, LM_L_LB3_DiverterPin, LM_L_LB3_Parts, LM_L_LB3_Playfield, LM_L_LB3_Spin, LM_L_LB3_TM3, LM_L_LB3_TM4, LM_L_LB3_UnderPF, LM_L_LB3_swC3, LM_L_LB3_swI2, LM_L_LB4_Asteroid1, LM_L_LB4_Asteroid2, LM_L_LB4_Asteroid3, LM_L_LB4_Asteroid4, LM_L_LB4_BR2, LM_L_LB4_BR3, LM_L_LB4_BR4, LM_L_LB4_BS2, LM_L_LB4_BS3, LM_L_LB4_BS4, LM_L_LB4_BmpBot, LM_L_LB4_BmpTopB, LM_L_LB4_GateR, LM_L_LB4_Parts, LM_L_LB4_Playfield, LM_L_LB4_TM4, LM_L_LB4_UnderPF, LM_L_LB4_swC3, LM_L_LB4_swR1, _
	LM_L_LC1_LFlip, LM_L_LC1_LFlipU, LM_L_LC1_Parts, LM_L_LC1_Playfield, LM_L_LC1_UnderPF, LM_L_LC2_LFlip, LM_L_LC2_LFlipU, LM_L_LC2_Parts, LM_L_LC2_Playfield, LM_L_LC2_UnderPF, LM_L_LC3_LFlipU, LM_L_LC3_Playfield, LM_L_LC3_UnderPF, LM_L_LC4_LFlipU, LM_L_LC4_Playfield, LM_L_LC4_UnderPF, LM_L_LC5_Playfield, LM_L_LC5_RFlipU, LM_L_LC5_UnderPF, LM_L_LC6_Playfield, LM_L_LC6_RFlipU, LM_L_LC6_UnderPF, LM_L_LC7_Playfield, LM_L_LC7_RFlipU, LM_L_LC7_UnderPF, LM_L_LC8_Parts, LM_L_LC8_Playfield, LM_L_LC8_RFlip, LM_L_LC8_RFlipU, LM_L_LC8_UnderPF, LM_L_LCC1_Parts, LM_L_LCC1_Playfield, LM_L_LCC1_Ramp, LM_L_LCC1_UnderPF, LM_L_LCC2_Parts, LM_L_LCC2_Playfield, LM_L_LCC2_UnderPF, LM_L_LCC3_Parts, LM_L_LCC3_Playfield, LM_L_LCC3_UnderPF, LM_L_LCR1_Lsling1, LM_L_LCR1_Lsling2, LM_L_LCR1_Parts, LM_L_LCR1_Playfield, LM_L_LCR1_UnderPF, LM_L_LCR2_Lsling1, LM_L_LCR2_Lsling2, LM_L_LCR2_Parts, LM_L_LCR2_Playfield, LM_L_LCR2_UnderPF, LM_L_LCWiz_Parts, LM_L_LCWiz_Playfield, LM_L_LCWiz_UnderPF, LM_L_LEBR_Parts, LM_L_LEBR_Playfield, _
	LM_L_LEBR_TM4, LM_L_LEBR_UnderPF, LM_L_LF1_Parts, LM_L_LF1_Playfield, LM_L_LF1_UnderPF, LM_L_LF1_swR1, LM_L_LF2_Parts, LM_L_LF2_Playfield, LM_L_LF2_TM5, LM_L_LF2_UnderPF, LM_L_LF2_swR1, LM_L_LF3_Parts, LM_L_LF3_Playfield, LM_L_LF3_RFlip1U, LM_L_LF3_TM5, LM_L_LF3_UnderPF, LM_L_LH1_LFlip, LM_L_LH1_LFlipU, LM_L_LH1_Parts, LM_L_LH1_Playfield, LM_L_LH1_UnderPF, LM_L_LH2_LFlip, LM_L_LH2_LFlipU, LM_L_LH2_Playfield, LM_L_LH2_UnderPF, LM_L_LH3_LFlip, LM_L_LH3_LFlipU, LM_L_LH3_Playfield, LM_L_LH3_UnderPF, LM_L_LH4_LFlip, LM_L_LH4_LFlipU, LM_L_LH4_Playfield, LM_L_LH4_UnderPF, LM_L_LH5_LFlipU, LM_L_LH5_Playfield, LM_L_LH5_RFlipU, LM_L_LH5_UnderPF, LM_L_LH6_Playfield, LM_L_LH6_RFlipU, LM_L_LH6_UnderPF, LM_L_LH7_Playfield, LM_L_LH7_RFlip, LM_L_LH7_RFlipU, LM_L_LH7_UnderPF, LM_L_LH8_Playfield, LM_L_LH8_RFlip, LM_L_LH8_RFlipU, LM_L_LH8_UnderPF, LM_L_LH9_Parts, LM_L_LH9_Playfield, LM_L_LH9_RFlip, LM_L_LH9_RFlipU, LM_L_LH9_UnderPF, LM_L_LLI_Parts, LM_L_LLI_Playfield, LM_L_LLI_UnderPF, LM_L_LLI_swLI, LM_L_LLO_Parts, _
	LM_L_LLO_Playfield, LM_L_LLO_UnderPF, LM_L_LLO_swLO, LM_L_LLWiz_Parts, LM_L_LLWiz_Playfield, LM_L_LLWiz_UnderPF, LM_L_LM1_Parts, LM_L_LM1_Playfield, LM_L_LM1_TM1, LM_L_LM1_UnderPF, LM_L_LM2_Parts, LM_L_LM2_Playfield, LM_L_LM2_TM2, LM_L_LM2_UnderPF, LM_L_LM3_Asteroid1, LM_L_LM3_Asteroid2, LM_L_LM3_Asteroid3, LM_L_LM3_Asteroid4, LM_L_LM3_Playfield, LM_L_LM3_TM3, LM_L_LM3_UnderPF, LM_L_LM4_Parts, LM_L_LM4_Playfield, LM_L_LM4_TM4, LM_L_LM4_UnderPF, LM_L_LM5_Parts, LM_L_LM5_Playfield, LM_L_LM5_TM5, LM_L_LM5_UnderPF, LM_L_LMLR_Parts, LM_L_LMLR_Playfield, LM_L_LMLR_TM5, LM_L_LMLR_UnderPF, LM_L_LMR_GateR, LM_L_LMR_Parts, LM_L_LMR_Playfield, LM_L_LMR_TM4, LM_L_LMR_UnderPF, LM_L_LMR1_Parts, LM_L_LMR1_Playfield, LM_L_LMR1_Rsling1, LM_L_LMR1_Rsling2, LM_L_LMR1_UnderPF, LM_L_LMR2_Parts, LM_L_LMR2_Playfield, LM_L_LMR2_Rsling1, LM_L_LMR2_Rsling2, LM_L_LMR2_UnderPF, LM_L_LMet1_BR1, LM_L_LMet1_BS1, LM_L_LMet1_BmpTopR, LM_L_LMet1_Parts, LM_L_LMet1_Playfield, LM_L_LMet1_TMet1, LM_L_LMet1_UnderPF, LM_L_LMet2_BmpTopR, _
	LM_L_LMet2_Parts, LM_L_LMet2_Playfield, LM_L_LMet2_TMet2, LM_L_LMet2_UnderPF, LM_L_LMet3_Parts, LM_L_LMet3_Playfield, LM_L_LMet3_TMet3, LM_L_LMet3_UnderPF, LM_L_LMet4_Parts, LM_L_LMet4_Playfield, LM_L_LMet4_TMet4, LM_L_LMet4_UnderPF, LM_L_LPC1_Asteroid1, LM_L_LPC1_Asteroid4, LM_L_LPC1_GateL, LM_L_LPC1_Parts, LM_L_LPC1_Playfield, LM_L_LPC1_Ramp, LM_L_LPC1_SpinU, LM_L_LPC1_TM2, LM_L_LPC1_UnderPF, LM_L_LPC2_Parts, LM_L_LPC2_Playfield, LM_L_LPC2_TM2, LM_L_LPC2_UnderPF, LM_L_LPC3_Parts, LM_L_LPC3_Playfield, LM_L_LPC3_UnderPF, LM_L_LPC4_Asteroid1, LM_L_LPC4_Asteroid2, LM_L_LPC4_Asteroid3, LM_L_LPC4_Asteroid4, LM_L_LPC4_Parts, LM_L_LPC4_Playfield, LM_L_LPC4_Ramp, LM_L_LPC4_TM3, LM_L_LPC4_UnderPF, LM_L_LPC4_swC1, LM_L_LPC5_Asteroid1, LM_L_LPC5_Asteroid2, LM_L_LPC5_Asteroid3, LM_L_LPC5_Asteroid4, LM_L_LPC5_Parts, LM_L_LPC5_Playfield, LM_L_LPC5_TM3, LM_L_LPC5_TM4, LM_L_LPC5_UnderPF, LM_L_LPC5_swC3, LM_L_LPF_Asteroid1, LM_L_LPF_Asteroid2, LM_L_LPF_Asteroid3, LM_L_LPF_Asteroid4, LM_L_LPF_Playfield, LM_L_LPF_TM3, _
	LM_L_LPF_UnderPF, LM_L_LPR1_Parts, LM_L_LPR1_Playfield, LM_L_LPR1_UnderPF, LM_L_LPR2_Parts, LM_L_LPR2_Playfield, LM_L_LPR2_UnderPF, LM_L_LPR3_Parts, LM_L_LPR3_Playfield, LM_L_LPR3_UnderPF, LM_L_LPR4_LFlip, LM_L_LPR4_LFlipU, LM_L_LPR4_Parts, LM_L_LPR4_Playfield, LM_L_LPR4_UnderPF, LM_L_LPR5_LFlipU, LM_L_LPR5_Parts, LM_L_LPR5_Playfield, LM_L_LPR5_RFlipU, LM_L_LPR5_UnderPF, LM_L_LPR6_Parts, LM_L_LPR6_Playfield, LM_L_LPR6_RFlipU, LM_L_LPR6_UnderPF, LM_L_LRI_Parts, LM_L_LRI_Playfield, LM_L_LRI_UnderPF, LM_L_LRI_swRI, LM_L_LRO_Parts, LM_L_LRO_Playfield, LM_L_LRO_UnderPF, LM_L_LRO_swRO, LM_L_LS1_BmpTopR, LM_L_LS1_Parts, LM_L_LS1_Playfield, LM_L_LS1_TM1, LM_L_LS1_UnderPF, LM_L_LS1_swLB1, LM_L_LS2_BmpTopR, LM_L_LS2_Parts, LM_L_LS2_Playfield, LM_L_LS2_UnderPF, LM_L_LS3_Parts, LM_L_LS3_Playfield, LM_L_LS3_Ship, LM_L_LS3_TMet2, LM_L_LS3_UnderPF, LM_L_LS4_Parts, LM_L_LS4_Playfield, LM_L_LS4_UnderPF, LM_L_LS5_Parts, LM_L_LS5_Playfield, LM_L_LS5_RFlip1U, LM_L_LS5_UnderPF, LM_L_LS6_Parts, LM_L_LS6_Playfield, LM_L_LS6_RFlip1, _
	LM_L_LS6_RFlip1U, LM_L_LS6_UnderPF, LM_L_LSA_LFlip, LM_L_LSA_LFlipU, LM_L_LSA_Playfield, LM_L_LSA_RFlip, LM_L_LSA_RFlipU, LM_L_LSA_TrustPost, LM_L_LSA_UnderPF, LM_L_LSC1_Parts, LM_L_LSC1_Playfield, LM_L_LSC1_TS1, LM_L_LSC1_TS2, LM_L_LSC1_UnderPF, LM_L_LSC2_Parts, LM_L_LSC2_Playfield, LM_L_LSC2_TS1, LM_L_LSC2_TS2, LM_L_LSC2_TS3, LM_L_LSC2_UnderPF, LM_L_LSC3_Parts, LM_L_LSC3_Playfield, LM_L_LSC3_TS2, LM_L_LSC3_TS3, LM_L_LSC3_TS4, LM_L_LSC3_UnderPF, LM_L_LSC4_Parts, LM_L_LSC4_Playfield, LM_L_LSC4_TS4, LM_L_LSC4_UnderPF, LM_L_LSL_Parts, LM_L_LSL_Playfield, LM_L_LSL_UnderPF, LM_L_LSL_swLO, LM_L_LSR_Parts, LM_L_LSR_Playfield, LM_L_LSR_UnderPF, LM_L_LSR_swRO, LM_L_LShip_Parts, LM_L_LShip_Ship, LM_L_LSwC1_Asteroid1, LM_L_LSwC1_Asteroid2, LM_L_LSwC1_Asteroid3, LM_L_LSwC1_Asteroid4, LM_L_LSwC1_Parts, LM_L_LSwC1_Playfield, LM_L_LSwC1_UnderPF, LM_L_LSwC1_swC1, LM_L_LSwC1_swC2, LM_L_LSwC2_Asteroid1, LM_L_LSwC2_Asteroid2, LM_L_LSwC2_Asteroid3, LM_L_LSwC2_Asteroid4, LM_L_LSwC2_BmpTopB, LM_L_LSwC2_Parts, _
	LM_L_LSwC2_Playfield, LM_L_LSwC2_TM3, LM_L_LSwC2_UnderPF, LM_L_LSwC2_swC2, LM_L_LSwC3_Asteroid1, LM_L_LSwC3_Asteroid2, LM_L_LSwC3_Asteroid3, LM_L_LSwC3_Asteroid4, LM_L_LSwC3_Parts, LM_L_LSwC3_Playfield, LM_L_LSwC3_UnderPF, LM_L_LSwC3_swC2, LM_L_LSwC3_swC3, LM_L_LSwL1_BR1, LM_L_LSwL1_BS1, LM_L_LSwL1_BmpTopR, LM_L_LSwL1_Parts, LM_L_LSwL1_Playfield, LM_L_LSwL1_TM1, LM_L_LSwL1_UnderPF, LM_L_LSwL1_swLB1, LM_L_LSwL2_BS1, LM_L_LSwL2_BmpBot, LM_L_LSwL2_BmpTopR, LM_L_LSwL2_Parts, LM_L_LSwL2_Playfield, LM_L_LSwL2_UnderPF, LM_L_LSwL2_swLB2, LM_L_LTW1_Parts, LM_L_LTW1_Playfield, LM_L_LTW1_Ramp, LM_L_LTW1_UnderPF, LM_L_LTW2_Parts, LM_L_LTW2_Playfield, LM_L_LTW2_Ramp, LM_L_LTW2_UnderPF, LM_L_LTW3_Parts, LM_L_LTW3_Playfield, LM_L_LTW3_UnderPF, LM_L_LTW4_Parts, LM_L_LTW4_Playfield, LM_L_LTW4_UnderPF, LM_L_LW1_Parts, LM_L_LW1_Playfield, LM_L_LW1_UnderPF, LM_L_LW2_Parts, LM_L_LW2_Playfield, LM_L_LW2_UnderPF, LM_L_LW3_Parts, LM_L_LW3_Playfield, LM_L_LW3_UnderPF, LM_L_LW4_Parts, LM_L_LW4_Playfield, LM_L_LW4_UnderPF, _
	LM_L_LW5_Parts, LM_L_LW5_Playfield, LM_L_LW5_UnderPF, LM_L_LW6_BmpTopR, LM_L_LW6_Parts, LM_L_LW6_Playfield, LM_L_LW6_UnderPF, LM_L_LW7_BmpTopR, LM_L_LW7_Parts, LM_L_LW7_Playfield, LM_L_LW7_UnderPF, LM_L_LW8_BmpTopR, LM_L_LW8_Parts, LM_L_LW8_Playfield, LM_L_LW8_UnderPF, LM_L_LW9_Parts, LM_L_LW9_Playfield, LM_L_LW9_UnderPF, LM_L_LWiz_Parts, LM_L_LWiz_Playfield, LM_L_LWiz_UnderPF, LM_L_LX_Parts, LM_L_LX_Playfield, LM_L_LX_UnderPF, LM_L_Lspot1_Asteroid1, LM_L_Lspot1_Asteroid2, LM_L_Lspot1_Asteroid3, LM_L_Lspot1_Asteroid4, LM_L_Lspot1_BR4, LM_L_Lspot1_BS4, LM_L_Lspot1_BmpTopB, LM_L_Lspot1_Parts, LM_L_Lspot1_Playfield, LM_L_Lspot1_Ramp, LM_L_Lspot1_Spin, LM_L_Lspot1_SpinU, LM_L_Lspot1_SpinWire, LM_L_Lspot1_TM3, LM_L_Lspot1_TM4, LM_L_Lspot1_UnderPF, LM_L_Lspot1_swC1, LM_L_Lspot1_swC2, LM_L_Lspot1_swC3, LM_L_Lspot1_swI2, LM_L_Lspot2_GateL, LM_L_Lspot2_LArm, LM_L_Lspot2_LFlip, LM_L_Lspot2_LFlipU, LM_L_Lspot2_LockPin, LM_L_Lspot2_Lsling1, LM_L_Lspot2_Lsling2, LM_L_Lspot2_Parts, LM_L_Lspot2_Playfield, LM_L_Lspot2_RArm, _
	LM_L_Lspot2_RFlip, LM_L_Lspot2_RFlipU, LM_L_Lspot2_Ramp, LM_L_Lspot2_Rsling1, LM_L_Lspot2_Rsling2, LM_L_Lspot2_UnderPF, LM_L_Lspot2_swLB1, LM_L_Lspot2_swLO, LM_Stars_Parts, LM_Stars_Ramp)
Dim BG_All: BG_All=Array(BM_Asteroid1, BM_BR1, BM_BR2, BM_BR3, BM_BR4, BM_BS1, BM_BS2, BM_BS3, BM_BS4, BM_BmpBot, BM_BmpTopB, BM_BmpTopR, BM_DiverterPin, BM_Gate2, BM_GateL, BM_GateR, BM_LArm, BM_LFlip, BM_LFlipU, BM_LockPin, BM_Lsling1, BM_Lsling2, BM_Parts, BM_Playfield, BM_RArm, BM_RFlip, BM_RFlip1, BM_RFlip1U, BM_RFlipU, BM_Rails, BM_Ramp, BM_Rsling1, BM_Rsling2, BM_Ship, BM_Spin, BM_SpinU, BM_SpinWire, BM_TM1, BM_TM2, BM_TM3, BM_TM4, BM_TM5, BM_TMet1, BM_TMet2, BM_TMet3, BM_TMet4, BM_TS1, BM_TS2, BM_TS3, BM_TS4, BM_TrustPost, BM_UnderPF, BM_swC1, BM_swC2, BM_swC3, BM_swI1, BM_swI2, BM_swL1, BM_swL2, BM_swLB1, BM_swLB2, BM_swLI, BM_swLO, BM_swP1, BM_swP2, BM_swR1, BM_swR2, BM_swRI, BM_swRO, LM_D_a00_Parts, LM_D_a00_Playfield, LM_D_a00_RFlipU, LM_D_a00_UnderPF, LM_D_a01_Parts, LM_D_a01_Playfield, LM_D_a01_RFlipU, LM_D_a01_UnderPF, LM_D_a02_Parts, LM_D_a02_Playfield, LM_D_a03_Parts, LM_D_a03_Playfield, LM_D_a04_Parts, LM_D_a04_Playfield, LM_D_a05_Parts, LM_D_a05_Playfield, LM_D_a05_UnderPF, LM_D_a06_Parts, _
	LM_D_a06_Playfield, LM_D_a06_RFlipU, LM_D_a10_Parts, LM_D_a10_Playfield, LM_D_a10_UnderPF, LM_D_a11_Parts, LM_D_a11_Playfield, LM_D_a11_UnderPF, LM_D_a12_Parts, LM_D_a12_Playfield, LM_D_a13_Parts, LM_D_a13_Playfield, LM_D_a14_Parts, LM_D_a14_Playfield, LM_D_a15_LFlip, LM_D_a15_LFlipU, LM_D_a15_Parts, LM_D_a15_Playfield, LM_D_a15_UnderPF, LM_D_a16_Parts, LM_D_a16_Playfield, LM_F_FL1_Asteroid1, LM_F_FL1_Asteroid2, LM_F_FL1_Asteroid3, LM_F_FL1_Asteroid4, LM_F_FL1_BR2, LM_F_FL1_BR3, LM_F_FL1_BR4, LM_F_FL1_BS2, LM_F_FL1_BS3, LM_F_FL1_BS4, LM_F_FL1_BmpBot, LM_F_FL1_BmpTopB, LM_F_FL1_DiverterPin, LM_F_FL1_Gate2, LM_F_FL1_GateR, LM_F_FL1_LArm, LM_F_FL1_LockPin, LM_F_FL1_Lsling1, LM_F_FL1_Parts, LM_F_FL1_Playfield, LM_F_FL1_RFlip1, LM_F_FL1_RFlip1U, LM_F_FL1_Rails, LM_F_FL1_Ramp, LM_F_FL1_Rsling2, LM_F_FL1_Ship, LM_F_FL1_Spin, LM_F_FL1_SpinU, LM_F_FL1_TM2, LM_F_FL1_TM3, LM_F_FL1_TM4, LM_F_FL1_TM5, LM_F_FL1_UnderPF, LM_F_FL1_swC3, LM_F_FL1_swI2, LM_F_FL1_swR1, LM_F_FL1_swR2, LM_F_FL2_Asteroid1, LM_F_FL2_Asteroid2, _
	LM_F_FL2_Asteroid3, LM_F_FL2_Asteroid4, LM_F_FL2_BR2, LM_F_FL2_BR3, LM_F_FL2_BR4, LM_F_FL2_BS2, LM_F_FL2_BS3, LM_F_FL2_BS4, LM_F_FL2_BmpBot, LM_F_FL2_BmpTopB, LM_F_FL2_DiverterPin, LM_F_FL2_GateL, LM_F_FL2_GateR, LM_F_FL2_LockPin, LM_F_FL2_Parts, LM_F_FL2_Playfield, LM_F_FL2_Ramp, LM_F_FL2_Ship, LM_F_FL2_Spin, LM_F_FL2_SpinU, LM_F_FL2_SpinWire, LM_F_FL2_TM2, LM_F_FL2_TM3, LM_F_FL2_TM4, LM_F_FL2_UnderPF, LM_F_FL2_swC1, LM_F_FL2_swC2, LM_F_FL2_swC3, LM_F_FL2_swI1, LM_F_FL2_swI2, LM_F_FL2_swL1, LM_F_FL2_swL2, LM_F_FL2_swR2, LM_F_FL3_Asteroid1, LM_F_FL3_Asteroid2, LM_F_FL3_Asteroid3, LM_F_FL3_Asteroid4, LM_F_FL3_BR2, LM_F_FL3_BR3, LM_F_FL3_BR4, LM_F_FL3_BS2, LM_F_FL3_BS3, LM_F_FL3_BS4, LM_F_FL3_BmpBot, LM_F_FL3_BmpTopB, LM_F_FL3_DiverterPin, LM_F_FL3_GateL, LM_F_FL3_GateR, LM_F_FL3_LockPin, LM_F_FL3_Parts, LM_F_FL3_Playfield, LM_F_FL3_Ramp, LM_F_FL3_Ship, LM_F_FL3_Spin, LM_F_FL3_SpinU, LM_F_FL3_SpinWire, LM_F_FL3_TM3, LM_F_FL3_TM4, LM_F_FL3_UnderPF, LM_F_FL3_swC1, LM_F_FL3_swC2, LM_F_FL3_swC3, LM_F_FL3_swI1, _
	LM_F_FL3_swI2, LM_F_FL3_swL1, LM_F_FL3_swL2, LM_F_FL3_swR1, LM_F_FL3_swR2, LM_F_FL4_Asteroid1, LM_F_FL4_Asteroid2, LM_F_FL4_Asteroid3, LM_F_FL4_Asteroid4, LM_F_FL4_BmpTopB, LM_F_FL4_GateR, LM_F_FL4_Parts, LM_F_FL4_Playfield, LM_F_FL4_RFlip1, LM_F_FL4_RFlip1U, LM_F_FL4_Ramp, LM_F_FL4_Spin, LM_F_FL4_SpinU, LM_F_FL4_TM2, LM_F_FL4_TM3, LM_F_FL4_TM4, LM_F_FL4_UnderPF, LM_F_FL4_swC1, LM_F_FL4_swC2, LM_F_FL4_swC3, LM_F_FL5_BR1, LM_F_FL5_BR4, LM_F_FL5_LArm, LM_F_FL5_LFlip, LM_F_FL5_LFlipU, LM_F_FL5_Lsling1, LM_F_FL5_Lsling2, LM_F_FL5_Parts, LM_F_FL5_Playfield, LM_F_FL5_RArm, LM_F_FL5_RFlip, LM_F_FL5_RFlipU, LM_F_FL5_Rsling1, LM_F_FL5_Rsling2, LM_F_FL5_TM1, LM_F_FL5_TrustPost, LM_F_FL5_UnderPF, LM_F_FL5_swLB1, LM_F_FL5_swLI, LM_F_FL5_swLO, LM_F_FL5_swRI, LM_F_FL6_BR1, LM_F_FL6_BS1, LM_F_FL6_LArm, LM_F_FL6_LFlip, LM_F_FL6_LFlipU, LM_F_FL6_Lsling1, LM_F_FL6_Lsling2, LM_F_FL6_Parts, LM_F_FL6_Playfield, LM_F_FL6_RArm, LM_F_FL6_RFlip, LM_F_FL6_RFlipU, LM_F_FL6_Ramp, LM_F_FL6_Rsling1, LM_F_FL6_Rsling2, LM_F_FL6_TS2, _
	LM_F_FL6_TS3, LM_F_FL6_TS4, LM_F_FL6_TrustPost, LM_F_FL6_UnderPF, LM_F_FL6_swC1, LM_F_FL6_swRI, LM_F_FL6_swRO, LM_F_FL7_Asteroid1, LM_F_FL7_Asteroid2, LM_F_FL7_Asteroid3, LM_F_FL7_Asteroid4, LM_F_FL7_BR2, LM_F_FL7_BR3, LM_F_FL7_BR4, LM_F_FL7_BS2, LM_F_FL7_BS3, LM_F_FL7_BS4, LM_F_FL7_BmpBot, LM_F_FL7_BmpTopB, LM_F_FL7_DiverterPin, LM_F_FL7_GateL, LM_F_FL7_GateR, LM_F_FL7_LockPin, LM_F_FL7_Parts, LM_F_FL7_Playfield, LM_F_FL7_Ramp, LM_F_FL7_Ship, LM_F_FL7_Spin, LM_F_FL7_SpinU, LM_F_FL7_SpinWire, LM_F_FL7_TM2, LM_F_FL7_TM3, LM_F_FL7_TM4, LM_F_FL7_TM5, LM_F_FL7_UnderPF, LM_F_FL7_swC1, LM_F_FL7_swC2, LM_F_FL7_swC3, LM_F_FL7_swI1, LM_F_FL7_swI2, LM_F_FL7_swL1, LM_F_FL7_swL2, LM_F_FL7_swR1, LM_F_FL7_swR2, LM_GI_gi01_LArm, LM_GI_gi01_LFlip, LM_GI_gi01_LFlipU, LM_GI_gi01_Lsling1, LM_GI_gi01_Lsling2, LM_GI_gi01_Parts, LM_GI_gi01_Playfield, LM_GI_gi01_RFlip, LM_GI_gi01_RFlipU, LM_GI_gi01_UnderPF, LM_GI_gi01_swLI, LM_GI_gi01_swLO, LM_GI_gi02_LArm, LM_GI_gi02_LFlip, LM_GI_gi02_LFlipU, LM_GI_gi02_Parts, _
	LM_GI_gi02_Playfield, LM_GI_gi02_RFlip, LM_GI_gi02_RFlipU, LM_GI_gi02_UnderPF, LM_GI_gi02_swLI, LM_GI_gi02_swLO, LM_GI_gi03_LArm, LM_GI_gi03_LFlip, LM_GI_gi03_LFlipU, LM_GI_gi03_Lsling1, LM_GI_gi03_Lsling2, LM_GI_gi03_Parts, LM_GI_gi03_Playfield, LM_GI_gi03_RFlip, LM_GI_gi03_RFlipU, LM_GI_gi03_UnderPF, LM_GI_gi03_swLI, LM_GI_gi03_swLO, LM_GI_gi04_BmpTopR, LM_GI_gi04_LArm, LM_GI_gi04_LFlip, LM_GI_gi04_LFlipU, LM_GI_gi04_Lsling1, LM_GI_gi04_Lsling2, LM_GI_gi04_Parts, LM_GI_gi04_Playfield, LM_GI_gi04_UnderPF, LM_GI_gi04_swLI, LM_GI_gi04_swLO, LM_GI_gi05_Parts, LM_GI_gi05_Playfield, LM_GI_gi05_RArm, LM_GI_gi05_RFlip, LM_GI_gi05_RFlipU, LM_GI_gi05_Rsling1, LM_GI_gi05_Rsling2, LM_GI_gi05_UnderPF, LM_GI_gi05_swRI, LM_GI_gi06_Parts, LM_GI_gi06_Playfield, LM_GI_gi06_RArm, LM_GI_gi06_RFlip, LM_GI_gi06_RFlipU, LM_GI_gi06_Rsling1, LM_GI_gi06_UnderPF, LM_GI_gi06_swRI, LM_GI_gi07_LFlip, LM_GI_gi07_LFlipU, LM_GI_gi07_Lsling2, LM_GI_gi07_Parts, LM_GI_gi07_Playfield, LM_GI_gi07_RArm, LM_GI_gi07_RFlip, LM_GI_gi07_RFlipU, _
	LM_GI_gi07_Rsling1, LM_GI_gi07_Rsling2, LM_GI_gi07_UnderPF, LM_GI_gi07_swRI, LM_GI_gi07_swRO, LM_GI_gi08_Parts, LM_GI_gi08_Playfield, LM_GI_gi08_RArm, LM_GI_gi08_RFlip, LM_GI_gi08_RFlipU, LM_GI_gi08_Rsling1, LM_GI_gi08_Rsling2, LM_GI_gi08_UnderPF, LM_GI_gi08_swRI, LM_GI_gi09_Parts, LM_GI_gi09_Playfield, LM_GI_gi09_swLI, LM_GI_gi10_Gate2, LM_GI_gi10_Parts, LM_GI_gi10_Playfield, LM_GI_gi10_RFlip1U, LM_GI_gi10_TS1, LM_GI_gi10_TS2, LM_GI_gi10_TS3, LM_GI_gi10_TS4, LM_GI_gi10_UnderPF, LM_GI_gi11_Parts, LM_GI_gi11_Playfield, LM_GI_gi12_Parts, LM_GI_gi12_Playfield, LM_GI_gi13_BR4, LM_GI_gi13_BS2, LM_GI_gi13_BS4, LM_GI_gi13_BmpBot, LM_GI_gi13_BmpTopB, LM_GI_gi13_GateR, LM_GI_gi13_Parts, LM_GI_gi13_Playfield, LM_GI_gi13_RFlip1U, LM_GI_gi13_TM4, LM_GI_gi13_TM5, LM_GI_gi13_UnderPF, LM_GI_gi14_Gate2, LM_GI_gi14_LockPin, LM_GI_gi14_Parts, LM_GI_gi14_Playfield, LM_GI_gi14_RFlip1, LM_GI_gi14_RFlip1U, LM_GI_gi14_TM5, LM_GI_gi15_LockPin, LM_GI_gi15_Parts, LM_GI_gi15_Playfield, LM_GI_gi15_RFlip1, LM_GI_gi15_RFlip1U, _
	LM_GI_gi15_UnderPF, LM_GI_gi16_Asteroid1, LM_GI_gi16_Asteroid2, LM_GI_gi16_Asteroid3, LM_GI_gi16_Asteroid4, LM_GI_gi16_BR2, LM_GI_gi16_BR3, LM_GI_gi16_BR4, LM_GI_gi16_BS2, LM_GI_gi16_BS3, LM_GI_gi16_BS4, LM_GI_gi16_BmpBot, LM_GI_gi16_BmpTopB, LM_GI_gi16_GateR, LM_GI_gi16_Parts, LM_GI_gi16_Playfield, LM_GI_gi16_Ramp, LM_GI_gi16_TM4, LM_GI_gi16_UnderPF, LM_GI_gi16_swC3, LM_GI_gi17_BR2, LM_GI_gi17_Parts, LM_GI_gi17_Playfield, LM_GI_gi18_Parts, LM_GI_gi18_Playfield, LM_GI_gi19_LockPin, LM_GI_gi19_Parts, LM_GI_gi19_Playfield, LM_GI_gi19_RFlip1, LM_GI_gi19_RFlip1U, LM_GI_gi19_TM5, LM_GI_gi19_UnderPF, LM_GI_gi20_Asteroid1, LM_GI_gi20_Asteroid2, LM_GI_gi20_Asteroid3, LM_GI_gi20_Asteroid4, LM_GI_gi20_GateL, LM_GI_gi20_Parts, LM_GI_gi20_Playfield, LM_GI_gi20_Ramp, LM_GI_gi20_Spin, LM_GI_gi20_SpinU, LM_GI_gi20_SpinWire, LM_GI_gi20_TM2, LM_GI_gi20_UnderPF, LM_GI_gi20_swC1, LM_GI_gi20_swI1, LM_GI_gi20_swL1, LM_GI_gi20_swL2, LM_GI_gi21_Asteroid1, LM_GI_gi21_Asteroid2, LM_GI_gi21_Asteroid3, LM_GI_gi21_Asteroid4, _
	LM_GI_gi21_GateL, LM_GI_gi21_Parts, LM_GI_gi21_Playfield, LM_GI_gi21_Ramp, LM_GI_gi21_Spin, LM_GI_gi21_SpinU, LM_GI_gi21_SpinWire, LM_GI_gi21_TM2, LM_GI_gi21_swL1, LM_GI_gi21_swL2, LM_GI_giapron_LFlip, LM_GI_giapron_LFlipU, LM_GI_giapron_Lsling1, LM_GI_giapron_Lsling2, LM_GI_giapron_Parts, LM_GI_giapron_Playfield, LM_GI_giapron_RFlip, LM_GI_giapron_RFlipU, LM_GI_giapron_Rsling1, LM_GI_giapron_Rsling2, LM_GI_giapron_TrustPost, LM_L_LB1_BR1, LM_L_LB1_BS1, LM_L_LB1_BmpBot, LM_L_LB1_BmpTopR, LM_L_LB1_LockPin, LM_L_LB1_Parts, LM_L_LB1_Playfield, LM_L_LB1_RFlip1, LM_L_LB1_RFlip1U, LM_L_LB1_Ramp, LM_L_LB1_Rsling1, LM_L_LB1_Rsling2, LM_L_LB1_Ship, LM_L_LB1_TM1, LM_L_LB1_TM2, LM_L_LB1_TMet1, LM_L_LB1_TS2, LM_L_LB1_UnderPF, LM_L_LB1_swLB1, LM_L_LB1_swLB2, LM_L_LB2_Asteroid1, LM_L_LB2_Asteroid2, LM_L_LB2_Asteroid3, LM_L_LB2_Asteroid4, LM_L_LB2_BR2, LM_L_LB2_BR3, LM_L_LB2_BR4, LM_L_LB2_BS2, LM_L_LB2_BS3, LM_L_LB2_BS4, LM_L_LB2_BmpBot, LM_L_LB2_BmpTopB, LM_L_LB2_DiverterPin, LM_L_LB2_Parts, LM_L_LB2_Playfield, _
	LM_L_LB2_swR2, LM_L_LB3_Asteroid1, LM_L_LB3_Asteroid2, LM_L_LB3_Asteroid3, LM_L_LB3_Asteroid4, LM_L_LB3_BR2, LM_L_LB3_BR3, LM_L_LB3_BR4, LM_L_LB3_BS2, LM_L_LB3_BS3, LM_L_LB3_BS4, LM_L_LB3_BmpBot, LM_L_LB3_BmpTopB, LM_L_LB3_DiverterPin, LM_L_LB3_Parts, LM_L_LB3_Playfield, LM_L_LB3_Spin, LM_L_LB3_TM3, LM_L_LB3_TM4, LM_L_LB3_UnderPF, LM_L_LB3_swC3, LM_L_LB3_swI2, LM_L_LB4_Asteroid1, LM_L_LB4_Asteroid2, LM_L_LB4_Asteroid3, LM_L_LB4_Asteroid4, LM_L_LB4_BR2, LM_L_LB4_BR3, LM_L_LB4_BR4, LM_L_LB4_BS2, LM_L_LB4_BS3, LM_L_LB4_BS4, LM_L_LB4_BmpBot, LM_L_LB4_BmpTopB, LM_L_LB4_GateR, LM_L_LB4_Parts, LM_L_LB4_Playfield, LM_L_LB4_TM4, LM_L_LB4_UnderPF, LM_L_LB4_swC3, LM_L_LB4_swR1, LM_L_LC1_LFlip, LM_L_LC1_LFlipU, LM_L_LC1_Parts, LM_L_LC1_Playfield, LM_L_LC1_UnderPF, LM_L_LC2_LFlip, LM_L_LC2_LFlipU, LM_L_LC2_Parts, LM_L_LC2_Playfield, LM_L_LC2_UnderPF, LM_L_LC3_LFlipU, LM_L_LC3_Playfield, LM_L_LC3_UnderPF, LM_L_LC4_LFlipU, LM_L_LC4_Playfield, LM_L_LC4_UnderPF, LM_L_LC5_Playfield, LM_L_LC5_RFlipU, LM_L_LC5_UnderPF, _
	LM_L_LC6_Playfield, LM_L_LC6_RFlipU, LM_L_LC6_UnderPF, LM_L_LC7_Playfield, LM_L_LC7_RFlipU, LM_L_LC7_UnderPF, LM_L_LC8_Parts, LM_L_LC8_Playfield, LM_L_LC8_RFlip, LM_L_LC8_RFlipU, LM_L_LC8_UnderPF, LM_L_LCC1_Parts, LM_L_LCC1_Playfield, LM_L_LCC1_Ramp, LM_L_LCC1_UnderPF, LM_L_LCC2_Parts, LM_L_LCC2_Playfield, LM_L_LCC2_UnderPF, LM_L_LCC3_Parts, LM_L_LCC3_Playfield, LM_L_LCC3_UnderPF, LM_L_LCR1_Lsling1, LM_L_LCR1_Lsling2, LM_L_LCR1_Parts, LM_L_LCR1_Playfield, LM_L_LCR1_UnderPF, LM_L_LCR2_Lsling1, LM_L_LCR2_Lsling2, LM_L_LCR2_Parts, LM_L_LCR2_Playfield, LM_L_LCR2_UnderPF, LM_L_LCWiz_Parts, LM_L_LCWiz_Playfield, LM_L_LCWiz_UnderPF, LM_L_LEBR_Parts, LM_L_LEBR_Playfield, LM_L_LEBR_TM4, LM_L_LEBR_UnderPF, LM_L_LF1_Parts, LM_L_LF1_Playfield, LM_L_LF1_UnderPF, LM_L_LF1_swR1, LM_L_LF2_Parts, LM_L_LF2_Playfield, LM_L_LF2_TM5, LM_L_LF2_UnderPF, LM_L_LF2_swR1, LM_L_LF3_Parts, LM_L_LF3_Playfield, LM_L_LF3_RFlip1U, LM_L_LF3_TM5, LM_L_LF3_UnderPF, LM_L_LH1_LFlip, LM_L_LH1_LFlipU, LM_L_LH1_Parts, LM_L_LH1_Playfield, _
	LM_L_LH1_UnderPF, LM_L_LH2_LFlip, LM_L_LH2_LFlipU, LM_L_LH2_Playfield, LM_L_LH2_UnderPF, LM_L_LH3_LFlip, LM_L_LH3_LFlipU, LM_L_LH3_Playfield, LM_L_LH3_UnderPF, LM_L_LH4_LFlip, LM_L_LH4_LFlipU, LM_L_LH4_Playfield, LM_L_LH4_UnderPF, LM_L_LH5_LFlipU, LM_L_LH5_Playfield, LM_L_LH5_RFlipU, LM_L_LH5_UnderPF, LM_L_LH6_Playfield, LM_L_LH6_RFlipU, LM_L_LH6_UnderPF, LM_L_LH7_Playfield, LM_L_LH7_RFlip, LM_L_LH7_RFlipU, LM_L_LH7_UnderPF, LM_L_LH8_Playfield, LM_L_LH8_RFlip, LM_L_LH8_RFlipU, LM_L_LH8_UnderPF, LM_L_LH9_Parts, LM_L_LH9_Playfield, LM_L_LH9_RFlip, LM_L_LH9_RFlipU, LM_L_LH9_UnderPF, LM_L_LLI_Parts, LM_L_LLI_Playfield, LM_L_LLI_UnderPF, LM_L_LLI_swLI, LM_L_LLO_Parts, LM_L_LLO_Playfield, LM_L_LLO_UnderPF, LM_L_LLO_swLO, LM_L_LLWiz_Parts, LM_L_LLWiz_Playfield, LM_L_LLWiz_UnderPF, LM_L_LM1_Parts, LM_L_LM1_Playfield, LM_L_LM1_TM1, LM_L_LM1_UnderPF, LM_L_LM2_Parts, LM_L_LM2_Playfield, LM_L_LM2_TM2, LM_L_LM2_UnderPF, LM_L_LM3_Asteroid1, LM_L_LM3_Asteroid2, LM_L_LM3_Asteroid3, LM_L_LM3_Asteroid4, LM_L_LM3_Playfield, _
	LM_L_LM3_TM3, LM_L_LM3_UnderPF, LM_L_LM4_Parts, LM_L_LM4_Playfield, LM_L_LM4_TM4, LM_L_LM4_UnderPF, LM_L_LM5_Parts, LM_L_LM5_Playfield, LM_L_LM5_TM5, LM_L_LM5_UnderPF, LM_L_LMLR_Parts, LM_L_LMLR_Playfield, LM_L_LMLR_TM5, LM_L_LMLR_UnderPF, LM_L_LMR_GateR, LM_L_LMR_Parts, LM_L_LMR_Playfield, LM_L_LMR_TM4, LM_L_LMR_UnderPF, LM_L_LMR1_Parts, LM_L_LMR1_Playfield, LM_L_LMR1_Rsling1, LM_L_LMR1_Rsling2, LM_L_LMR1_UnderPF, LM_L_LMR2_Parts, LM_L_LMR2_Playfield, LM_L_LMR2_Rsling1, LM_L_LMR2_Rsling2, LM_L_LMR2_UnderPF, LM_L_LMet1_BR1, LM_L_LMet1_BS1, LM_L_LMet1_BmpTopR, LM_L_LMet1_Parts, LM_L_LMet1_Playfield, LM_L_LMet1_TMet1, LM_L_LMet1_UnderPF, LM_L_LMet2_BmpTopR, LM_L_LMet2_Parts, LM_L_LMet2_Playfield, LM_L_LMet2_TMet2, LM_L_LMet2_UnderPF, LM_L_LMet3_Parts, LM_L_LMet3_Playfield, LM_L_LMet3_TMet3, LM_L_LMet3_UnderPF, LM_L_LMet4_Parts, LM_L_LMet4_Playfield, LM_L_LMet4_TMet4, LM_L_LMet4_UnderPF, LM_L_LPC1_Asteroid1, LM_L_LPC1_Asteroid4, LM_L_LPC1_GateL, LM_L_LPC1_Parts, LM_L_LPC1_Playfield, LM_L_LPC1_Ramp, _
	LM_L_LPC1_SpinU, LM_L_LPC1_TM2, LM_L_LPC1_UnderPF, LM_L_LPC2_Parts, LM_L_LPC2_Playfield, LM_L_LPC2_TM2, LM_L_LPC2_UnderPF, LM_L_LPC3_Parts, LM_L_LPC3_Playfield, LM_L_LPC3_UnderPF, LM_L_LPC4_Asteroid1, LM_L_LPC4_Asteroid2, LM_L_LPC4_Asteroid3, LM_L_LPC4_Asteroid4, LM_L_LPC4_Parts, LM_L_LPC4_Playfield, LM_L_LPC4_Ramp, LM_L_LPC4_TM3, LM_L_LPC4_UnderPF, LM_L_LPC4_swC1, LM_L_LPC5_Asteroid1, LM_L_LPC5_Asteroid2, LM_L_LPC5_Asteroid3, LM_L_LPC5_Asteroid4, LM_L_LPC5_Parts, LM_L_LPC5_Playfield, LM_L_LPC5_TM3, LM_L_LPC5_TM4, LM_L_LPC5_UnderPF, LM_L_LPC5_swC3, LM_L_LPF_Asteroid1, LM_L_LPF_Asteroid2, LM_L_LPF_Asteroid3, LM_L_LPF_Asteroid4, LM_L_LPF_Playfield, LM_L_LPF_TM3, LM_L_LPF_UnderPF, LM_L_LPR1_Parts, LM_L_LPR1_Playfield, LM_L_LPR1_UnderPF, LM_L_LPR2_Parts, LM_L_LPR2_Playfield, LM_L_LPR2_UnderPF, LM_L_LPR3_Parts, LM_L_LPR3_Playfield, LM_L_LPR3_UnderPF, LM_L_LPR4_LFlip, LM_L_LPR4_LFlipU, LM_L_LPR4_Parts, LM_L_LPR4_Playfield, LM_L_LPR4_UnderPF, LM_L_LPR5_LFlipU, LM_L_LPR5_Parts, LM_L_LPR5_Playfield, LM_L_LPR5_RFlipU, _
	LM_L_LPR5_UnderPF, LM_L_LPR6_Parts, LM_L_LPR6_Playfield, LM_L_LPR6_RFlipU, LM_L_LPR6_UnderPF, LM_L_LRI_Parts, LM_L_LRI_Playfield, LM_L_LRI_UnderPF, LM_L_LRI_swRI, LM_L_LRO_Parts, LM_L_LRO_Playfield, LM_L_LRO_UnderPF, LM_L_LRO_swRO, LM_L_LS1_BmpTopR, LM_L_LS1_Parts, LM_L_LS1_Playfield, LM_L_LS1_TM1, LM_L_LS1_UnderPF, LM_L_LS1_swLB1, LM_L_LS2_BmpTopR, LM_L_LS2_Parts, LM_L_LS2_Playfield, LM_L_LS2_UnderPF, LM_L_LS3_Parts, LM_L_LS3_Playfield, LM_L_LS3_Ship, LM_L_LS3_TMet2, LM_L_LS3_UnderPF, LM_L_LS4_Parts, LM_L_LS4_Playfield, LM_L_LS4_UnderPF, LM_L_LS5_Parts, LM_L_LS5_Playfield, LM_L_LS5_RFlip1U, LM_L_LS5_UnderPF, LM_L_LS6_Parts, LM_L_LS6_Playfield, LM_L_LS6_RFlip1, LM_L_LS6_RFlip1U, LM_L_LS6_UnderPF, LM_L_LSA_LFlip, LM_L_LSA_LFlipU, LM_L_LSA_Playfield, LM_L_LSA_RFlip, LM_L_LSA_RFlipU, LM_L_LSA_TrustPost, LM_L_LSA_UnderPF, LM_L_LSC1_Parts, LM_L_LSC1_Playfield, LM_L_LSC1_TS1, LM_L_LSC1_TS2, LM_L_LSC1_UnderPF, LM_L_LSC2_Parts, LM_L_LSC2_Playfield, LM_L_LSC2_TS1, LM_L_LSC2_TS2, LM_L_LSC2_TS3, LM_L_LSC2_UnderPF, _
	LM_L_LSC3_Parts, LM_L_LSC3_Playfield, LM_L_LSC3_TS2, LM_L_LSC3_TS3, LM_L_LSC3_TS4, LM_L_LSC3_UnderPF, LM_L_LSC4_Parts, LM_L_LSC4_Playfield, LM_L_LSC4_TS4, LM_L_LSC4_UnderPF, LM_L_LSL_Parts, LM_L_LSL_Playfield, LM_L_LSL_UnderPF, LM_L_LSL_swLO, LM_L_LSR_Parts, LM_L_LSR_Playfield, LM_L_LSR_UnderPF, LM_L_LSR_swRO, LM_L_LShip_Parts, LM_L_LShip_Ship, LM_L_LSwC1_Asteroid1, LM_L_LSwC1_Asteroid2, LM_L_LSwC1_Asteroid3, LM_L_LSwC1_Asteroid4, LM_L_LSwC1_Parts, LM_L_LSwC1_Playfield, LM_L_LSwC1_UnderPF, LM_L_LSwC1_swC1, LM_L_LSwC1_swC2, LM_L_LSwC2_Asteroid1, LM_L_LSwC2_Asteroid2, LM_L_LSwC2_Asteroid3, LM_L_LSwC2_Asteroid4, LM_L_LSwC2_BmpTopB, LM_L_LSwC2_Parts, LM_L_LSwC2_Playfield, LM_L_LSwC2_TM3, LM_L_LSwC2_UnderPF, LM_L_LSwC2_swC2, LM_L_LSwC3_Asteroid1, LM_L_LSwC3_Asteroid2, LM_L_LSwC3_Asteroid3, LM_L_LSwC3_Asteroid4, LM_L_LSwC3_Parts, LM_L_LSwC3_Playfield, LM_L_LSwC3_UnderPF, LM_L_LSwC3_swC2, LM_L_LSwC3_swC3, LM_L_LSwL1_BR1, LM_L_LSwL1_BS1, LM_L_LSwL1_BmpTopR, LM_L_LSwL1_Parts, LM_L_LSwL1_Playfield, LM_L_LSwL1_TM1, _
	LM_L_LSwL1_UnderPF, LM_L_LSwL1_swLB1, LM_L_LSwL2_BS1, LM_L_LSwL2_BmpBot, LM_L_LSwL2_BmpTopR, LM_L_LSwL2_Parts, LM_L_LSwL2_Playfield, LM_L_LSwL2_UnderPF, LM_L_LSwL2_swLB2, LM_L_LTW1_Parts, LM_L_LTW1_Playfield, LM_L_LTW1_Ramp, LM_L_LTW1_UnderPF, LM_L_LTW2_Parts, LM_L_LTW2_Playfield, LM_L_LTW2_Ramp, LM_L_LTW2_UnderPF, LM_L_LTW3_Parts, LM_L_LTW3_Playfield, LM_L_LTW3_UnderPF, LM_L_LTW4_Parts, LM_L_LTW4_Playfield, LM_L_LTW4_UnderPF, LM_L_LW1_Parts, LM_L_LW1_Playfield, LM_L_LW1_UnderPF, LM_L_LW2_Parts, LM_L_LW2_Playfield, LM_L_LW2_UnderPF, LM_L_LW3_Parts, LM_L_LW3_Playfield, LM_L_LW3_UnderPF, LM_L_LW4_Parts, LM_L_LW4_Playfield, LM_L_LW4_UnderPF, LM_L_LW5_Parts, LM_L_LW5_Playfield, LM_L_LW5_UnderPF, LM_L_LW6_BmpTopR, LM_L_LW6_Parts, LM_L_LW6_Playfield, LM_L_LW6_UnderPF, LM_L_LW7_BmpTopR, LM_L_LW7_Parts, LM_L_LW7_Playfield, LM_L_LW7_UnderPF, LM_L_LW8_BmpTopR, LM_L_LW8_Parts, LM_L_LW8_Playfield, LM_L_LW8_UnderPF, LM_L_LW9_Parts, LM_L_LW9_Playfield, LM_L_LW9_UnderPF, LM_L_LWiz_Parts, LM_L_LWiz_Playfield, _
	LM_L_LWiz_UnderPF, LM_L_LX_Parts, LM_L_LX_Playfield, LM_L_LX_UnderPF, LM_L_Lspot1_Asteroid1, LM_L_Lspot1_Asteroid2, LM_L_Lspot1_Asteroid3, LM_L_Lspot1_Asteroid4, LM_L_Lspot1_BR4, LM_L_Lspot1_BS4, LM_L_Lspot1_BmpTopB, LM_L_Lspot1_Parts, LM_L_Lspot1_Playfield, LM_L_Lspot1_Ramp, LM_L_Lspot1_Spin, LM_L_Lspot1_SpinU, LM_L_Lspot1_SpinWire, LM_L_Lspot1_TM3, LM_L_Lspot1_TM4, LM_L_Lspot1_UnderPF, LM_L_Lspot1_swC1, LM_L_Lspot1_swC2, LM_L_Lspot1_swC3, LM_L_Lspot1_swI2, LM_L_Lspot2_GateL, LM_L_Lspot2_LArm, LM_L_Lspot2_LFlip, LM_L_Lspot2_LFlipU, LM_L_Lspot2_LockPin, LM_L_Lspot2_Lsling1, LM_L_Lspot2_Lsling2, LM_L_Lspot2_Parts, LM_L_Lspot2_Playfield, LM_L_Lspot2_RArm, LM_L_Lspot2_RFlip, LM_L_Lspot2_RFlipU, LM_L_Lspot2_Ramp, LM_L_Lspot2_Rsling1, LM_L_Lspot2_Rsling2, LM_L_Lspot2_UnderPF, LM_L_Lspot2_swLB1, LM_L_Lspot2_swLO, LM_Stars_Parts, LM_Stars_Ramp)
' VLM  Arrays - End

' BL array. Must be in same order as AllControlLights collection
Dim BL_Array: BL_Array = Array(BL_L_LB1,BL_L_LB2,BL_L_LB3,BL_L_LB4,BL_L_LC1,BL_L_LC2,BL_L_LC3,BL_L_LC4,BL_L_LC5,BL_L_LC6,BL_L_LC7,BL_L_LC8,BL_L_LCC1,BL_L_LCC2,BL_L_LCC3,BL_L_LCR1,BL_L_LCR2, _
	BL_L_LCWiz,BL_L_LEBR,BL_L_LF1,BL_L_LF2,BL_L_LF3,BL_L_LH1,BL_L_LH2,BL_L_LH3,BL_L_LH4,BL_L_LH5,BL_L_LH6,BL_L_LH7,BL_L_LH8,BL_L_LH9,BL_L_LLI,BL_L_LLO,BL_L_LLWiz,BL_L_LM1,BL_L_LM2,BL_L_LM3, _
	BL_L_LM4,BL_L_LM5,BL_L_LMet1,BL_L_LMet2,BL_L_LMet3,BL_L_LMet4,BL_L_LMLR,BL_L_LMR,BL_L_LMR1,BL_L_LMR2,BL_L_LPC1,BL_L_LPC2,BL_L_LPC3,BL_L_LPC4,BL_L_LPC5,BL_L_LPF,BL_L_LPR1,BL_L_LPR2,BL_L_LPR3, _
	BL_L_LPR4,BL_L_LPR5,BL_L_LPR6,BL_L_LRI,BL_L_LRO,BL_L_LS1,BL_L_LS2,BL_L_LS3,BL_L_LS4,BL_L_LS5,BL_L_LS6,BL_L_LSA,BL_L_LSC1,BL_L_LSC2,BL_L_LSC3,BL_L_LSC4,BL_L_LSL,BL_L_Lspot1,BL_L_Lspot2, _
	BL_L_LSR,BL_L_LSwC1,BL_L_LSwC2,BL_L_LSwC3,BL_L_LSwL1,BL_L_LSwL2,BL_L_LTW1,BL_L_LTW2,BL_L_LTW3,BL_L_LTW4,BL_L_LW1,BL_L_LW2,BL_L_LW3,BL_L_LW4,BL_L_LW5,BL_L_LW6,BL_L_LW7,BL_L_LW8, _
	BL_L_LW9,BL_L_LWiz,BL_L_LX)

Dim LenControlLights: LenControlLights = UBound(BL_Array)

