#config_version=6

mode:
  start_events: new_ball_started, stop_meteor_wave, stop_training, wizard_mode_ended
  stop_events: stop_mystery, mode_base_stopping, start_training_select, wizard_mode_started
  priority: 580

event_player: 
  mode_mystery_started{current_player.shot_mystery_ready==1 and machine.flippers_are_dead==0}:
    - enable_scoop_hold
  check_mystery{current_player.shot_mystery_ready==0 and machine.flippers_are_dead==0}:
    - check_training
  check_mystery{current_player.shot_mystery_ready==1 and machine.flippers_are_dead==0}:
    - select_random_mystery
  select_random_mystery:
    - play_mystery_show
  restart_qualify_mystery{current_player.shot_training_ready==0}:
    - release_scoop_hold
  release_scoop_hold:
    - disable_scoop_hold
    - start_mwq_timer
  restart_qualify_mystery:
    - mystery_select_done
    - check_training
  sss_mystery_ready:
    - complete_mystery_shots
    - set_sss_mystery_flag
  qualify_mystery_on_complete{current_player.flag_sss_mystery == 0}:
    - play_voc_LMR
    - enable_scoop_hold
    - mystery_flash
    - score_30000
  qualify_mystery_hit:
    - score_1000


random_event_player: 
  select_random_mystery: 
    events:
      mystery_full_health{current_player.shot_health9_light == 0}: 1
      mystery_full_protons{current_player.shot_proton_round6 == 0}: 0.7
      mystery_added_cluster{current_player.shot_cluster_bomb2 == 0}: 0.8
      mystery_added_saver{current_player.shot_ship_charge3 != 2}: 1
      mystery_added_shields{current_player.shot_shield_left == 0}: 1
      mystery_moon_ready{current_player.shot_moon_missile2 == 0 and device.state_machines.moon_mb.state!="locking"}: 1
      mystery_double_scoring{current_player.scoring_multiplier == 1}: 0.5
      mystery_super_spinner{current_player.spin_multiplier == 1}: 0.5
      mystery_super_pops{current_player.pop_multiplier == 1}: 0.5
      mystery_double_bonus{current_player.bonus_multiplier == 1}: 0.5
      mystery_relaxed_combos{current_player.combos_relaxed == 0}: 0.5
      activate_nuke{current_player.nuke_acquired == 0}: 0.5
    scope: player
  qualify_mystery_hit: 
    events:
      play_sfx_LM1: 1
      play_sfx_LM2: 1
      play_sfx_LM3: 1
      play_sfx_LM4: 1
      play_sfx_LM5: 1
    scope: player


segment_display_player: 
  qualify_mystery_on_complete: 
    player2: 
      text: "CLAIM"
      priority: 1000
      expire: 4000ms
      flashing: all
    player3: 
      text: "MYSTERY"
      priority: 1000
      expire: 4000ms
      flashing: all

  select_random_mystery: 
    player1: 
      text: "MYSTERY"
      priority: 1000
      expire: 4000ms
      flashing: off
    player4: 
      text: " "
      priority: 1000
      expire: 4000ms
      flashing: off

  mystery_full_health: 
    player2: 
      text: " FULL "
      priority: 1000
      expire: 4000ms
      flashing: all
    player3: 
      text: "HEALTH"
      priority: 1000
      expire: 4000ms
      flashing: all

  mystery_full_protons: 
    player2: 
      text: " FULL "
      priority: 1000
      expire: 4000ms
      flashing: all
    player3: 
      text: "PROTONS"
      priority: 1000
      expire: 4000ms
      flashing: all

  mystery_added_cluster: 
    player2: 
      text: " ADDED "
      priority: 1000
      expire: 4000ms
      flashing: all
    player3: 
      text: "CLUSTER"
      priority: 1000
      expire: 4000ms
      flashing: all

  mystery_added_saver: 
    player2: 
      text: " ADDED "
      priority: 1000
      expire: 4000ms
      flashing: all
    player3: 
      text: " SAVER "
      priority: 1000
      expire: 4000ms
      flashing: all

  mystery_added_shields: 
    player2: 
      text: " ADDED "
      priority: 1000
      expire: 4000ms
      flashing: all
    player3: 
      text: "SHIELDS"
      priority: 1000
      expire: 4000ms
      flashing: all

  mystery_moon_ready: 
    player2: 
      text: " MOON "
      priority: 1000
      expire: 4000ms
      flashing: all
    player3: 
      text: " READY "
      priority: 1000
      expire: 4000ms
      flashing: all

  mystery_trainer_ready: 
    player2: 
      text: "TRAINER"
      priority: 1000
      expire: 4000ms
      flashing: all
    player3: 
      text: " READY "
      priority: 1000
      expire: 4000ms
      flashing: all

  mystery_double_scoring: 
    player2: 
      text: "DOUBLE"
      priority: 1000
      expire: 4000ms
      flashing: all
    player3: 
      text: "SCORING"
      priority: 1000
      expire: 4000ms
      flashing: all

  mystery_super_spinner: 
    player2: 
      text: " SUPER "
      priority: 1000
      expire: 4000ms
      flashing: all
    player3: 
      text: "SPINNER"
      priority: 1000
      expire: 4000ms
      flashing: all

  mystery_super_pops: 
    player2: 
      text: " SUPER "
      priority: 1000
      expire: 4000ms
      flashing: all
    player3: 
      text: "  POPS  "
      priority: 1000
      expire: 4000ms
      flashing: all

  mystery_double_bonus: 
    player2: 
      text: "DOUBLE"
      priority: 1000
      expire: 4000ms
      flashing: all
    player3: 
      text: " BONUS "
      priority: 1000
      expire: 4000ms
      flashing: all

  mystery_relaxed_combos: 
    player2: 
      text: "RELAXED"
      priority: 1000
      expire: 4000ms
      flashing: all
    player3: 
      text: "COMBOS"
      priority: 1000
      expire: 4000ms
      flashing: all

  mystery_eb_is_lit: 
    player2: 
      text: " EB IS "
      priority: 1000
      expire: 4000ms
      flashing: all
    player3: 
      text: " LIT "
      priority: 1000
      expire: 4000ms
      flashing: all


shot_groups: 
  qualify_mystery:
    shots: mystery_shot1,mystery_shot2,mystery_shot3,mystery_shot4,mystery_shot5
    restart_events: restart_qualify_mystery
    enable_events: stop_meteor_wave
    disable_events: select_random_mystery, start_meteor_wave

shots: 
  mystery_shot1:
    switch: s_TargetMystery1
    profile: flicker_on
    show_tokens: 
      lights: "LM1"
      color: "f7b5c9"
    control_events: 
      - events: complete_mystery_shots
        state: 1
  mystery_shot2:
    switch: s_TargetMystery2
    profile: flicker_on
    show_tokens: 
      lights: "LM2"
      color: "f7b5c9"
    control_events: 
      - events: complete_mystery_shots
        state: 1
  mystery_shot3:
    switch: s_TargetMystery3
    profile: flicker_on
    show_tokens: 
      lights: "LM3"
      color: "f7b5c9"
    control_events: 
      - events: complete_mystery_shots
        state: 1
  mystery_shot4:
    switch: s_TargetMystery4
    profile: flicker_on
    show_tokens: 
      lights: "LM4"
      color: "f7b5c9"
    control_events: 
      - events: complete_mystery_shots
        state: 1
  mystery_shot5:
    switch: s_TargetMystery5
    profile: flicker_on
    show_tokens: 
      lights: "LM5"
      color: "f7b5c9"
    control_events: 
      - events: complete_mystery_shots
        state: 1
  mystery_ready:
    profile: qualified_shot
    restart_events: restart_qualify_mystery
    show_tokens: 
      lights: "LMR"
      color: "f7b5c9"
    control_events: 
      - events: qualify_mystery_on_complete
        state: 1

show_player: 
  qualify_mystery_on_complete: 
    flash_color: 
      key: key_mystery_qualified
      loops: 6
      speed: 13
      show_tokens: 
        lights: "tMystery"
        color: "f7b5c9"
  mystery_flash: 
    flash_color: 
      key: key_loaded_wiz_ready
      loops: 3
      speed: 20
      show_tokens: 
        lights: "tFlasherU"
        color: "f7b5c9"
  play_mystery_show: 
    gi_spin1_cw: 
      key: key_mystery_show
      loops: 1
      show_tokens: 
        intensity: "100"
      events_when_completed: restart_qualify_mystery


sound_player: 
  play_voc_LMR: 
    voc_LMR: 
      key: key_voc_LMR
      action: play
  play_sfx_LM1: 
    sfx_LM1: 
      key: key_sfx_LM1
      action: play
  play_sfx_LM2: 
    sfx_LM2: 
      key: key_sfx_LM2
      action: play
  play_sfx_LM3: 
    sfx_LM3: 
      key: key_sfx_LM3
      action: play
  play_sfx_LM4: 
    sfx_LM4: 
      key: key_sfx_LM4
      action: play
  play_sfx_LM5: 
    sfx_LM5: 
      key: key_sfx_LM5
      action: play
  mystery_relaxed_combos: 
    voc_relaxed_combos: 
      key: key_voc_relaxed_combos
      action: play
  mystery_super_spinner: 
    voc_super_spinner: 
      key: key_voc_super_spinner
      action: play
  mystery_super_pops: 
    voc_super_pop_bumpers: 
      key: key_voc_super_pop_bumpers
      action: play
  mystery_full_protons: 
    voc_full_protons: 
      key: key_voc_full_protons
      action: play
  mystery_full_health: 
    voc_full_health: 
      key: key_voc_full_health
      action: play
  mystery_double_scoring: 
    voc_double_scoring: 
      key: key_voc_double_scoring
      action: play
  mystery_double_bonus: 
    voc_double_bonus: 
      key: key_voc_double_bonus
      action: play


variable_player: 
  set_sss_mystery_flag: 
    flag_sss_mystery: 
      action: set
      int: 1

  play_voc_LMR: 
    flag_sss_mystery: 
      action: set
      int: 0



widget_player: 
  play_voc_LMR: 
    mystery_ready:
      action: play
      expire: 5s



