

'Insert Shows

Sub CreateInsertShows()

With CreateGlfShow("insert_swap2")
    With .AddStep(Null, Null, 0.1)
        .Lights = Array( _
        "LPF|(intensity)|(color1)", _
        "LX|(intensity)|(color2)", _
        "LS5|(intensity)|(color1)", _
        "LS1|(intensity)|(color2)", _
        "LSwL1|(intensity)|(color1)", _
        "LSwL2|(intensity)|(color2)", _
        "LS2|(intensity)|(color1)", _
        "LS3|(intensity)|(color2)", _
        "LS4|(intensity)|(color1)", _
        "LS6|(intensity)|(color2)", _
        "LSwC3|(intensity)|(color1)", _
        "LSwC2|(intensity)|(color2)", _
        "LSwC1|(intensity)|(color1)", _
        "LCWiz|(intensity)|(color2)", _
        "LLWiz|(intensity)|(color1)", _
        "LC1|(intensity)|(color2)", _
        "LC2|(intensity)|(color1)", _
        "LC3|(intensity)|(color2)", _
        "LC4|(intensity)|(color1)", _
        "LC5|(intensity)|(color2)", _
        "LC6|(intensity)|(color1)", _
        "LC7|(intensity)|(color2)", _
        "LC8|(intensity)|(color1)", _
        "LWiz|(intensity)|(color2)", _
        "LW9|(intensity)|(color1)", _
        "LW8|(intensity)|(color2)", _
        "LW7|(intensity)|(color1)", _
        "LW6|(intensity)|(color2)", _
        "LW5|(intensity)|(color1)", _
        "LW4|(intensity)|(color2)", _
        "LW3|(intensity)|(color1)", _
        "LW2|(intensity)|(color2)", _
        "LW1|(intensity)|(color1)", _
        "LMLR|(intensity)|(color2)", _
        "LEBR|(intensity)|(color1)", _
        "LMR|(intensity)|(color2)", _
        "LPC5|(intensity)|(color1)", _
        "LPC4|(intensity)|(color2)", _
        "LSC4|(intensity)|(color1)", _
        "LSC3|(intensity)|(color2)", _
        "LSC2|(intensity)|(color1)", _
        "LSC1|(intensity)|(color2)", _
        "LF3|(intensity)|(color1)", _
        "LF2|(intensity)|(color2)", _
        "LF1|(intensity)|(color1)", _
        "LPC3|(intensity)|(color2)", _
        "LPC2|(intensity)|(color1)", _
        "LPC1|(intensity)|(color2)", _
        "LTW4|(intensity)|(color1)", _
        "LTW3|(intensity)|(color2)", _
        "LTW2|(intensity)|(color1)", _
        "LTW1|(intensity)|(color2)", _
        "LCC3|(intensity)|(color1)", _
        "LCC2|(intensity)|(color2)", _
        "LCC1|(intensity)|(color1)", _
        "LMet4|(intensity)|(color2)", _
        "LMet3|(intensity)|(color1)", _
        "LMet2|(intensity)|(color2)", _
        "LMet1|(intensity)|(color1)", _
        "LM5|(intensity)|(color2)", _
        "LM4|(intensity)|(color1)", _
        "LM3|(intensity)|(color2)", _
        "LM2|(intensity)|(color1)", _
        "LM1|(intensity)|(color2)", _
        "LSA|(intensity)|(color1)", _
        "LH9|(intensity)|(color2)", _
        "LH8|(intensity)|(color1)", _
        "LH7|(intensity)|(color2)", _
        "LH6|(intensity)|(color1)", _
        "LH5|(intensity)|(color2)", _
        "LH4|(intensity)|(color1)", _
        "LH3|(intensity)|(color2)", _
        "LH2|(intensity)|(color1)", _
        "LH1|(intensity)|(color2)", _
        "LPR1|(intensity)|(color1)", _
        "LPR3|(intensity)|(color2)", _
        "LPR2|(intensity)|(color1)", _
        "LPR6|(intensity)|(color2)", _
        "LPR5|(intensity)|(color1)", _
        "LPR4|(intensity)|(color2)", _
        "LMR2|(intensity)|(color1)", _
        "LMR1|(intensity)|(color2)", _
        "LCR2|(intensity)|(color1)", _
        "LCR1|(intensity)|(color2)", _
        "LRI|(intensity)|(color1)", _
        "LRO|(intensity)|(color2)", _
        "LLI|(intensity)|(color1)", _
        "LLO|(intensity)|(color2)", _
        "LSR|(intensity)|(color1)", _
        "LSL|(intensity)|(color2)" _
        )
    End With
    With .AddStep(Null, Null, 0.1)
        .Lights = Array( _
        "LPF|(intensity)|(color2)", _
        "LX|(intensity)|(color1)", _
        "LS5|(intensity)|(color2)", _
        "LS1|(intensity)|(color1)", _
        "LSwL1|(intensity)|(color2)", _
        "LSwL2|(intensity)|(color1)", _
        "LS2|(intensity)|(color2)", _
        "LS3|(intensity)|(color1)", _
        "LS4|(intensity)|(color2)", _
        "LS6|(intensity)|(color1)", _
        "LSwC3|(intensity)|(color2)", _
        "LSwC2|(intensity)|(color1)", _
        "LSwC1|(intensity)|(color2)", _
        "LCWiz|(intensity)|(color1)", _
        "LLWiz|(intensity)|(color2)", _
        "LC1|(intensity)|(color1)", _
        "LC2|(intensity)|(color2)", _
        "LC3|(intensity)|(color1)", _
        "LC4|(intensity)|(color2)", _
        "LC5|(intensity)|(color1)", _
        "LC6|(intensity)|(color2)", _
        "LC7|(intensity)|(color1)", _
        "LC8|(intensity)|(color2)", _
        "LWiz|(intensity)|(color1)", _
        "LW9|(intensity)|(color2)", _
        "LW8|(intensity)|(color1)", _
        "LW7|(intensity)|(color2)", _
        "LW6|(intensity)|(color1)", _
        "LW5|(intensity)|(color2)", _
        "LW4|(intensity)|(color1)", _
        "LW3|(intensity)|(color2)", _
        "LW2|(intensity)|(color1)", _
        "LW1|(intensity)|(color2)", _
        "LMLR|(intensity)|(color1)", _
        "LEBR|(intensity)|(color2)", _
        "LMR|(intensity)|(color1)", _
        "LPC5|(intensity)|(color2)", _
        "LPC4|(intensity)|(color1)", _
        "LSC4|(intensity)|(color2)", _
        "LSC3|(intensity)|(color1)", _
        "LSC2|(intensity)|(color2)", _
        "LSC1|(intensity)|(color1)", _
        "LF3|(intensity)|(color2)", _
        "LF2|(intensity)|(color1)", _
        "LF1|(intensity)|(color2)", _
        "LPC3|(intensity)|(color1)", _
        "LPC2|(intensity)|(color2)", _
        "LPC1|(intensity)|(color1)", _
        "LTW4|(intensity)|(color2)", _
        "LTW3|(intensity)|(color1)", _
        "LTW2|(intensity)|(color2)", _
        "LTW1|(intensity)|(color1)", _
        "LCC3|(intensity)|(color2)", _
        "LCC2|(intensity)|(color1)", _
        "LCC1|(intensity)|(color2)", _
        "LMet4|(intensity)|(color1)", _
        "LMet3|(intensity)|(color2)", _
        "LMet2|(intensity)|(color1)", _
        "LMet1|(intensity)|(color2)", _
        "LM5|(intensity)|(color1)", _
        "LM4|(intensity)|(color2)", _
        "LM3|(intensity)|(color1)", _
        "LM2|(intensity)|(color2)", _
        "LM1|(intensity)|(color1)", _
        "LSA|(intensity)|(color2)", _
        "LH9|(intensity)|(color1)", _
        "LH8|(intensity)|(color2)", _
        "LH7|(intensity)|(color1)", _
        "LH6|(intensity)|(color2)", _
        "LH5|(intensity)|(color1)", _
        "LH4|(intensity)|(color2)", _
        "LH3|(intensity)|(color1)", _
        "LH2|(intensity)|(color2)", _
        "LH1|(intensity)|(color1)", _
        "LPR1|(intensity)|(color2)", _
        "LPR3|(intensity)|(color1)", _
        "LPR2|(intensity)|(color2)", _
        "LPR6|(intensity)|(color1)", _
        "LPR5|(intensity)|(color2)", _
        "LPR4|(intensity)|(color1)", _
        "LMR2|(intensity)|(color2)", _
        "LMR1|(intensity)|(color1)", _
        "LCR2|(intensity)|(color2)", _
        "LCR1|(intensity)|(color1)", _
        "LRI|(intensity)|(color2)", _
        "LRO|(intensity)|(color1)", _
        "LLI|(intensity)|(color2)", _
        "LLO|(intensity)|(color1)", _
        "LSR|(intensity)|(color2)", _
        "LSL|(intensity)|(color1)" _
        )
    End With
End With




With CreateGlfShow("insert_swap3")
    With .AddStep(Null, Null, 0.1)
        .Lights = Array( _
        "LPF|(intensity)|(color1)", _
        "LX|(intensity)|(color2)", _
        "LS5|(intensity)|(color3)", _
        "LS1|(intensity)|(color1)", _
        "LSwL1|(intensity)|(color2)", _
        "LSwL2|(intensity)|(color3)", _
        "LS2|(intensity)|(color1)", _
        "LS3|(intensity)|(color2)", _
        "LS4|(intensity)|(color3)", _
        "LS6|(intensity)|(color1)", _
        "LSwC3|(intensity)|(color2)", _
        "LSwC2|(intensity)|(color3)", _
        "LSwC1|(intensity)|(color1)", _
        "LCWiz|(intensity)|(color2)", _
        "LLWiz|(intensity)|(color3)", _
        "LC1|(intensity)|(color1)", _
        "LC2|(intensity)|(color2)", _
        "LC3|(intensity)|(color3)", _
        "LC4|(intensity)|(color1)", _
        "LC5|(intensity)|(color2)", _
        "LC6|(intensity)|(color3)", _
        "LC7|(intensity)|(color1)", _
        "LC8|(intensity)|(color2)", _
        "LWiz|(intensity)|(color3)", _
        "LW9|(intensity)|(color1)", _
        "LW8|(intensity)|(color2)", _
        "LW7|(intensity)|(color3)", _
        "LW6|(intensity)|(color1)", _
        "LW5|(intensity)|(color2)", _
        "LW4|(intensity)|(color3)", _
        "LW3|(intensity)|(color1)", _
        "LW2|(intensity)|(color2)", _
        "LW1|(intensity)|(color3)", _
        "LMLR|(intensity)|(color1)", _
        "LEBR|(intensity)|(color2)", _
        "LMR|(intensity)|(color3)", _
        "LPC5|(intensity)|(color1)", _
        "LPC4|(intensity)|(color2)", _
        "LSC4|(intensity)|(color3)", _
        "LSC3|(intensity)|(color1)", _
        "LSC2|(intensity)|(color2)", _
        "LSC1|(intensity)|(color3)", _
        "LF3|(intensity)|(color1)", _
        "LF2|(intensity)|(color2)", _
        "LF1|(intensity)|(color3)", _
        "LPC3|(intensity)|(color1)", _
        "LPC2|(intensity)|(color2)", _
        "LPC1|(intensity)|(color3)", _
        "LTW4|(intensity)|(color1)", _
        "LTW3|(intensity)|(color2)", _
        "LTW2|(intensity)|(color3)", _
        "LTW1|(intensity)|(color1)", _
        "LCC3|(intensity)|(color2)", _
        "LCC2|(intensity)|(color3)", _
        "LCC1|(intensity)|(color1)", _
        "LMet4|(intensity)|(color2)", _
        "LMet3|(intensity)|(color3)", _
        "LMet2|(intensity)|(color1)", _
        "LMet1|(intensity)|(color2)", _
        "LM5|(intensity)|(color3)", _
        "LM4|(intensity)|(color1)", _
        "LM3|(intensity)|(color2)", _
        "LM2|(intensity)|(color3)", _
        "LM1|(intensity)|(color1)", _
        "LSA|(intensity)|(color2)", _
        "LH9|(intensity)|(color3)", _
        "LH8|(intensity)|(color1)", _
        "LH7|(intensity)|(color2)", _
        "LH6|(intensity)|(color3)", _
        "LH5|(intensity)|(color1)", _
        "LH4|(intensity)|(color2)", _
        "LH3|(intensity)|(color3)", _
        "LH2|(intensity)|(color1)", _
        "LH1|(intensity)|(color2)", _
        "LPR1|(intensity)|(color3)", _
        "LPR3|(intensity)|(color1)", _
        "LPR2|(intensity)|(color2)", _
        "LPR6|(intensity)|(color3)", _
        "LPR5|(intensity)|(color1)", _
        "LPR4|(intensity)|(color2)", _
        "LMR2|(intensity)|(color3)", _
        "LMR1|(intensity)|(color1)", _
        "LCR2|(intensity)|(color2)", _
        "LCR1|(intensity)|(color3)", _
        "LRI|(intensity)|(color1)", _
        "LRO|(intensity)|(color2)", _
        "LLI|(intensity)|(color3)", _
        "LLO|(intensity)|(color1)", _
        "LSR|(intensity)|(color2)", _
        "LSL|(intensity)|(color3)" _
        )
    End With
    With .AddStep(Null, Null, 0.1)
        .Lights = Array( _
        "LPF|(intensity)|(color3)", _
        "LX|(intensity)|(color1)", _
        "LS5|(intensity)|(color2)", _
        "LS1|(intensity)|(color3)", _
        "LSwL1|(intensity)|(color1)", _
        "LSwL2|(intensity)|(color2)", _
        "LS2|(intensity)|(color3)", _
        "LS3|(intensity)|(color1)", _
        "LS4|(intensity)|(color2)", _
        "LS6|(intensity)|(color3)", _
        "LSwC3|(intensity)|(color1)", _
        "LSwC2|(intensity)|(color2)", _
        "LSwC1|(intensity)|(color3)", _
        "LCWiz|(intensity)|(color1)", _
        "LLWiz|(intensity)|(color2)", _
        "LC1|(intensity)|(color3)", _
        "LC2|(intensity)|(color1)", _
        "LC3|(intensity)|(color2)", _
        "LC4|(intensity)|(color3)", _
        "LC5|(intensity)|(color1)", _
        "LC6|(intensity)|(color2)", _
        "LC7|(intensity)|(color3)", _
        "LC8|(intensity)|(color1)", _
        "LWiz|(intensity)|(color2)", _
        "LW9|(intensity)|(color3)", _
        "LW8|(intensity)|(color1)", _
        "LW7|(intensity)|(color2)", _
        "LW6|(intensity)|(color3)", _
        "LW5|(intensity)|(color1)", _
        "LW4|(intensity)|(color2)", _
        "LW3|(intensity)|(color3)", _
        "LW2|(intensity)|(color1)", _
        "LW1|(intensity)|(color2)", _
        "LMLR|(intensity)|(color3)", _
        "LEBR|(intensity)|(color1)", _
        "LMR|(intensity)|(color2)", _
        "LPC5|(intensity)|(color3)", _
        "LPC4|(intensity)|(color1)", _
        "LSC4|(intensity)|(color2)", _
        "LSC3|(intensity)|(color3)", _
        "LSC2|(intensity)|(color1)", _
        "LSC1|(intensity)|(color2)", _
        "LF3|(intensity)|(color3)", _
        "LF2|(intensity)|(color1)", _
        "LF1|(intensity)|(color2)", _
        "LPC3|(intensity)|(color3)", _
        "LPC2|(intensity)|(color1)", _
        "LPC1|(intensity)|(color2)", _
        "LTW4|(intensity)|(color3)", _
        "LTW3|(intensity)|(color1)", _
        "LTW2|(intensity)|(color2)", _
        "LTW1|(intensity)|(color3)", _
        "LCC3|(intensity)|(color1)", _
        "LCC2|(intensity)|(color2)", _
        "LCC1|(intensity)|(color3)", _
        "LMet4|(intensity)|(color1)", _
        "LMet3|(intensity)|(color2)", _
        "LMet2|(intensity)|(color3)", _
        "LMet1|(intensity)|(color1)", _
        "LM5|(intensity)|(color2)", _
        "LM4|(intensity)|(color3)", _
        "LM3|(intensity)|(color1)", _
        "LM2|(intensity)|(color2)", _
        "LM1|(intensity)|(color3)", _
        "LSA|(intensity)|(color1)", _
        "LH9|(intensity)|(color2)", _
        "LH8|(intensity)|(color3)", _
        "LH7|(intensity)|(color1)", _
        "LH6|(intensity)|(color2)", _
        "LH5|(intensity)|(color3)", _
        "LH4|(intensity)|(color1)", _
        "LH3|(intensity)|(color2)", _
        "LH2|(intensity)|(color3)", _
        "LH1|(intensity)|(color1)", _
        "LPR1|(intensity)|(color2)", _
        "LPR3|(intensity)|(color3)", _
        "LPR2|(intensity)|(color1)", _
        "LPR6|(intensity)|(color2)", _
        "LPR5|(intensity)|(color3)", _
        "LPR4|(intensity)|(color1)", _
        "LMR2|(intensity)|(color2)", _
        "LMR1|(intensity)|(color3)", _
        "LCR2|(intensity)|(color1)", _
        "LCR1|(intensity)|(color2)", _
        "LRI|(intensity)|(color3)", _
        "LRO|(intensity)|(color1)", _
        "LLI|(intensity)|(color2)", _
        "LLO|(intensity)|(color3)", _
        "LSR|(intensity)|(color1)", _
        "LSL|(intensity)|(color2)" _
        )
    End With
    With .AddStep(Null, Null, 0.1)
        .Lights = Array( _
        "LPF|(intensity)|(color2)", _
        "LX|(intensity)|(color3)", _
        "LS5|(intensity)|(color1)", _
        "LS1|(intensity)|(color2)", _
        "LSwL1|(intensity)|(color3)", _
        "LSwL2|(intensity)|(color1)", _
        "LS2|(intensity)|(color2)", _
        "LS3|(intensity)|(color3)", _
        "LS4|(intensity)|(color1)", _
        "LS6|(intensity)|(color2)", _
        "LSwC3|(intensity)|(color3)", _
        "LSwC2|(intensity)|(color1)", _
        "LSwC1|(intensity)|(color2)", _
        "LCWiz|(intensity)|(color3)", _
        "LLWiz|(intensity)|(color1)", _
        "LC1|(intensity)|(color2)", _
        "LC2|(intensity)|(color3)", _
        "LC3|(intensity)|(color1)", _
        "LC4|(intensity)|(color2)", _
        "LC5|(intensity)|(color3)", _
        "LC6|(intensity)|(color1)", _
        "LC7|(intensity)|(color2)", _
        "LC8|(intensity)|(color3)", _
        "LWiz|(intensity)|(color1)", _
        "LW9|(intensity)|(color2)", _
        "LW8|(intensity)|(color3)", _
        "LW7|(intensity)|(color1)", _
        "LW6|(intensity)|(color2)", _
        "LW5|(intensity)|(color3)", _
        "LW4|(intensity)|(color1)", _
        "LW3|(intensity)|(color2)", _
        "LW2|(intensity)|(color3)", _
        "LW1|(intensity)|(color1)", _
        "LMLR|(intensity)|(color2)", _
        "LEBR|(intensity)|(color3)", _
        "LMR|(intensity)|(color1)", _
        "LPC5|(intensity)|(color2)", _
        "LPC4|(intensity)|(color3)", _
        "LSC4|(intensity)|(color1)", _
        "LSC3|(intensity)|(color2)", _
        "LSC2|(intensity)|(color3)", _
        "LSC1|(intensity)|(color1)", _
        "LF3|(intensity)|(color2)", _
        "LF2|(intensity)|(color3)", _
        "LF1|(intensity)|(color1)", _
        "LPC3|(intensity)|(color2)", _
        "LPC2|(intensity)|(color3)", _
        "LPC1|(intensity)|(color1)", _
        "LTW4|(intensity)|(color2)", _
        "LTW3|(intensity)|(color3)", _
        "LTW2|(intensity)|(color1)", _
        "LTW1|(intensity)|(color2)", _
        "LCC3|(intensity)|(color3)", _
        "LCC2|(intensity)|(color1)", _
        "LCC1|(intensity)|(color2)", _
        "LMet4|(intensity)|(color3)", _
        "LMet3|(intensity)|(color1)", _
        "LMet2|(intensity)|(color2)", _
        "LMet1|(intensity)|(color3)", _
        "LM5|(intensity)|(color1)", _
        "LM4|(intensity)|(color2)", _
        "LM3|(intensity)|(color3)", _
        "LM2|(intensity)|(color1)", _
        "LM1|(intensity)|(color2)", _
        "LSA|(intensity)|(color3)", _
        "LH9|(intensity)|(color1)", _
        "LH8|(intensity)|(color2)", _
        "LH7|(intensity)|(color3)", _
        "LH6|(intensity)|(color1)", _
        "LH5|(intensity)|(color2)", _
        "LH4|(intensity)|(color3)", _
        "LH3|(intensity)|(color1)", _
        "LH2|(intensity)|(color2)", _
        "LH1|(intensity)|(color3)", _
        "LPR1|(intensity)|(color1)", _
        "LPR3|(intensity)|(color2)", _
        "LPR2|(intensity)|(color3)", _
        "LPR6|(intensity)|(color1)", _
        "LPR5|(intensity)|(color2)", _
        "LPR4|(intensity)|(color3)", _
        "LMR2|(intensity)|(color1)", _
        "LMR1|(intensity)|(color2)", _
        "LCR2|(intensity)|(color3)", _
        "LCR1|(intensity)|(color1)", _
        "LRI|(intensity)|(color2)", _
        "LRO|(intensity)|(color3)", _
        "LLI|(intensity)|(color1)", _
        "LLO|(intensity)|(color2)", _
        "LSR|(intensity)|(color3)", _
        "LSL|(intensity)|(color1)" _
        )
    End With
End With



End Sub


