#config_version=6

config:
  - lights.yaml
  - ball_devices.yaml
  - coils.yaml
  - switches.yaml
  - sounds.yaml

playfields:
  playfield:
    tags: default
    default_source_device: balldevice_plunger

virtual_platform_start_active_switches:
  - s_Trough1
  - s_Trough2
  - s_Trough3
  - s_trough4
  - s_Trough5

