#config_version=6

hardware:
  platform: virtual

config:
  - switches.yaml
  - lights.yaml

modes:
  - base

playfields:
  playfield:
    tags: default
    default_source_device: plunger

virtual_platform_start_active_switches:
  - s_trough1
  - s_trough2
  - s_trough3
  - s_trough4
  - s_trough5

switches:
  s_left_flipper:
    number: 0-0-1
    tags: left_flipper
  s_right_flipper:
    number: 0-0-2
    tags: right_flipper
  s_upper_flipper:
    number: 0-0-3
    tags: upper_flipper

coils:
  c_flipper_left_main:
    number: 0-0-1
    default_pulse_ms: 20
  c_flipper_left_hold:
    number: 0-0-2
    allow_enable: true
  c_flipper_right_main:
    number: 0-0-3
    default_pulse_ms: 20
  c_flipper_right_hold:
    number: 0-0-4
    allow_enable: true
  c_flipper_upper_main:
    number: 0-0-5
    default_pulse_ms: 20
  c_flipper_upper_hold:
    number: 0-0-6
    allow_enable: true

  c_trough_eject:
    number: 0-0-7
    default_pulse_ms: 20
  c_plunger:
    number: 0-0-8
    default_pulse_ms: 20
  c_race_scoop:
    number: 0-0-9
    default_pulse_ms: 20
  c_hyper_vuk:
    number: 0-0-10
    default_pulse_ms: 20
  c_center_scoop:
    number: 0-0-11
    default_pulse_ms: 20


ball_devices:
  trough:
    ball_switches: s_trough1, s_trough2, s_trough3, s_trough4, s_trough5, s_trough_jam
    eject_coil: c_trough_eject
    tags: trough, home, drain
    jam_switch: s_trough_jam
    eject_coil_jam_pulse: 15ms
    eject_targets: plunger
  plunger:
    ball_switches: swPlunger1
    eject_coil: c_plunger
    mechanical_eject: true
    eject_targets: playfield
    eject_timeouts: 3s
    debug: true