#config_version=6

lights:
  gi17:
    number: 1
    subtype: led
    type: rgb
    tags: GI
  giapron:
    number: 2
    subtype: led
    type: rgb
    tags: GI
  gi22:
    number: 3
    subtype: led
    type: rgb
    tags: GI
  LStars:
    number: 4
    subtype: led
    type: rgb
    tags: GI
  gi20:
    number: 5
    subtype: led
    type: rgb
    tags: GI
  gi21:
    number: 6
    subtype: led
    type: rgb
    tags: GI
  gi19:
    number: 7
    subtype: led
    type: rgb
    tags: GI
  gi18:
    number: 8
    subtype: led
    type: rgb
    tags: GI
  gi16:
    number: 9
    subtype: led
    type: rgb
    tags: GI
  gi15:
    number: 10
    subtype: led
    type: rgb
    tags: GI
  gi14:
    number: 11
    subtype: led
    type: rgb
    tags: GI
  gi13:
    number: 12
    subtype: led
    type: rgb
    tags: GI
  gi12:
    number: 13
    subtype: led
    type: rgb
    tags: GI
  gi11:
    number: 14
    subtype: led
    type: rgb
    tags: GI
  gi10:
    number: 15
    subtype: led
    type: rgb
    tags: GI
  gi09:
    number: 16
    subtype: led
    type: rgb
    tags: GI
  gi08:
    number: 17
    subtype: led
    type: rgb
    tags: GI
  gi07:
    number: 18
    subtype: led
    type: rgb
    tags: GI
  gi06:
    number: 19
    subtype: led
    type: rgb
    tags: GI
  gi05:
    number: 20
    subtype: led
    type: rgb
    tags: GI
  gi04:
    number: 21
    subtype: led
    type: rgb
    tags: GI
  gi03:
    number: 22
    subtype: led
    type: rgb
    tags: GI
  gi02:
    number: 23
    subtype: led
    type: rgb
    tags: GI
  gi01:
    number: 24
    subtype: led
    type: rgb
    tags: GI
  LPF:
    number: 25
    subtype: led
    type: rgb
    tags: 10
  a10:
    number: 26
    subtype: led
    type: rgb
    tags: Display
  a00:
    number: 27
    subtype: led
    type: rgb
    tags: Display
  a16:
    number: 28
    subtype: led
    type: rgb
    tags: Display
  a15:
    number: 29
    subtype: led
    type: rgb
    tags: Display
  a14:
    number: 30
    subtype: led
    type: rgb
    tags: Display
  a13:
    number: 31
    subtype: led
    type: rgb
    tags: Display
  a12:
    number: 32
    subtype: led
    type: rgb
    tags: Display
  a11:
    number: 33
    subtype: led
    type: rgb
    tags: Display
  a06:
    number: 34
    subtype: led
    type: rgb
    tags: Display
  a05:
    number: 35
    subtype: led
    type: rgb
    tags: Display
  a04:
    number: 36
    subtype: led
    type: rgb
    tags: Display
  a03:
    number: 37
    subtype: led
    type: rgb
    tags: Display
  a02:
    number: 38
    subtype: led
    type: rgb
    tags: Display
  a01:
    number: 39
    subtype: led
    type: rgb
    tags: Display
  LX:
    number: 40
    subtype: led
    type: rgb
    tags: 10
  LS5:
    number: 41
    subtype: led
    type: rgb
    tags: TrainingShots
  LS1:
    number: 42
    subtype: led
    type: rgb
    tags: TrainingShots
  LSwL1:
    number: 43
    subtype: led
    type: rgb
    tags: 10
  LSwL2:
    number: 44
    subtype: led
    type: rgb
    tags: 10
  LS2:
    number: 45
    subtype: led
    type: rgb
    tags: TrainingShots
  LS3:
    number: 46
    subtype: led
    type: rgb
    tags: TrainingShots
  LS4:
    number: 47
    subtype: led
    type: rgb
    tags: TrainingShots
  LS6:
    number: 48
    subtype: led
    type: rgb
    tags: TrainingShots
  LSwC3:
    number: 49
    subtype: led
    type: rgb
    tags: 10
  LSwC2:
    number: 50
    subtype: led
    type: rgb
    tags: 10
  LSwC1:
    number: 51
    subtype: led
    type: rgb
    tags: 10
  LCWiz:
    number: 52
    subtype: led
    type: rgb
    tags: 10
  LLWiz:
    number: 53
    subtype: led
    type: rgb
    tags: 10
  LC1:
    number: 54
    subtype: led
    type: rgb
    tags: Combobar
  LC2:
    number: 55
    subtype: led
    type: rgb
    tags: Combobar
  LC3:
    number: 56
    subtype: led
    type: rgb
    tags: Combobar
  LC4:
    number: 57
    subtype: led
    type: rgb
    tags: Combobar
  LC5:
    number: 58
    subtype: led
    type: rgb
    tags: Combobar
  LC6:
    number: 59
    subtype: led
    type: rgb
    tags: Combobar
  LC7:
    number: 60
    subtype: led
    type: rgb
    tags: Combobar
  LC8:
    number: 61
    subtype: led
    type: rgb
    tags: Combobar
  LWiz:
    number: 62
    subtype: led
    type: rgb
    tags: MeteorWaves
  LW9:
    number: 63
    subtype: led
    type: rgb
    tags: MeteorWaves
  LW8:
    number: 64
    subtype: led
    type: rgb
    tags: MeteorWaves
  LW7:
    number: 65
    subtype: led
    type: rgb
    tags: MeteorWaves
  LW6:
    number: 66
    subtype: led
    type: rgb
    tags: MeteorWaves
  LW5:
    number: 67
    subtype: led
    type: rgb
    tags: MeteorWaves
  LW4:
    number: 68
    subtype: led
    type: rgb
    tags: MeteorWaves
  LW3:
    number: 69
    subtype: led
    type: rgb
    tags: MeteorWaves
  LW2:
    number: 70
    subtype: led
    type: rgb
    tags: MeteorWaves
  LW1:
    number: 71
    subtype: led
    type: rgb
    tags: MeteorWaves
  LMLR:
    number: 72
    subtype: led
    type: rgb
    tags: 10
  LEBR:
    number: 73
    subtype: led
    type: rgb
    tags: 10
  LMR:
    number: 74
    subtype: led
    type: rgb
    tags: 10
  LPC5:
    number: 75
    subtype: led
    type: rgb
    tags: 10
  LPC4:
    number: 76
    subtype: led
    type: rgb
    tags: 10
  LSC4:
    number: 77
    subtype: led
    type: rgb
    tags: ShieldShots
  LSC3:
    number: 78
    subtype: led
    type: rgb
    tags: ShieldShots
  LSC2:
    number: 79
    subtype: led
    type: rgb
    tags: ShieldShots
  LSC1:
    number: 80
    subtype: led
    type: rgb
    tags: ShieldShots
  LF3:
    number: 81
    subtype: led
    type: rgb
    tags: ShipSaveShot
  LF2:
    number: 82
    subtype: led
    type: rgb
    tags: ShipSaveShot
  LF1:
    number: 83
    subtype: led
    type: rgb
    tags: ShipSaveShot
  LPC3:
    number: 84
    subtype: led
    type: rgb
    tags: ProtonShot
  LPC2:
    number: 85
    subtype: led
    type: rgb
    tags: ProtonShot
  LPC1:
    number: 86
    subtype: led
    type: rgb
    tags: ProtonShot
  LTW4:
    number: 87
    subtype: led
    type: rgb
    tags: TimewarpShot
  LTW3:
    number: 88
    subtype: led
    type: rgb
    tags: TimewarpShot
  LTW2:
    number: 89
    subtype: led
    type: rgb
    tags: TimewarpShot
  LTW1:
    number: 90
    subtype: led
    type: rgb
    tags: TimewarpShot
  LCC3:
    number: 91
    subtype: led
    type: rgb
    tags: ClusterBombShot
  LCC2:
    number: 92
    subtype: led
    type: rgb
    tags: ClusterBombShot
  LCC1:
    number: 93
    subtype: led
    type: rgb
    tags: ClusterBombShot
  LMet4:
    number: 94
    subtype: led
    type: rgb
    tags: Meteors
  LMet3:
    number: 95
    subtype: led
    type: rgb
    tags: Meteors
  LMet2:
    number: 96
    subtype: led
    type: rgb
    tags: Meteors
  LMet1:
    number: 97
    subtype: led
    type: rgb
    tags: Meteors
  LM5:
    number: 98
    subtype: led
    type: rgb
    tags: MysteryShots
  LM4:
    number: 99
    subtype: led
    type: rgb
    tags: MysteryShots
  LM3:
    number: 100
    subtype: led
    type: rgb
    tags: MysteryShots
  LM2:
    number: 101
    subtype: led
    type: rgb
    tags: MysteryShots
  LM1:
    number: 102
    subtype: led
    type: rgb
    tags: MysteryShots
  LSA:
    number: 103
    subtype: led
    type: rgb
    tags: 10
  LH9:
    number: 104
    subtype: led
    type: rgb
    tags: Healthbar
  LH8:
    number: 105
    subtype: led
    type: rgb
    tags: Healthbar
  LH7:
    number: 106
    subtype: led
    type: rgb
    tags: Healthbar
  LH6:
    number: 107
    subtype: led
    type: rgb
    tags: Healthbar
  LH5:
    number: 108
    subtype: led
    type: rgb
    tags: Healthbar
  LH4:
    number: 109
    subtype: led
    type: rgb
    tags: Healthbar
  LH3:
    number: 110
    subtype: led
    type: rgb
    tags: Healthbar
  LH2:
    number: 111
    subtype: led
    type: rgb
    tags: Healthbar
  LH1:
    number: 112
    subtype: led
    type: rgb
    tags: Healthbar
  LPR1:
    number: 113
    subtype: led
    type: rgb
    tags: ProtonRounds
  LPR3:
    number: 114
    subtype: led
    type: rgb
    tags: ProtonRounds
  LPR2:
    number: 115
    subtype: led
    type: rgb
    tags: ProtonRounds
  LPR6:
    number: 116
    subtype: led
    type: rgb
    tags: ProtonRounds
  LPR5:
    number: 117
    subtype: led
    type: rgb
    tags: ProtonRounds
  LPR4:
    number: 118
    subtype: led
    type: rgb
    tags: ProtonRounds
  LMR2:
    number: 119
    subtype: led
    type: rgb
    tags: 10
  LMR1:
    number: 120
    subtype: led
    type: rgb
    tags: 10
  LCR2:
    number: 121
    subtype: led
    type: rgb
    tags: 10
  LCR1:
    number: 122
    subtype: led
    type: rgb
    tags: 10
  LRI:
    number: 123
    subtype: led
    type: rgb
    tags: MoonLanes
  LRO:
    number: 124
    subtype: led
    type: rgb
    tags: MoonLanes
  LLI:
    number: 125
    subtype: led
    type: rgb
    tags: MoonLanes
  LLO:
    number: 126
    subtype: led
    type: rgb
    tags: MoonLanes
  LSR:
    number: 127
    subtype: led
    type: rgb
    tags: 10
  LSL:
    number: 128
    subtype: led
    type: rgb
    tags: 10

