#config_version=6

shot_profiles:
  default:
    states: 
     - name: on
       show: flash
       loops: -1
       speed: 1
       sync_ms: 0
     advance_on_hit: True
     - name: off
       show: off
       loops: -1
       speed: 1
       sync_ms: 0
     advance_on_hit: True
  flash_color:
    states: 
     - name: off
       show: off
       loops: -1
       speed: 1
       sync_ms: 0
     advance_on_hit: True
     - name: on
       show: flash_color
       loops: -1
       speed: 1
       sync_ms: 0
     advance_on_hit: True
  off_on_color:
    states: 
     - name: unlit
       show: off
       loops: -1
       speed: 1
       sync_ms: 0
     advance_on_hit: True
     - name: on
       show: led_color
       loops: -1
       speed: 1
       sync_ms: 0
     advance_on_hit: True
  flicker_on_flicker_off:
    states: 
     - name: lit
       show: flicker_color_on
       loops: -1
       speed: 3
       sync_ms: 0
     advance_on_hit: True
     - name: unlit
       show: flicker_color_off
       loops: -1
       speed: 3
       sync_ms: 0
     advance_on_hit: True
  flicker_on:
    states: 
     - name: unlit
       show: off
       loops: -1
       speed: 1
       sync_ms: 0
     advance_on_hit: True
     - name: on
       show: flicker_color_on
       loops: -1
       speed: 4
       sync_ms: 0
     advance_on_hit: True
  powerups:
    states: 
     - name: unlit
       show: off
       loops: -1
       speed: 1
       sync_ms: 0
     advance_on_hit: True
     - name: ready
       show: flash_color_with_fade
       loops: -1
       speed: 4
       sync_ms: 0
       show_tokens: 
         fade: 400
     advance_on_hit: True
     - name: collected
       show: led_color
       loops: -1
       speed: 1
       sync_ms: 0
     advance_on_hit: True
  training_powerups:
    states: 
     - name: ready
       show: flash_color_with_fade
       loops: -1
       speed: 12
       sync_ms: 0
       show_tokens: 
         fade: 100
     advance_on_hit: True
     - name: collected
       show: led_color
       loops: -1
       speed: 1
       sync_ms: 0
     advance_on_hit: True
  qualified_shot:
    states: 
     - name: unlit
       show: off
       loops: -1
       speed: 1
       sync_ms: 0
     advance_on_hit: True
     - name: ready
       show: flash_color_with_fade
       loops: -1
       speed: 2
       sync_ms: 0
       show_tokens: 
         fade: 100
     advance_on_hit: True
  shoot_again:
    states: 
     - name: unlit
       show: off
       loops: -1
       speed: 1
       sync_ms: 0
       show_tokens: 
         lights: LSA
     advance_on_hit: True
     - name: flashing
       show: flash_color_with_fade
       loops: -1
       speed: 2
       sync_ms: 0
       show_tokens: 
         lights: LSA
         fade: 500
     advance_on_hit: True
     - name: hurry
       show: flash_color
       loops: -1
       speed: 7
       sync_ms: 0
       show_tokens: 
         lights: LSA
     advance_on_hit: True
  health_shot_ready:
    states: 
     - name: unlit
       show: off
       loops: -1
       speed: 1
       sync_ms: 0
       show_tokens: 
         lights: LDP
     advance_on_hit: True
     - name: ready
       show: flash_color_with_fade
       loops: -1
       speed: 2
       sync_ms: 0
       show_tokens: 
         fade: 500
         color: 00dd00
         lights: LDP
     advance_on_hit: True
  wizard_ready1:
    states: 
     - name: unlit
       show: off
       loops: -1
       speed: 1
       sync_ms: 0
     advance_on_hit: True
     - name: ready
       show: flash_color_with_fade
       loops: -1
       speed: 8
       sync_ms: 0
       show_tokens: 
         fade: 400
     advance_on_hit: True
     - name: collected
       show: led_color
       loops: -1
       speed: 1
       sync_ms: 0
     advance_on_hit: True
  ss_ready:
    states: 
     - name: unlit
       show: off
       loops: -1
       speed: 1
       sync_ms: 0
       show_tokens: 
         lights: LM2
     advance_on_hit: True
     - name: ready
       show: flash_color_with_fade
       loops: -1
       speed: 3
       sync_ms: 0
       show_tokens: 
         fade: 200
         color: 33dd33
         lights: LM2
     advance_on_hit: True
  alien:
    states: 
     - name: unlit
       show: off
       loops: -1
       speed: 1
       sync_ms: 0
     advance_on_hit: True
     - name: lit
       show: flash_color_with_fade
       loops: -1
       speed: 7
       sync_ms: 0
       show_tokens: 
         fade: 200
         color: ff0300
     advance_on_hit: True
     - name: grace
       show: off
       loops: -1
       speed: 1
       sync_ms: 0
     advance_on_hit: True
  qualify_shields:
    states: 
     - name: unlit
       show: off
       loops: -1
       speed: 1
       sync_ms: 0
     advance_on_hit: True
     - name: on
       show: flicker_color_on
       loops: -1
       speed: 4
       sync_ms: 0
       show_tokens: 
         color: 0010cc
     advance_on_hit: True
  shields_ready:
    states: 
     - name: unlit
       show: off
       loops: -1
       speed: 1
       sync_ms: 0
     advance_on_hit: True
     - name: on
       show: led_color
       loops: -1
       speed: 1
       sync_ms: 0
       show_tokens: 
         color: 0010cc
     advance_on_hit: True
  extraball:
    states: 
     - name: unlit
       show: off
       loops: -1
       speed: 1
       sync_ms: 0
       show_tokens: 
         lights: LSA
     advance_on_hit: True
     - name: lit
       show: led_color
       loops: -1
       speed: 1
       sync_ms: 0
       show_tokens: 
         lights: LSA
         color: 0500ee
     advance_on_hit: True
  double_scoring:
    states: 
     - name: unlit
       show: off
       loops: -1
       speed: 1
       sync_ms: 0
       show_tokens: 
         lights: LDS
         color: ff3300
     advance_on_hit: True
     - name: flashing
       show: flash_color_with_fade
       loops: -1
       speed: 2
       sync_ms: 0
       show_tokens: 
         lights: LDS
         fade: 500
         color: ff3300
     advance_on_hit: True
     - name: hurry
       show: flash_color
       loops: -1
       speed: 7
       sync_ms: 0
       show_tokens: 
         lights: LDS
         color: ff3300
     advance_on_hit: True
  super_spinner:
    states: 
     - name: unlit
       show: off
       loops: -1
       speed: 1
       sync_ms: 0
       show_tokens: 
         lights: gi21
         color: 00dddd
     advance_on_hit: True
     - name: flashing
       show: flash_color_with_fade
       loops: -1
       speed: 5
       sync_ms: 0
       show_tokens: 
         lights: gi21
         fade: 500
         color: 00dddd
     advance_on_hit: True
     - name: hurry
       show: flash_color
       loops: -1
       speed: 10
       sync_ms: 0
       show_tokens: 
         lights: gi21
         color: 00dddd
     advance_on_hit: True
  super_pops:
    states: 
     - name: unlit
       show: off
       loops: -1
       speed: 1
       sync_ms: 0
       show_tokens: 
         lights: tBumper
         color: 555555
     advance_on_hit: True
     - name: flashing
       show: flash_color_with_fade
       loops: -1
       speed: 2
       sync_ms: 0
       show_tokens: 
         lights: tBumper
         fade: 500
         color: 555555
     advance_on_hit: True
     - name: hurry
       show: flash_color
       loops: -1
       speed: 7
       sync_ms: 0
       show_tokens: 
         lights: tBumper
         color: 555555
     advance_on_hit: True
  health_meter:
    states: 
     - name: unlit
       show: off
       loops: -1
       speed: 1
       sync_ms: 0
     advance_on_hit: True
     - name: normal
       show: led_color
       loops: -1
       speed: 1
       sync_ms: 0
       show_tokens: 
         color: 00dd00
     advance_on_hit: True
     - name: warning
       show: led_color
       loops: -1
       speed: 1
       sync_ms: 0
       show_tokens: 
         color: d14c00
     advance_on_hit: True
     - name: critical
       show: flash_color
       loops: -1
       speed: 15
       sync_ms: 0
       show_tokens: 
         color: ff0300
     advance_on_hit: True
  training_profile:
    states: 
     - name: unlit
       show: off
       loops: -1
       speed: 1
       sync_ms: 0
     advance_on_hit: True
     - name: on
       show: led_color
       loops: -1
       speed: 1
       sync_ms: 0
     advance_on_hit: True
  training_select:
    states: 
     - name: unlit
       show: off
       loops: -1
       speed: 1
       sync_ms: 0
     advance_on_hit: True
     - name: ready1
       show: flash_color_with_fade
       loops: -1
       speed: 3
       sync_ms: 0
       show_tokens: 
         fade: 200
     advance_on_hit: True
     - name: ready2
       show: flash_color_with_fade
       loops: -1
       speed: 8
       sync_ms: 0
       show_tokens: 
         fade: 200
     advance_on_hit: True
     - name: on
       show: led_color
       loops: -1
       speed: 1
       sync_ms: 0
     advance_on_hit: True
  train_moon_missile:
    states: 
     - name: ready
       show: flash_color_with_fade
       loops: -1
       speed: 8
       sync_ms: 0
       show_tokens: 
         color: ccbb00
         fade: 400
     advance_on_hit: True
     - name: collected
       show: led_color
       loops: -1
       speed: 1
       sync_ms: 0
       show_tokens: 
         color: ccbb00
     advance_on_hit: True
  train_shields:
    states: 
     - name: ready
       show: flash_color_with_fade
       loops: -1
       speed: 8
       sync_ms: 0
       show_tokens: 
         color: 0010cc
         fade: 400
     advance_on_hit: True
     - name: collected
       show: led_color
       loops: -1
       speed: 1
       sync_ms: 0
       show_tokens: 
         color: 0010cc
     advance_on_hit: True
  meteor_temp:
    states: 
     - name: unlit
       show: off
       loops: -1
       speed: 1
       sync_ms: 0
     advance_on_hit: True
     - name: cool
       show: flash_color_with_fade
       loops: -1
       speed: 2
       sync_ms: 0
       show_tokens: 
         color: ffA957
         fade: 1000
     advance_on_hit: True
     - name: warm
       show: flash_color_with_fade
       loops: -1
       speed: 5
       sync_ms: 0
       show_tokens: 
         color: edb600
         fade: 1000
     advance_on_hit: True
     - name: hot
       show: flash_color
       loops: -1
       speed: 12
       sync_ms: 0
       show_tokens: 
         color: ed1800
     advance_on_hit: True
  proton_shot_ready:
    states: 
     - name: unlit
       show: off
       loops: -1
       speed: 1
       sync_ms: 0
       show_tokens: 
         lights: tFire
     advance_on_hit: True
     - name: ready
       show: flash_color_with_fade
       loops: -1
       speed: 2
       sync_ms: 0
       show_tokens: 
         fade: 400
         color: 00dddd
         lights: tFire
     advance_on_hit: True
  fully_loaded_profile:
    states: 
     - name: unlit
       show: off
       loops: -1
       speed: 1
       sync_ms: 0
     advance_on_hit: True
     - name: ready
       show: flash_color
       loops: -1
       speed: 10
       sync_ms: 0
     advance_on_hit: True
     - name: on
       show: led_color
       loops: -1
       speed: 1
       sync_ms: 0
     advance_on_hit: True
  combo_command:
    states: 
     - name: unlit
       show: off
       loops: -1
       speed: 1
       sync_ms: 0
     advance_on_hit: True
     - name: ready
       show: flash_color
       loops: -1
       speed: 10
       sync_ms: 0
       show_tokens: 
         color: ffb46b
     advance_on_hit: True
     - name: on
       show: led_color
       loops: -1
       speed: 1
       sync_ms: 0
       show_tokens: 
         color: ffb46b
     advance_on_hit: True
  asteroid:
    states: 
     - name: unlit
       show: off
       loops: -1
       speed: 1
       sync_ms: 0
       show_tokens: 
         lights: tFire
     advance_on_hit: True
     - name: ready
       show: flash_color
       loops: -1
       speed: 8
       sync_ms: 0
       show_tokens: 
         lights: tFire
         color: dd0400
     advance_on_hit: True
  fwwiz_meteor:
    states: 
     - name: unlit
       show: off
       loops: -1
       speed: 1
       sync_ms: 0
     advance_on_hit: True
     - name: ready
       show: flash_color
       loops: -1
       speed: 8
       sync_ms: 0
       show_tokens: 
         color: ed1800
     advance_on_hit: True
  victory_shots:
    states: 
     - name: unlit
       show: off
       loops: -1
       speed: 1
       sync_ms: 0
     advance_on_hit: True
     - name: ready
       show: flash_color
       loops: -1
       speed: 7
       sync_ms: 0
       show_tokens: 
         color: ffffff
     advance_on_hit: True

